/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotSha3.Extraction`. -/

/-
  # Discharging the hax-generated specs

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust. For each annotated function it
  emits

    * `<fn>.pre  : … → RustM Bool`  -- the `requires` clause,
    * `<fn>.post : … → RustM Bool`  -- the `ensures` clause, when there is one, and
    * `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  where `post` is `⌜True⌝` when the function has no `ensures`. hax also emits
  `Extraction/ProofObligations.lean`, one `@[spec] theorem <fn>.spec.proof … := by
  sorry` per obligation (46 of them). That file stays on disk but is imported by
  nothing: the lakefile has no `globs`, so the build follows the root module's
  import tree and leaves it out -- otherwise its sorries would enter the build and
  feed unproved `@[spec]` lemmas to `hax_mvcgen`. This file discharges the ones
  that matter instead.

  ## What is actually being proved

  Every obligation below is discharged by PRODUCING the generated post, not by
  weakening it: each of these entry points names its hacspec counterpart in its
  `#[ensures]`.

  Which hacspec? `hacspec_sha3_pedantic` -- the FIPS 202 transcript, whose module
  structure and naming follow the Standard's sections and algorithms rather than an
  implementation's convenience. The Lean theorems in `Sponge/` are stated against
  `hacspec_sha3`, the byte-and-lane spec the proofs were built on;
  `Composition/Pedantic/` closes the gap, proving the two agree on all six entry
  points, and the `pedantic_*` lemmas below are that agreement in the shape the
  generated posts want.

    * `shake128` / `shake256` -- the array-returning wrappers -- compare
      `out.declassify()[..]` to
      `hacspec_sha3_pedantic::bytes::shake{128,256}(data, BYTES)[..]`. The
      transcript's SHAKE returns a `Vec<u8>` (its length is a runtime argument,
      not a const generic), so both sides are taken as slices and the post ends
      in CoreModels' slice `==`.

    * The four `*_ema` entry points carry
      `#[ensures(|_| future(digest).declassify_ref()
          == &hacspec_sha3_pedantic::bytes::sha3_<n>(payload.declassify_ref())[..])]`,
      so their post is the full functional claim -- the digest IS the FIPS-202
      hash of the payload -- which is exactly what `Sponge.sha<n>_ema_spec`
      establishes, once transported onto the transcript. (The annotation used to
      lead with a second conjunct, `future(digest).len() == SHA3_<n>_DIGEST_SIZE`.
      The equality subsumes it, so it was dropped. The length is still needed
      INSIDE each proof -- it is what turns the theorem's byte-wise agreement into
      the list equality the slice `==` reduces to -- but it now comes from the
      theorem rather than from the generated post.)

  ## The input bound

  Naming the transcript costs one thing: it works on BIT strings, so it expands
  its input to `8 * len` bits and then appends the domain-separation suffix and
  `pad10*1`. That padded bit length has to be a representable `usize` on every
  supported target, the smallest being 32-bit. So the `#[requires]` clauses bound
  the input by `MAX_INPUT_LEN = (u32::MAX as usize - 4096) / 8` rather than by
  `u32::MAX` -- a narrowing from 4 GB to 512 MB, far above anything an IoT target
  will hash, and the price of stating correctness against the Standard's own text
  instead of against a spec shaped like the implementation.

  `keccak` itself carries no contract -- the FIPS-202 transcript has no
  rate-and-delimiter-parameterised byte sponge to compare it against (it exposes
  `KECCAK[c]` and the six standard functions). Its correctness is the Lean theorem
  `Sponge.keccak.keccak_keccak_spec`, which is what the six obligations below are
  proved through.

  For all six a second thing is being checked: the PRECONDITION MATCH. The
  `*_ema` theorems carry hand-written hypotheses (`payload.length ≤ 4294967295` and
  `digest.length = 28/32/48/64`) that a human wrote by reading the Rust. Deriving
  exactly those from the *generated* `.pre` -- via `max_input_len_eq`, which
  evaluates the annotated `MAX_INPUT_LEN` -- is what checks that the hand-written
  hypotheses really are the annotated precondition rather than a convenient
  approximation of it. A mismatch there is precisely the kind of gap that makes a
  green development mean less than it looks, and it stays invisible until the two
  are connected as they are here.

  What this does NOT establish: `shake128_ema` / `shake256_ema` carry a `requires`
  with no `ensures`, so their obligations say only "under the annotated
  precondition, this neither panics nor diverges"; they are not discharged here and
  remain `sorry`ed in the unbuilt generated file.
-/
import LibcruxIotSha3.Extraction
import LibcruxIotSha3.Sponge.Shake
import LibcruxIotSha3.Composition.SliceEq
import LibcruxIotSha3.Composition.Pedantic.LaneSqueeze

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_sha3.Verification

/-! ## Small bridges between the generated shapes and the Lean theorems -/

/-- Decoding a generated precondition. `<fn>.pre` is a `RustM Bool` while
    `RustM.holds` wants a `RustM Prop`, so the generated `.spec` inserts a
    `(· = true) <$> ·`; on an `ok` that collapses to the plain boolean fact. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Decoding the input bound in the generated `pre`. `MAX_INPUT_LEN` is
    `(u32::MAX as usize - 4096) / 8`: the FIPS-202 transcript the `#[ensures]`
    clauses name works on BIT strings, so `8 * len`, plus the suffix and
    `pad10*1`, has to be a representable `usize` on a 32-bit target. -/
private theorem len_le_of_le_max {s : Slice Std.U8}
    (h : Aeneas.Std.Slice.len s ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)) :
    s.val.length ≤ 536870399 := by
  have hv : (Aeneas.Std.Slice.len s).val
      ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize).val := by scalar_tac
  rw [Aeneas.Std.Slice.len_val, Sponge.max_input_len_val] at hv
  exact hv

/-- Converse of `bool_of_holds_map_ok`: build a generated `post`'s `.holds` from
    the plain boolean fact. -/
private theorem holds_map_ok_of_bool {b : Bool} (h : b = true) :
    RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool)) := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap]
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Triple from an `ok` equation plus the post fact. -/
private theorem triple_of_ok {α : Type} {x : RustM α} {v : α} {P : α → Prop}
    (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

/-- Triple to existential (stated with `x` a variable so the `match` substitutes). -/
private theorem triple_exists_ok {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) : ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'; exact h'
  | .fail e =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-! ## Shared machinery for the functional-correctness posts

    All six generated posts end the same way: declassify, call the hacspec, take
    `[..]` of its array output, and compare slices. These five lemmas are that
    shape, factored out. -/

/-- `declassify_ref` on a shared slice is the identity (Assumptions/FunsExternal). -/
private theorem decl_ref_eq (s : Slice Std.U8) :
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar s = .ok s := rfl

/-- `arr[..]` is `arr` viewed as a slice. -/
private theorem range_full_index_eq {N : Std.Usize} (arr : Std.Array Std.U8 N) :
    (CoreModels.core.Array.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.Slice.Insts.CoreOpsIndexIndex
        (CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
          Std.U8))
      arr ()) = .ok (Aeneas.Std.Array.to_slice arr) := by
  simp [CoreModels.core.Array.Insts.CoreOpsIndexIndex.index,
    CoreModels.core.array.Array.as_slice,
    CoreModels.rust_primitives.slice.array_as_slice,
    CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index,
    CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get]

/-- Elementwise agreement over a common length gives list equality. The theorems
    state their posts elementwise because the digest is a `Slice` while the
    hacspec output is an `Array`, so the two are not the same Lean type. -/
private theorem val_eq_of_bytes {N : Nat} {v : Slice Std.U8} {M : Std.Usize}
    {spec_out : Std.Array Std.U8 M}
    (hv_len : v.val.length = N) (hso : spec_out.val.length = N)
    (hbytes : ∀ k : Nat, k < N → v.val[k]! = spec_out.val[k]!) :
    v.val = (Aeneas.Std.Array.to_slice spec_out).val := by
  rw [Aeneas.Std.Array.val_to_slice]
  apply List.ext_getElem (by rw [hv_len, hso])
  intro k h1 _h2
  have h1' : k < N := by rw [hv_len] at h1; exact h1
  have hk := hbytes k h1'
  rwa [List.getElem!_eq_getElem?_getD, List.getElem!_eq_getElem?_getD,
    List.getElem?_eq_getElem h1,
    List.getElem?_eq_getElem (show k < spec_out.val.length by rw [hso]; exact h1')] at hk

/-- The `shake` variant: both sides are arrays of the same length `M`, so the
    length side conditions come from the types. -/
private theorem to_slice_val_eq_of_bytes {M : Std.Usize}
    {v spec_out : Std.Array Std.U8 M}
    (hbytes : ∀ k : Nat, k < M.val → v.val[k]! = spec_out.val[k]!) :
    (Aeneas.Std.Array.to_slice v).val = (Aeneas.Std.Array.to_slice spec_out).val := by
  rw [Aeneas.Std.Array.val_to_slice, Aeneas.Std.Array.val_to_slice]
  have hv : v.val.length = M.val := by simp
  have hs : spec_out.val.length = M.val := by simp
  apply List.ext_getElem (by rw [hv, hs])
  intro k h1 _h2
  have h1' : k < M.val := by rw [hv] at h1; exact h1
  have hk := hbytes k h1'
  rwa [List.getElem!_eq_getElem?_getD, List.getElem!_eq_getElem?_getD,
    List.getElem?_eq_getElem h1,
    List.getElem?_eq_getElem (show k < spec_out.val.length by rw [hs]; exact h1')] at hk

/-- The slice comparison that ends every one of these posts returns `true`.
    `Composition.slice_eq_spec` is the closed form for
    `core::cmp::PartialEq for [T]`, which CoreModels implements as a loop. -/
private theorem slice_eq_true {a b : Slice Std.U8} (h : a.val = b.val) :
    CoreModels.core.Slice.Insts.CoreCmpPartialEqSlice.eq
      CoreModels.core.U8.Insts.CoreCmpPartialEqU8 a b = .ok true := by
  obtain ⟨r, hr_eq, hr_iff⟩ := triple_exists_ok
    (Composition.slice_eq_spec CoreModels.core.U8.Insts.CoreCmpPartialEqU8
      Composition.lawful_partialEq_u8 a b)
  rw [hr_eq, hr_iff.mpr h]

/-- `declassify` by value (blanket instance) is the identity (Assumptions/FunsExternal). -/
private theorem decl_blanket_eq {T : Type} (x : T) :
    libcrux_secrets.traits.Declassify.Blanket.declassify x = .ok x := rfl

/-- In-range `Slice.index_usize` as an equation (array-equality helper). -/
private theorem slice_index_ok_arr {T : Type} [Inhabited T] (s : Aeneas.Std.Slice T)
    (i : Std.Usize) (h : i.val < s.val.length) :
    Aeneas.Std.Slice.index_usize s i = .ok (s.val[i.val]!) := by
  unfold Aeneas.Std.Slice.index_usize
  rw [Aeneas.Std.Slice.getElem?_Usize_eq, List.getElem?_eq_getElem h,
    List.getElem!_eq_getElem?_getD, List.getElem?_eq_getElem h]
  rfl

private theorem array_index_self_ok {T : Type} [Inhabited T] {N : Std.Usize}
    (x : Std.Array T N) (i : Std.Usize) (h : i.val < N.val) :
    CoreModels.rust_primitives.slice.array_index x i = .ok (x.val[i.val]!) := by
  have hlen : (Aeneas.Std.Array.to_slice x).val.length = N.val := by
    rw [Aeneas.Std.Array.val_to_slice]; exact x.property
  unfold CoreModels.rust_primitives.slice.array_index
  rw [slice_index_ok_arr (Aeneas.Std.Array.to_slice x) i (by rw [hlen]; exact h),
    Aeneas.Std.Array.val_to_slice]

/-- The element-wise `==` loop of CoreModels' array `PartialEq` on equal arrays
    returns `ok true` (downward induction on the remaining `fuel = N - i`; the
    ml-kem tree carries the same lemma). -/
private theorem array_eq_loop_self {T : Type} [Inhabited T] {N : Std.Usize}
    (inst : CoreModels.core.cmp.PartialEq T T) (x : Std.Array T N)
    (hrefl : ∀ j : Nat, j < N.val → inst.eq (x.val[j]!) (x.val[j]!) = .ok true) :
    ∀ (fuel : Nat) (i : Std.Usize), i.val + fuel = N.val →
      CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop inst x x i = .ok true := by
  intro fuel
  induction fuel with
  | zero =>
      intro i hi
      unfold CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop
      rw [Aeneas.Std.loop.eq_1]
      simp only [CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop.body]
      have hnlt : ¬ (i < N) := by scalar_tac
      simp only [hnlt, if_false]
  | succ f ih =>
      intro i hi
      have hlt : i.val < N.val := by omega
      have hltB : (i < N) := by scalar_tac
      have hNmax : N.val ≤ Aeneas.Std.UScalar.max .Usize := by
        have := N.hBounds; scalar_tac
      have hadd : ∃ i1 : Std.Usize,
          (i + 1#usize : RustM Std.Usize) = .ok i1 ∧ i1.val = i.val + 1 := by
        obtain ⟨i1, h1, h2, _⟩ :=
          Aeneas.Std.WP.spec_imp_exists (Aeneas.Std.UScalar.add_bv_spec (x := i) (y := 1#usize)
            (by show i.val + 1 ≤ Aeneas.Std.UScalar.max .Usize; omega))
        exact ⟨i1, h1, by simp [h2]⟩
      obtain ⟨i1, hi1_eq, hi1_val⟩ := hadd
      unfold CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop
      rw [Aeneas.Std.loop.eq_1]
      simp only [CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop.body,
        if_pos hltB, array_index_self_ok x i hlt, bind_tc_ok, hrefl i.val hlt, hi1_eq,
        if_true]
      show CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq_loop inst x x i1 = .ok true
      exact ih i1 (by omega)

/-- Rust `==` on two `U8` arrays with equal contents is `ok true`. -/
private theorem array_eq_true {N : Std.Usize} {a b : Std.Array Std.U8 N} (h : a.val = b.val) :
    CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq
      CoreModels.core.U8.Insts.CoreCmpPartialEqU8 a b = .ok true := by
  have hab : a = b := Subtype.ext h
  subst hab
  unfold CoreModels.core.Array.Insts.CoreCmpPartialEqArray.eq
  exact array_eq_loop_self _ a (fun j _ => by
      simp [CoreModels.core.U8.Insts.CoreCmpPartialEqU8]) N.val 0#usize (by simp)

/-! ## Transporting the hacspec results onto the FIPS-202 transcript

    The `#[ensures]` clauses name `hacspec_sha3_pedantic`, the FIPS 202 transcript;
    the Lean theorems in `Sponge/` are stated against `hacspec_sha3`, the spec they
    were built on.  `Composition/Pedantic/` proves the two agree, and these six
    lemmas are that agreement in the shape the posts want. -/

private theorem pedantic_sha3_224 {payload : Slice Std.U8}
    {spec_out : Std.Array Std.U8 28#usize}
    (hb : 8 * payload.val.length + 2 ≤ 4294965000)
    (h : hacspec_sha3.sha3.sha3_224 payload = .ok spec_out) :
    hacspec_sha3_pedantic.bytes.sha3_224 payload = .ok spec_out := by
  obtain ⟨o, h1, h2⟩ := LibcruxIotSha3.Composition.Pedantic.sha3_224_agree payload hb
  have ho : o = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ho ▸ h2

private theorem pedantic_sha3_256 {payload : Slice Std.U8}
    {spec_out : Std.Array Std.U8 32#usize}
    (hb : 8 * payload.val.length + 2 ≤ 4294965000)
    (h : hacspec_sha3.sha3.sha3_256 payload = .ok spec_out) :
    hacspec_sha3_pedantic.bytes.sha3_256 payload = .ok spec_out := by
  obtain ⟨o, h1, h2⟩ := LibcruxIotSha3.Composition.Pedantic.sha3_256_agree payload hb
  have ho : o = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ho ▸ h2

private theorem pedantic_sha3_384 {payload : Slice Std.U8}
    {spec_out : Std.Array Std.U8 48#usize}
    (hb : 8 * payload.val.length + 2 ≤ 4294965000)
    (h : hacspec_sha3.sha3.sha3_384 payload = .ok spec_out) :
    hacspec_sha3_pedantic.bytes.sha3_384 payload = .ok spec_out := by
  obtain ⟨o, h1, h2⟩ := LibcruxIotSha3.Composition.Pedantic.sha3_384_agree payload hb
  have ho : o = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ho ▸ h2

private theorem pedantic_sha3_512 {payload : Slice Std.U8}
    {spec_out : Std.Array Std.U8 64#usize}
    (hb : 8 * payload.val.length + 2 ≤ 4294965000)
    (h : hacspec_sha3.sha3.sha3_512 payload = .ok spec_out) :
    hacspec_sha3_pedantic.bytes.sha3_512 payload = .ok spec_out := by
  obtain ⟨o, h1, h2⟩ := LibcruxIotSha3.Composition.Pedantic.sha3_512_agree payload hb
  have ho : o = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ho ▸ h2

private theorem pedantic_shake128 {BYTES : Std.Usize} {data : Slice Std.U8}
    {spec_out : Std.Array Std.U8 BYTES}
    (hb : 8 * BYTES.val ≤ 4294965000) (hm : 8 * data.val.length + 4 ≤ 4294965000)
    (h : hacspec_sha3.sha3.shake128 BYTES data = .ok spec_out) :
    ∃ v : CoreModels.alloc.vec.Vec Std.U8,
      hacspec_sha3_pedantic.bytes.shake128 data BYTES = .ok v ∧ v.val = spec_out.val := by
  obtain ⟨o1, o2, h1, h2, hv⟩ :=
    LibcruxIotSha3.Composition.Pedantic.shake128_agree BYTES data (by omega) hb hm
  have ho : o1 = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ⟨o2, h2, by rw [← hv, ho]⟩

private theorem pedantic_shake256 {BYTES : Std.Usize} {data : Slice Std.U8}
    {spec_out : Std.Array Std.U8 BYTES}
    (hb : 8 * BYTES.val ≤ 4294965000) (hm : 8 * data.val.length + 4 ≤ 4294965000)
    (h : hacspec_sha3.sha3.shake256 BYTES data = .ok spec_out) :
    ∃ v : CoreModels.alloc.vec.Vec Std.U8,
      hacspec_sha3_pedantic.bytes.shake256 data BYTES = .ok v ∧ v.val = spec_out.val := by
  obtain ⟨o1, o2, h1, h2, hv⟩ :=
    LibcruxIotSha3.Composition.Pedantic.shake256_agree BYTES data (by omega) hb hm
  have ho : o1 = spec_out := RustM.ok.inj (h1.symm.trans h)
  exact ⟨o2, h2, by rw [← hv, ho]⟩

/-- `vec[..]` is the vector viewed as a slice (the SHAKE posts end on a `Vec`,
    since the FIPS-202 transcript's SHAKE returns one). -/
private theorem vec_range_full_index_eq (v : CoreModels.alloc.vec.Vec Std.U8) :
    (CoreModels.alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) v ()) = .ok ⟨v.val, v.property⟩ := by
  simp [CoreModels.alloc.vec.Vec.Insts.CoreOpsIndexIndex.index,
    CoreModels.alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref,
    CoreModels.alloc.vec.Vec.as_slice, CoreModels.rust_primitives.sequence.seq_to_slice,
    CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index,
    CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get]

/-! ## SHAKE128 / SHAKE256

    Discharged OUTRIGHT with the full functional-correctness post. The generated
    `pre` bounds `BYTES` by `u32::MAX`; the correctness theorems do not need it,
    so it is introduced and dropped.

    The contract compares the `[U8; BYTES]` result to the hacspec array directly
    (`out.declassify() == hacspec_sha3::shake128::<BYTES>(…)`), so the post ends in
    CoreModels' array `==`, closed by `array_eq_true` once the two arrays are
    shown equal from the per-byte agreement. `post` is applied as `post data v`,
    `BYTES` inferred from `v`'s type. -/

theorem shake128_spec_proof (BYTES : Std.Usize) (data : Slice Std.U8) :
    libcrux_iot_sha3.shake128.spec BYTES data := by
  intro hpre
  simp only [libcrux_iot_sha3.shake128.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : BYTES ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hB : BYTES.val ≤ 536870399 := by
      have hv : BYTES.val ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize).val := by scalar_tac
      rw [Sponge.max_input_len_val] at hv
      exact hv
    have hdlen : data.val.length ≤ 536870399 :=
      len_le_of_le_max (of_decide_eq_true (bool_of_holds_map_ok hpre))
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_bytes⟩ :=
      triple_exists_ok (Sponge.shake128_spec BYTES data)
    obtain ⟨pv, hpv, hpvv⟩ := pedantic_shake128 (by omega) (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.shake128.post data v = .ok true := by
      simp only [libcrux_iot_sha3.shake128.post]
      rw [decl_blanket_eq v, Aeneas.Std.bind_tc_ok, range_full_index_eq v,
        Aeneas.Std.bind_tc_ok, decl_ref_eq data, Aeneas.Std.bind_tc_ok,
        hpv, Aeneas.Std.bind_tc_ok, vec_range_full_index_eq pv, Aeneas.Std.bind_tc_ok]
      refine slice_eq_true ?_
      show (Aeneas.Std.Array.to_slice v).val = pv.val
      rw [hpvv, Aeneas.Std.Array.val_to_slice]
      have h := to_slice_val_eq_of_bytes hv_bytes
      rwa [Aeneas.Std.Array.val_to_slice, Aeneas.Std.Array.val_to_slice] at h
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem shake256_spec_proof (BYTES : Std.Usize) (data : Slice Std.U8) :
    libcrux_iot_sha3.shake256.spec BYTES data := by
  intro hpre
  simp only [libcrux_iot_sha3.shake256.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : BYTES ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hB : BYTES.val ≤ 536870399 := by
      have hv : BYTES.val ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize).val := by scalar_tac
      rw [Sponge.max_input_len_val] at hv
      exact hv
    have hdlen : data.val.length ≤ 536870399 :=
      len_le_of_le_max (of_decide_eq_true (bool_of_holds_map_ok hpre))
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_bytes⟩ :=
      triple_exists_ok (Sponge.shake256_spec BYTES data)
    obtain ⟨pv, hpv, hpvv⟩ := pedantic_shake256 (by omega) (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.shake256.post data v = .ok true := by
      simp only [libcrux_iot_sha3.shake256.post]
      rw [decl_blanket_eq v, Aeneas.Std.bind_tc_ok, range_full_index_eq v,
        Aeneas.Std.bind_tc_ok, decl_ref_eq data, Aeneas.Std.bind_tc_ok,
        hpv, Aeneas.Std.bind_tc_ok, vec_range_full_index_eq pv, Aeneas.Std.bind_tc_ok]
      refine slice_eq_true ?_
      show (Aeneas.Std.Array.to_slice v).val = pv.val
      rw [hpvv, Aeneas.Std.Array.val_to_slice]
      have h := to_slice_val_eq_of_bytes hv_bytes
      rwa [Aeneas.Std.Array.val_to_slice, Aeneas.Std.Array.val_to_slice] at h
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

/-! ## SHA3-224/256/384/512 (EMA)

    Discharged OUTRIGHT with the full functional-correctness post. The generated
    `pre` is `payload.len() <= u32::MAX && digest.len() == SIZE`, and the
    correctness theorems want exactly those two facts as hypotheses.

    Each `#[ensures]` names the corresponding hacspec directly, so the generated
    `post` says the digest IS the FIPS-202 digest of the payload rather than
    merely that it has the right length. -/

theorem sha224_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha224_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha224_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hplen : payload.val.length ≤ 536870399 := len_le_of_le_max hcond
    have hd : digest.len = libcrux_iot_sha3.SHA3_224_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 28 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_224_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha224_ema_spec digest payload (by omega) hlen)
    have hped : hacspec_sha3_pedantic.bytes.sha3_224 payload = .ok spec_out :=
      pedantic_sha3_224 (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.sha224_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha224_ema.post]
      rw [decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hped, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha256_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha256_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha256_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hplen : payload.val.length ≤ 536870399 := len_le_of_le_max hcond
    have hd : digest.len = libcrux_iot_sha3.SHA3_256_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 32 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_256_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha256_ema_spec digest payload (by omega) hlen)
    have hped : hacspec_sha3_pedantic.bytes.sha3_256 payload = .ok spec_out :=
      pedantic_sha3_256 (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.sha256_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha256_ema.post]
      rw [decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hped, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha384_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha384_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha384_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hplen : payload.val.length ≤ 536870399 := len_le_of_le_max hcond
    have hd : digest.len = libcrux_iot_sha3.SHA3_384_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 48 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_384_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha384_ema_spec digest payload (by omega) hlen)
    have hped : hacspec_sha3_pedantic.bytes.sha3_384 payload = .ok spec_out :=
      pedantic_sha3_384 (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.sha384_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha384_ema.post]
      rw [decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hped, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha512_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha512_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha512_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload ≤ (libcrux_iot_sha3.MAX_INPUT_LEN : Std.Usize)
  · rw [if_pos hcond] at hpre
    have hplen : payload.val.length ≤ 536870399 := len_le_of_le_max hcond
    have hd : digest.len = libcrux_iot_sha3.SHA3_512_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 64 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_512_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha512_ema_spec digest payload (by omega) hlen)
    have hped : hacspec_sha3_pedantic.bytes.sha3_512 payload = .ok spec_out :=
      pedantic_sha3_512 (by omega) hspec_eq
    refine triple_of_ok hv_eq ?_
    have hpost : libcrux_iot_sha3.sha512_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha512_ema.post]
      rw [decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hped, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)


/-! ## Axiom guards
    Pinned by `#guard_msgs`: the build fails if a result comes to depend on any axiom
    beyond Lean's standard three (an admitted `sorry`, or `Lean.ofReduceBool` from
    `bv_decide`/`native_decide`). -/
/--
info: 'libcrux_iot_sha3.Verification.shake128_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms shake128_spec_proof

/--
info: 'libcrux_iot_sha3.Verification.shake256_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms shake256_spec_proof

/--
info: 'libcrux_iot_sha3.Verification.sha224_ema_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms sha224_ema_spec_proof

/--
info: 'libcrux_iot_sha3.Verification.sha256_ema_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms sha256_ema_spec_proof

/--
info: 'libcrux_iot_sha3.Verification.sha384_ema_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms sha384_ema_spec_proof

/--
info: 'libcrux_iot_sha3.Verification.sha512_ema_spec_proof' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms sha512_ema_spec_proof

end libcrux_iot_sha3.Verification
