/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotSha3.Extraction`. -/

/-
  # Discharging the hax-generated specs

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust. For each annotated function it
  emits

    * `<fn>.pre  : … → RustM Bool`  -- the `requires` clause, and
    * `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  where `post` is `⌜True⌝` when the function has no `ensures`. hax also emits an
  `Extraction/ProofObligations.lean` with `@[spec] theorem <fn>.spec.proof … := by
  sorry` for every one of them; the extraction driver DROPS that file, because its
  bodies are `sorry` and every one is `@[spec]`-tagged, so keeping it would both
  put sorries in the build and feed unproved specs to `hax_mvcgen`. This file
  discharges the ones that matter instead.

  ## What is actually being proved

  The two SHAKE entry points carry `requires` but no `ensures`, so their generated
  `post` is `⌜True⌝` and `<fn>.spec` says exactly: **under the Rust-annotated
  precondition, the function neither panics nor diverges**. That follows from the
  functional-correctness Triple by post-weakening (`triple_true_of_triple`).

  The four `*_ema` entry points now also carry
  `#[ensures(|_| future(digest).len() == SHA3_<n>_DIGEST_SIZE)]`, added so the
  generated spec says something closer to what the Lean theorems actually prove.
  Their `post` is therefore a REAL property, and it is one of the conjuncts
  `Sponge.sha<n>_ema_spec` already establishes, so those four are discharged by
  producing the post rather than by weakening it.

  The content is therefore not in the weakening -- it is in the PRECONDITION
  MATCH. The four `*_ema` theorems carry hand-written hypotheses
  (`payload.length ≤ 4294967295` and `digest.length = 28/32/48/64`) that a human
  wrote by reading the Rust. Deriving exactly those from the *generated* `.pre` is
  what checks that the hand-written hypotheses really are the annotated
  precondition rather than a convenient approximation of it. A mismatch there is
  precisely the kind of gap that makes a green development mean less than it
  looks, and it stays invisible until the two are connected as they are here.

  What this does NOT establish: the two SHAKE entry points have a `requires`
  (`BYTES <= u32::MAX`) that their correctness theorems never needed, so for those
  the generated precondition is introduced and discarded. That is sound -- a
  theorem proved without a hypothesis certainly holds with it -- but it means the
  SHAKE obligations add no information beyond what `Sponge/Shake.lean` already
  had. The `*_ema` four are where this file has real content.
-/
import LibcruxIotSha3.Extraction
import LibcruxIotSha3.Sponge.Shake
import LibcruxIotSha3.Composition.SliceEq

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_sha3.Verification

/-! ## Two small bridges -/

/-- A Triple with a `⌜True⌝` post says exactly "this computation does not fail
    and does not diverge", so any stronger post implies it. -/
private theorem triple_true_of_triple {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ True ⌝ ⦄ := by
  -- `match hx : x` already rewrites `x` inside `h`, so no `rw [hx] at h` is needed.
  match hx : x with
  | .ok v => simp [Std.Do.Triple, WP.wp, PredTrans.apply]
  | .fail e =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-- Decoding a generated precondition. `<fn>.pre` is a `RustM Bool` while
    `RustM.holds` wants a `RustM Prop`, so the generated `.spec` inserts a
    `(· = true) <$> ·`; on an `ok` that collapses to the plain boolean fact. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- The `u32::MAX as usize` bound in the generated `pre`, at the `Nat` level.
    `UScalar.cast_val_eq` leaves a `% 2^Usize.numBits`, which is the identity here
    because `Usize.numBits >= 32`. -/
private theorem payload_len_le {payload : Slice Std.U8}
    (h : Aeneas.Std.Slice.len payload
          ≤ Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize CoreModels.core.num.U32.MAX) :
    payload.val.length ≤ 4294967295 := by
  have hmax : (Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize
      CoreModels.core.num.U32.MAX).val = 4294967295 := by
    rw [Aeneas.Std.UScalar.cast_val_eq]
    have hlt : (4294967295 : Nat) < 2 ^ Aeneas.Std.UScalarTy.Usize.numBits := by
      rw [Aeneas.Std.UScalarTy.Usize_numBits_eq]
      rcases System.Platform.numBits_eq with hb | hb <;> rw [hb] <;> norm_num
    show (CoreModels.core.num.U32.MAX).val % _ = _
    rw [show (CoreModels.core.num.U32.MAX).val = 4294967295 from
      Aeneas.Std.UScalar.ofNatCore_val_eq (by simp [Aeneas.Std.U32.rMax])]
    exact Nat.mod_eq_of_lt hlt
  have hv : (Aeneas.Std.Slice.len payload).val
      ≤ (Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize
            CoreModels.core.num.U32.MAX).val := by scalar_tac
  rw [Aeneas.Std.Slice.len_val, hmax] at hv
  exact hv

/-- Converse of `bool_of_holds_map_ok`: build a generated `post`'s `.holds` from
    the plain boolean fact. -/
private theorem holds_map_ok_of_bool {b : Bool} (h : b = true) :
    RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool)) := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap]
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Triple from an `ok` equation plus the post fact. -/
private theorem triple_of_ok {α : Type} {x : RustM α} {v : α} {P : α → Prop}
    (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

/-- Triple to existential (stated with `x` a variable so the `match` substitutes). -/
private theorem triple_exists_ok {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) : ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'; exact h'
  | .fail e =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-! ## Shared machinery for the functional-correctness posts

    All six generated posts end the same way: declassify, call the hacspec, take
    `[..]` of its array output, and compare slices. These five lemmas are that
    shape, factored out. -/

/-- `declassify_ref` on a shared slice is the identity (Assumptions/FunsExternal). -/
private theorem decl_ref_eq (s : Slice Std.U8) :
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar s = .ok s := rfl

/-- `arr[..]` is `arr` viewed as a slice. -/
private theorem range_full_index_eq {N : Std.Usize} (arr : Std.Array Std.U8 N) :
    (CoreModels.core.Array.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.Slice.Insts.CoreOpsIndexIndex
        (CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
          Std.U8))
      arr ()) = .ok (Aeneas.Std.Array.to_slice arr) := by
  simp [CoreModels.core.Array.Insts.CoreOpsIndexIndex.index,
    CoreModels.core.array.Array.as_slice,
    CoreModels.rust_primitives.slice.array_as_slice,
    CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index,
    CoreModels.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get]

/-- Elementwise agreement over a common length gives list equality. The theorems
    state their posts elementwise because the digest is a `Slice` while the
    hacspec output is an `Array`, so the two are not the same Lean type. -/
private theorem val_eq_of_bytes {N : Nat} {v : Slice Std.U8} {M : Std.Usize}
    {spec_out : Std.Array Std.U8 M}
    (hv_len : v.val.length = N) (hso : spec_out.val.length = N)
    (hbytes : ∀ k : Nat, k < N → v.val[k]! = spec_out.val[k]!) :
    v.val = (Aeneas.Std.Array.to_slice spec_out).val := by
  rw [Aeneas.Std.Array.val_to_slice]
  apply List.ext_getElem (by rw [hv_len, hso])
  intro k h1 _h2
  have h1' : k < N := by rw [hv_len] at h1; exact h1
  have hk := hbytes k h1'
  rwa [List.getElem!_eq_getElem?_getD, List.getElem!_eq_getElem?_getD,
    List.getElem?_eq_getElem h1,
    List.getElem?_eq_getElem (show k < spec_out.val.length by rw [hso]; exact h1')] at hk

/-- The `shake` variant: both sides are arrays of the same length `M`, so the
    length side conditions come from the types. -/
private theorem to_slice_val_eq_of_bytes {M : Std.Usize}
    {v spec_out : Std.Array Std.U8 M}
    (hbytes : ∀ k : Nat, k < M.val → v.val[k]! = spec_out.val[k]!) :
    (Aeneas.Std.Array.to_slice v).val = (Aeneas.Std.Array.to_slice spec_out).val := by
  rw [Aeneas.Std.Array.val_to_slice, Aeneas.Std.Array.val_to_slice]
  have hv : v.val.length = M.val := by simp
  have hs : spec_out.val.length = M.val := by simp
  apply List.ext_getElem (by rw [hv, hs])
  intro k h1 _h2
  have h1' : k < M.val := by rw [hv] at h1; exact h1
  have hk := hbytes k h1'
  rwa [List.getElem!_eq_getElem?_getD, List.getElem!_eq_getElem?_getD,
    List.getElem?_eq_getElem h1,
    List.getElem?_eq_getElem (show k < spec_out.val.length by rw [hs]; exact h1')] at hk

/-- The slice comparison that ends every one of these posts returns `true`.
    `Composition.slice_eq_spec` is the closed form for
    `core::cmp::PartialEq for [T]`, which CoreModels implements as a loop. -/
private theorem slice_eq_true {a b : Slice Std.U8} (h : a.val = b.val) :
    CoreModels.core.Slice.Insts.CoreCmpPartialEqSlice.eq
      CoreModels.core.U8.Insts.CoreCmpPartialEqU8 a b = .ok true := by
  obtain ⟨r, hr_eq, hr_iff⟩ := triple_exists_ok
    (Composition.slice_eq_spec CoreModels.core.U8.Insts.CoreCmpPartialEqU8
      Composition.lawful_partialEq_u8 a b)
  rw [hr_eq, hr_iff.mpr h]

/-! ## SHAKE128 / SHAKE256

    Discharged OUTRIGHT with the full functional-correctness post. The generated
    `pre` bounds `BYTES` by `u32::MAX`; the correctness theorems do not need it,
    so it is introduced and dropped.

    NOTE these two need a driver fix-up: aeneas binds `BYTES` IMPLICITLY in
    `<fn>.post` but applies it EXPLICITLY in `<fn>.spec`, so the emitted Lean does
    not typecheck as generated. See the pass in `hax_aeneas.py`. -/

theorem shake128_spec_proof (BYTES : Std.Usize) (data : Slice Std.U8) :
    libcrux_iot_sha3.shake128.spec BYTES data := by
  intro _
  obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_bytes⟩ :=
    triple_exists_ok (Sponge.shake128_spec BYTES data)
  refine triple_of_ok hv_eq ?_
  have hpost : libcrux_iot_sha3.shake128.post BYTES data v = .ok true := by
    simp only [libcrux_iot_sha3.shake128.post]
    rw [range_full_index_eq v, Aeneas.Std.bind_tc_ok,
      decl_ref_eq (Aeneas.Std.Array.to_slice v), Aeneas.Std.bind_tc_ok,
      decl_ref_eq data, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
      range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
    exact slice_eq_true (to_slice_val_eq_of_bytes hv_bytes)
  rw [hpost]
  exact holds_map_ok_of_bool rfl

theorem shake256_spec_proof (BYTES : Std.Usize) (data : Slice Std.U8) :
    libcrux_iot_sha3.shake256.spec BYTES data := by
  intro _
  obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_bytes⟩ :=
    triple_exists_ok (Sponge.shake256_spec BYTES data)
  refine triple_of_ok hv_eq ?_
  have hpost : libcrux_iot_sha3.shake256.post BYTES data v = .ok true := by
    simp only [libcrux_iot_sha3.shake256.post]
    rw [range_full_index_eq v, Aeneas.Std.bind_tc_ok,
      decl_ref_eq (Aeneas.Std.Array.to_slice v), Aeneas.Std.bind_tc_ok,
      decl_ref_eq data, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
      range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
    exact slice_eq_true (to_slice_val_eq_of_bytes hv_bytes)
  rw [hpost]
  exact holds_map_ok_of_bool rfl

/-! ## SHA3-224/256/384/512 (EMA)

    Discharged OUTRIGHT with the full functional-correctness post. The generated
    `pre` is `payload.len() <= u32::MAX && digest.len() == SIZE`, and the
    correctness theorems want exactly those two facts as hypotheses.

    Each `#[ensures]` names the corresponding hacspec directly, so the generated
    `post` says the digest IS the FIPS-202 digest of the payload rather than
    merely that it has the right length. -/

theorem sha224_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha224_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha224_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok, Aeneas.Std.lift] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload
      ≤ Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize CoreModels.core.num.U32.MAX
  · rw [if_pos hcond] at hpre
    have hd : digest.len = libcrux_iot_sha3.SHA3_224_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 28 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_224_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha224_ema_spec digest payload (payload_len_le hcond) hlen)
    refine triple_of_ok hv_eq ?_
    have hlen_usize : Aeneas.Std.Slice.len v = libcrux_iot_sha3.SHA3_224_DIGEST_SIZE := by
      apply Aeneas.Std.UScalar.eq_of_val_eq
      rw [Aeneas.Std.Slice.len_val]
      show v.val.length = _
      rw [hv_len]
      simp [libcrux_iot_sha3.SHA3_224_DIGEST_SIZE]
    have hpost : libcrux_iot_sha3.sha224_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha224_ema.post,
        CoreModels.core.slice.Slice.len,
        CoreModels.rust_primitives.slice.slice_length, Aeneas.Std.bind_tc_ok]
      rw [if_pos hlen_usize, decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha256_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha256_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha256_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok, Aeneas.Std.lift] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload
      ≤ Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize CoreModels.core.num.U32.MAX
  · rw [if_pos hcond] at hpre
    have hd : digest.len = libcrux_iot_sha3.SHA3_256_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 32 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_256_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha256_ema_spec digest payload (payload_len_le hcond) hlen)
    refine triple_of_ok hv_eq ?_
    have hlen_usize : Aeneas.Std.Slice.len v = libcrux_iot_sha3.SHA3_256_DIGEST_SIZE := by
      apply Aeneas.Std.UScalar.eq_of_val_eq
      rw [Aeneas.Std.Slice.len_val]
      show v.val.length = _
      rw [hv_len]
      simp [libcrux_iot_sha3.SHA3_256_DIGEST_SIZE]
    have hpost : libcrux_iot_sha3.sha256_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha256_ema.post,
        CoreModels.core.slice.Slice.len,
        CoreModels.rust_primitives.slice.slice_length, Aeneas.Std.bind_tc_ok]
      rw [if_pos hlen_usize, decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha384_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha384_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha384_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok, Aeneas.Std.lift] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload
      ≤ Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize CoreModels.core.num.U32.MAX
  · rw [if_pos hcond] at hpre
    have hd : digest.len = libcrux_iot_sha3.SHA3_384_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 48 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_384_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha384_ema_spec digest payload (payload_len_le hcond) hlen)
    refine triple_of_ok hv_eq ?_
    have hlen_usize : Aeneas.Std.Slice.len v = libcrux_iot_sha3.SHA3_384_DIGEST_SIZE := by
      apply Aeneas.Std.UScalar.eq_of_val_eq
      rw [Aeneas.Std.Slice.len_val]
      show v.val.length = _
      rw [hv_len]
      simp [libcrux_iot_sha3.SHA3_384_DIGEST_SIZE]
    have hpost : libcrux_iot_sha3.sha384_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha384_ema.post,
        CoreModels.core.slice.Slice.len,
        CoreModels.rust_primitives.slice.slice_length, Aeneas.Std.bind_tc_ok]
      rw [if_pos hlen_usize, decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

theorem sha512_ema_spec_proof (digest payload : Slice Std.U8) :
    libcrux_iot_sha3.sha512_ema.spec digest payload := by
  intro hpre
  simp only [libcrux_iot_sha3.sha512_ema.pre,
    CoreModels.core.slice.Slice.len, CoreModels.rust_primitives.slice.slice_length,
    Aeneas.Std.bind_tc_ok, Aeneas.Std.lift] at hpre
  by_cases hcond : Aeneas.Std.Slice.len payload
      ≤ Aeneas.Std.UScalar.cast Aeneas.Std.UScalarTy.Usize CoreModels.core.num.U32.MAX
  · rw [if_pos hcond] at hpre
    have hd : digest.len = libcrux_iot_sha3.SHA3_512_DIGEST_SIZE :=
      of_decide_eq_true (bool_of_holds_map_ok hpre)
    have hlen : digest.val.length = 64 := by
      have hv := congrArg Aeneas.Std.UScalar.val hd
      rw [Aeneas.Std.Slice.len_val] at hv
      simpa [libcrux_iot_sha3.SHA3_512_DIGEST_SIZE] using hv
    -- all four conjuncts of the theorem's post are used below
    obtain ⟨v, hv_eq, spec_out, hspec_eq, hv_len, hv_bytes⟩ :=
      triple_exists_ok
        (Sponge.sha512_ema_spec digest payload (payload_len_le hcond) hlen)
    refine triple_of_ok hv_eq ?_
    have hlen_usize : Aeneas.Std.Slice.len v = libcrux_iot_sha3.SHA3_512_DIGEST_SIZE := by
      apply Aeneas.Std.UScalar.eq_of_val_eq
      rw [Aeneas.Std.Slice.len_val]
      show v.val.length = _
      rw [hv_len]
      simp [libcrux_iot_sha3.SHA3_512_DIGEST_SIZE]
    have hpost : libcrux_iot_sha3.sha512_ema.post digest payload v = .ok true := by
      simp only [libcrux_iot_sha3.sha512_ema.post,
        CoreModels.core.slice.Slice.len,
        CoreModels.rust_primitives.slice.slice_length, Aeneas.Std.bind_tc_ok]
      rw [if_pos hlen_usize, decl_ref_eq v, Aeneas.Std.bind_tc_ok,
        decl_ref_eq payload, Aeneas.Std.bind_tc_ok, hspec_eq, Aeneas.Std.bind_tc_ok,
        range_full_index_eq spec_out, Aeneas.Std.bind_tc_ok]
      exact slice_eq_true (val_eq_of_bytes hv_len (by simp) hv_bytes)
    rw [hpost]
    exact holds_map_ok_of_bool rfl
  · rw [if_neg hcond] at hpre
    exact absurd (bool_of_holds_map_ok hpre) (by simp)

end libcrux_iot_sha3.Verification
