-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_dsa]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import LibcruxIotMlDsa.Extraction.Types
import LibcruxIotMlDsa.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_dsa


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::get_n_least_significant_bits::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 28:0-28:28 -/
@[reducible]
def simd.portable.arithmetic.get_n_least_significant_bits.pre
  (n : Std.U8) (value : Std.U64) : RustM Bool := do
  ok (n < 64#u8)

def simd.portable.arithmetic.get_n_least_significant_bits.spec (n : Std.U8)
  (value : Std.U64) : Prop :=
  (simd.portable.arithmetic.get_n_least_significant_bits.pre n value).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.get_n_least_significant_bits n value
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::power2round_element::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 84:0-84:62 -/
@[reducible]
def simd.portable.arithmetic.power2round_element.pre
  (t : Std.I32) : RustM Bool := do
  let i ← -. simd.traits.FIELD_MODULUS
  if t >= i
  then ok (t < simd.traits.FIELD_MODULUS)
  else ok false

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::power2round_element::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 90:0-94:56 -/
@[reducible]
def simd.portable.arithmetic.power2round_element.post
  (t : Std.I32) (out : (Std.I32 × Std.I32)) : RustM Bool := do
  let (i, i1) := out
  let i2 ← lift (IScalar.cast .I64 t)
  let i3 ← hacspec_ml_dsa.arithmetic.mod_q i2
  let (_, i4) ← hacspec_ml_dsa.arithmetic.power2round i3
  if i = i4
  then
    let i5 ← lift (IScalar.cast .I64 t)
    let i6 ← hacspec_ml_dsa.arithmetic.mod_q i5
    let (i7, _) ← hacspec_ml_dsa.arithmetic.power2round i6
    ok (i1 = i7)
  else ok false

def simd.portable.arithmetic.power2round_element.spec (t : Std.I32) : Prop :=
  (simd.portable.arithmetic.power2round_element.pre t).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.power2round_element t
  ⦃ ⇓ res =>
  ⌜ (simd.portable.arithmetic.power2round_element.post t res).holds ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::power2round::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 143:0-143:47 -/
@[reducible]
def simd.portable.arithmetic.power2round.pre
  (t0 : simd.portable.vector_type.Coefficients)
  (t1 : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  simd.portable.arithmetic.coefficients_in_field t0

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::power2round::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 146:0-146:72 -/
@[reducible]
def simd.portable.arithmetic.power2round.post
  (t0 : simd.portable.vector_type.Coefficients)
  (t1 : simd.portable.vector_type.Coefficients)
  (p : (simd.portable.vector_type.Coefficients ×
  simd.portable.vector_type.Coefficients)) :
  RustM Bool
  := do
  let (t0_future, t1_future) := p
  simd.portable.arithmetic.power2round_unit_ok t0 t0_future t1_future

def simd.portable.arithmetic.power2round.spec
  (t0 : simd.portable.vector_type.Coefficients)
  (t1 : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.power2round.pre t0 t1).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.power2round t0 t1
  ⦃ ⇓ res =>
  ⌜ (simd.portable.arithmetic.power2round.post t0 t1 res).holds ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::shift_left_then_reduce::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 198:0-198:52 -/
@[reducible]
def simd.portable.arithmetic.shift_left_then_reduce.pre
  (SHIFT_BY : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if SHIFT_BY >= 0#i32
  then ok (SHIFT_BY < 32#i32)
  else ok false

def simd.portable.arithmetic.shift_left_then_reduce.spec (SHIFT_BY : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.shift_left_then_reduce.pre SHIFT_BY
  simd_unit).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.shift_left_then_reduce SHIFT_BY simd_unit
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_one_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 206:0-206:75 -/
@[reducible]
def simd.portable.arithmetic.compute_one_hint.pre
  (low : Std.I32) (high : Std.I32) (gamma2 : Std.I32) : RustM Bool := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_one_hint::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 207:0-207:47 -/
@[reducible]
def simd.portable.arithmetic.compute_one_hint.post
  (low : Std.I32) (high : Std.I32) (gamma2 : Std.I32) (out : Std.I32) :
  RustM Bool
  := do
  if out >= 0#i32
  then ok (out <= 1#i32)
  else ok false

def simd.portable.arithmetic.compute_one_hint.spec (low : Std.I32)
  (high : Std.I32) (gamma2 : Std.I32) : Prop :=
  (simd.portable.arithmetic.compute_one_hint.pre low high gamma2).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.compute_one_hint low high gamma2
  ⦃ ⇓ res =>
  ⌜
  (simd.portable.arithmetic.compute_one_hint.post low high gamma2 res).holds
  ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 217:0-217:75 -/
@[reducible]
def simd.portable.arithmetic.compute_hint.pre
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) (gamma2 : Std.I32)
  (hint : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

def simd.portable.arithmetic.compute_hint.spec
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) (gamma2 : Std.I32)
  (hint : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.compute_hint.pre low high gamma2 hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.compute_hint low high gamma2 hint
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose_element::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 263:0-265:26 -/
@[reducible]
def simd.portable.arithmetic.decompose_element.pre
  (gamma2 : Std.I32) (r : Std.I32) : RustM Bool := do
  if gamma2 = constants.GAMMA2_V95_232
  then
    let i ← -. simd.traits.FIELD_MODULUS
    if r >= i
    then ok (r < simd.traits.FIELD_MODULUS)
    else ok false
  else
    if gamma2 = constants.GAMMA2_V261_888
    then
      let i ← -. simd.traits.FIELD_MODULUS
      if r >= i
      then ok (r < simd.traits.FIELD_MODULUS)
      else ok false
    else ok false

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose_element::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 278:0-282:64 -/
@[reducible]
def simd.portable.arithmetic.decompose_element.post
  (gamma2 : Std.I32) (r : Std.I32) (out : (Std.I32 × Std.I32)) :
  RustM Bool
  := do
  let (i, i1) := out
  let i2 ← lift (IScalar.cast .I64 r)
  let i3 ← hacspec_ml_dsa.arithmetic.mod_q i2
  let (_, i4) ← hacspec_ml_dsa.arithmetic.decompose i3 gamma2
  if i = i4
  then
    let i5 ← lift (IScalar.cast .I64 r)
    let i6 ← hacspec_ml_dsa.arithmetic.mod_q i5
    let (i7, _) ← hacspec_ml_dsa.arithmetic.decompose i6 gamma2
    ok (i1 = i7)
  else ok false

def simd.portable.arithmetic.decompose_element.spec (gamma2 : Std.I32)
  (r : Std.I32) : Prop :=
  (simd.portable.arithmetic.decompose_element.pre gamma2 r).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.decompose_element gamma2 r
  ⦃ ⇓ res =>
  ⌜ (simd.portable.arithmetic.decompose_element.post gamma2 r res).holds ⌝
  ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_one_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 328:0-330:33 -/
@[reducible]
def simd.portable.arithmetic.use_one_hint.pre
  (gamma2 : Std.I32) (r : Std.I32) (hint : Std.I32) : RustM Bool := do
  if gamma2 = constants.GAMMA2_V95_232
  then
    let i ← -. simd.traits.FIELD_MODULUS
    if r >= i
    then
      if r < simd.traits.FIELD_MODULUS
      then if hint = 0#i32
           then ok true
           else ok (hint = 1#i32)
      else ok false
    else ok false
  else
    if gamma2 = constants.GAMMA2_V261_888
    then
      let i ← -. simd.traits.FIELD_MODULUS
      if r >= i
      then
        if r < simd.traits.FIELD_MODULUS
        then if hint = 0#i32
             then ok true
             else ok (hint = 1#i32)
        else ok false
      else ok false
    else ok false

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_one_hint::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 335:0-336:69 -/
@[reducible]
def simd.portable.arithmetic.use_one_hint.post
  (gamma2 : Std.I32) (r : Std.I32) (hint : Std.I32) (out : Std.I32) :
  RustM Bool
  := do
  let i ← lift (IScalar.cast .I64 r)
  let i1 ← hacspec_ml_dsa.arithmetic.mod_q i
  let i2 ← hacspec_ml_dsa.arithmetic.use_hint (hint = 1#i32) i1 gamma2
  ok (out = i2)

def simd.portable.arithmetic.use_one_hint.spec (gamma2 : Std.I32) (r : Std.I32)
  (hint : Std.I32) : Prop :=
  (simd.portable.arithmetic.use_one_hint.pre gamma2 r hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.use_one_hint gamma2 r hint
  ⦃ ⇓ res =>
  ⌜ (simd.portable.arithmetic.use_one_hint.post gamma2 r hint res).holds ⌝
  ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 468:0-469:41 -/
@[reducible]
def simd.portable.arithmetic.decompose.pre
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if gamma2 = constants.GAMMA2_V95_232
  then simd.portable.arithmetic.coefficients_in_field simd_unit
  else
    if gamma2 = constants.GAMMA2_V261_888
    then simd.portable.arithmetic.coefficients_in_field simd_unit
    else ok false

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 472:0-472:88 -/
@[reducible]
def simd.portable.arithmetic.decompose.post
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients)
  (p : (simd.portable.vector_type.Coefficients ×
  simd.portable.vector_type.Coefficients)) :
  RustM Bool
  := do
  let (low_future, high_future) := p
  simd.portable.arithmetic.decompose_unit_ok gamma2 simd_unit low_future
    high_future

def simd.portable.arithmetic.decompose.spec (gamma2 : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients)
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.decompose.pre gamma2 simd_unit low high).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.decompose gamma2 simd_unit low high
  ⦃ ⇓ res =>
  ⌜
  (simd.portable.arithmetic.decompose.post gamma2 simd_unit low high res).holds
  ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 522:0-524:37 -/
@[reducible]
def simd.portable.arithmetic.use_hint.pre
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (hint : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if gamma2 = constants.GAMMA2_V95_232
  then
    let b ← simd.portable.arithmetic.coefficients_in_field simd_unit
    if b
    then simd.portable.arithmetic.coefficients_are_hints hint
    else ok false
  else
    if gamma2 = constants.GAMMA2_V261_888
    then
      let b ← simd.portable.arithmetic.coefficients_in_field simd_unit
      if b
      then simd.portable.arithmetic.coefficients_are_hints hint
      else ok false
    else ok false

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_hint::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 527:0-527:80 -/
@[reducible]
def simd.portable.arithmetic.use_hint.post
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (hint : simd.portable.vector_type.Coefficients)
  (hint_future : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  simd.portable.arithmetic.use_hint_unit_ok gamma2 simd_unit hint hint_future

def simd.portable.arithmetic.use_hint.spec (gamma2 : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients)
  (hint : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.use_hint.pre gamma2 simd_unit hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.use_hint gamma2 simd_unit hint
  ⦃ ⇓ res =>
  ⌜ (simd.portable.arithmetic.use_hint.post gamma2 simd_unit hint res).holds
  ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::vector_type::lane::pre]:
    Source: 'ml-dsa/src/simd/portable/vector_type.rs', lines 24:0-24:51 -/
@[reducible]
def simd.portable.vector_type.lane.pre
  (value : simd.portable.vector_type.Coefficients) (i : Std.Usize) :
  RustM Bool
  := do
  ok (i < simd.traits.COEFFICIENTS_IN_SIMD_UNIT)

def simd.portable.vector_type.lane.spec
  (value : simd.portable.vector_type.Coefficients) (i : Std.Usize) : Prop :=
  (simd.portable.vector_type.lane.pre value i).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.vector_type.lane value i
  ⦃ ⇓ res => ⌜ True ⌝ ⦄

end libcrux_iot_ml_dsa
