-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_dsa]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import LibcruxIotMlDsa.Extraction.Types
import LibcruxIotMlDsa.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_dsa


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::get_n_least_significant_bits::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 28:0-28:28 -/
@[reducible]
def simd.portable.arithmetic.get_n_least_significant_bits.pre
  (n : Std.U8) (value : Std.U64) : RustM Bool := do
  ok (n < 64#u8)

def simd.portable.arithmetic.get_n_least_significant_bits.spec (n : Std.U8)
  (value : Std.U64) : Prop :=
  (simd.portable.arithmetic.get_n_least_significant_bits.pre n value).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.get_n_least_significant_bits n value
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::shift_left_then_reduce::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 157:0-157:52 -/
@[reducible]
def simd.portable.arithmetic.shift_left_then_reduce.pre
  (SHIFT_BY : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if SHIFT_BY >= 0#i32
  then ok (SHIFT_BY < 32#i32)
  else ok false

def simd.portable.arithmetic.shift_left_then_reduce.spec (SHIFT_BY : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.shift_left_then_reduce.pre SHIFT_BY
  simd_unit).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.shift_left_then_reduce SHIFT_BY simd_unit
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_one_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 165:0-165:40 -/
@[reducible]
def simd.portable.arithmetic.compute_one_hint.pre
  (low : Std.I32) (high : Std.I32) (gamma2 : Std.I32) : RustM Bool := do
  ok (gamma2 != core.num.I32.MIN)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_one_hint::post]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 166:0-166:47 -/
@[reducible]
def simd.portable.arithmetic.compute_one_hint.post
  (low : Std.I32) (high : Std.I32) (gamma2 : Std.I32) (out : Std.I32) :
  RustM Bool
  := do
  if out >= 0#i32
  then ok (out <= 1#i32)
  else ok false

def simd.portable.arithmetic.compute_one_hint.spec (low : Std.I32)
  (high : Std.I32) (gamma2 : Std.I32) : Prop :=
  (simd.portable.arithmetic.compute_one_hint.pre low high gamma2).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.compute_one_hint low high gamma2
  ⦃ ⇓ res =>
  ⌜
  (simd.portable.arithmetic.compute_one_hint.post low high gamma2 res).holds
  ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::compute_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 176:0-176:40 -/
@[reducible]
def simd.portable.arithmetic.compute_hint.pre
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) (gamma2 : Std.I32)
  (hint : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  ok (gamma2 != core.num.I32.MIN)

def simd.portable.arithmetic.compute_hint.spec
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) (gamma2 : Std.I32)
  (hint : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.compute_hint.pre low high gamma2 hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.compute_hint low high gamma2 hint
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose_element::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 218:0-218:75 -/
@[reducible]
def simd.portable.arithmetic.decompose_element.pre
  (gamma2 : Std.I32) (r : Std.I32) : RustM Bool := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

def simd.portable.arithmetic.decompose_element.spec (gamma2 : Std.I32)
  (r : Std.I32) : Prop :=
  (simd.portable.arithmetic.decompose_element.pre gamma2 r).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.decompose_element gamma2 r
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_one_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 269:0-269:75 -/
@[reducible]
def simd.portable.arithmetic.use_one_hint.pre
  (gamma2 : Std.I32) (r : Std.I32) (hint : Std.I32) : RustM Bool := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

def simd.portable.arithmetic.use_one_hint.spec (gamma2 : Std.I32) (r : Std.I32)
  (hint : Std.I32) : Prop :=
  (simd.portable.arithmetic.use_one_hint.pre gamma2 r hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.use_one_hint gamma2 r hint
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::decompose::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 307:0-307:75 -/
@[reducible]
def simd.portable.arithmetic.decompose.pre
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

def simd.portable.arithmetic.decompose.spec (gamma2 : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients)
  (low : simd.portable.vector_type.Coefficients)
  (high : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.decompose.pre gamma2 simd_unit low high).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.decompose gamma2 simd_unit low high
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::use_hint::pre]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 320:0-320:75 -/
@[reducible]
def simd.portable.arithmetic.use_hint.pre
  (gamma2 : Std.I32) (simd_unit : simd.portable.vector_type.Coefficients)
  (hint : simd.portable.vector_type.Coefficients) :
  RustM Bool
  := do
  if gamma2 = constants.GAMMA2_V95_232
  then ok true
  else ok (gamma2 = constants.GAMMA2_V261_888)

def simd.portable.arithmetic.use_hint.spec (gamma2 : Std.I32)
  (simd_unit : simd.portable.vector_type.Coefficients)
  (hint : simd.portable.vector_type.Coefficients) : Prop :=
  (simd.portable.arithmetic.use_hint.pre gamma2 simd_unit hint).holds →
  ⦃ ⌜ True ⌝ ⦄
  simd.portable.arithmetic.use_hint gamma2 simd_unit hint
  ⦃ ⇓ res => ⌜ True ⌝ ⦄

end libcrux_iot_ml_dsa
