-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: external functions.
-- This is a template file: hax seeded LibcruxIotMlKem/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open libcrux_iot_ml_kem

/-- [libcrux_iot_ml_kem::matrix::sample_matrix_entry]:
    Source: 'ml-kem/src/matrix.rs', lines 207:0-224:1 -/
axiom matrix.sample_matrix_entry
  {Vector : Type} {Hasher : Type} (vectortraitsOperationsInst :
  vector.traits.Operations Vector) (hash_functionsHashInst :
  hash_functions.Hash Hasher) :
  polynomial.PolynomialRingElement Vector → Slice Std.U8 → Std.Usize →
    Std.Usize → RustM (polynomial.PolynomialRingElement Vector)

/-- [libcrux_iot_ml_kem::matrix::sample_matrix_A]:
    Source: 'ml-kem/src/matrix.rs', lines 230:0-264:1 -/
axiom matrix.sample_matrix_A
  {Vector : Type} {Hasher : Type} (K : Std.Usize) (vectortraitsOperationsInst :
  vector.traits.Operations Vector) (hash_functionsHashInst :
  hash_functions.Hash Hasher) :
  Slice (polynomial.PolynomialRingElement Vector) → Array Std.U8 34#usize →
    Bool → RustM (Slice (polynomial.PolynomialRingElement Vector))

