-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open libcrux_iot_ml_kem

/-- [libcrux_iot_ml_kem::matrix::sample_matrix_entry]:
    Source: 'ml-kem/src/matrix.rs', lines 26:0-43:1 -/
axiom matrix.sample_matrix_entry
  {Vector : Type} {Hasher : Type} (vectortraitsOperationsInst :
  vector.traits.Operations Vector) (hash_functionsHashInst :
  hash_functions.Hash Hasher) :
  polynomial.PolynomialRingElement Vector → Slice Std.U8 → Std.Usize →
    Std.Usize → Result (polynomial.PolynomialRingElement Vector)

