-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: proof obligations
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.Types
import LibcruxIotMlKem.Extraction.Funs
import LibcruxIotMlKem.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_kem

@[spec]
theorem
  ntt.ntt_at_layer_1.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_1.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_2.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_2.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_3.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_3.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_layer_int_vec_step.spec.proof {Vector : Type}
                                       (vectortraitsOperationsInst :
                                       vector.traits.Operations Vector)
  (coefficients : Array Vector 16#usize) (a : Std.Usize) (b : Std.Usize)
  (scratch : Vector) (zeta_r : Std.I16) :
  ntt.ntt_layer_int_vec_step.spec vectortraitsOperationsInst coefficients a b
  scratch zeta_r
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_4_plus.spec.proof {Vector : Type}
                                    (vectortraitsOperationsInst :
                                    vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (layer : Std.Usize) (scratch : Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_4_plus.spec vectortraitsOperationsInst zeta_i re layer
  scratch _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_1.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_1.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_2.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_2.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_3.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_3.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.inv_ntt_layer_int_vec_step_reduce.spec.proof {Vector : Type}
                                                         (vectortraitsOperationsInst
                                                         :
                                                         vector.traits.Operations
                                                         Vector)
  (coefficients : Array Vector 16#usize) (a : Std.Usize) (b : Std.Usize)
  (scratch : Vector) (zeta_r : Std.I16) :
  invert_ntt.inv_ntt_layer_int_vec_step_reduce.spec vectortraitsOperationsInst
  coefficients a b scratch zeta_r
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_4_plus.spec.proof {Vector : Type}
                                                  (vectortraitsOperationsInst :
                                                  vector.traits.Operations
                                                  Vector) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (layer : Std.Usize)
  (scratch : Vector) :
  invert_ntt.invert_ntt_at_layer_4_plus.spec vectortraitsOperationsInst zeta_i
  re layer scratch
  := by sorry

@[spec]
theorem vector.portable.arithmetic.get_n_least_significant_bits.spec.proof
   (n : Std.U8) (value : Std.U32) :
  vector.portable.arithmetic.get_n_least_significant_bits.spec n value
  := by sorry

@[spec]
theorem vector.portable.arithmetic.reducing_from_i32_array.spec.proof
   (array : Slice Std.I32) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.arithmetic.reducing_from_i32_array.spec array out
  := by sorry

@[spec]
theorem vector.portable.arithmetic.shift_right.spec.proof (SHIFT_BY : Std.I32)
  (vec : vector.portable.vector_type.PortableVector) :
  vector.portable.arithmetic.shift_right.spec SHIFT_BY vec
  := by sorry

@[spec]
theorem vector.portable.compress.compress_ciphertext_coefficient.spec.proof
   (coefficient_bits : Std.U8) (fe : Std.U16) :
  vector.portable.compress.compress_ciphertext_coefficient.spec
  coefficient_bits fe
  := by sorry

@[spec]
theorem
  vector.portable.compress.compress.spec.proof (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.compress.compress.spec COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.compress.decompress_ciphertext_coefficient.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.compress.decompress_ciphertext_coefficient.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem vector.portable.ntt.ntt_step.spec.proof
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  vector.portable.ntt.ntt_step.spec vec zeta i j
  := by sorry

@[spec]
theorem vector.portable.ntt.inv_ntt_step.spec.proof
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  vector.portable.ntt.inv_ntt_step.spec vec zeta i j
  := by sorry

@[spec]
theorem
  vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache.spec a b
  zeta i out cache
  := by sorry

@[spec]
theorem
  vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (i : Std.Usize)
  (out : Slice Std.I32) (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache.spec a b i
  out cache
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_binomials.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials.spec a b zeta i out
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply.spec.proof
  (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (zeta0 : Std.I16) (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.ntt.accumulating_ntt_multiply.spec lhs rhs out zeta0 zeta1
  zeta2 zeta3
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_fill_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.ntt.accumulating_ntt_multiply_fill_cache.spec lhs rhs out
  cache zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_use_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_use_cache.spec lhs rhs out
  cache
  := by sorry

@[spec]
theorem vector.portable.sampling.rej_sample.spec.proof (a : Slice Std.U8)
  (out : Slice Std.I16) : vector.portable.sampling.rej_sample.spec a out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_1.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_1.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_1.spec.proof (v : Slice Std.U8)
  (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_1.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_4_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_4_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_4.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_4.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_4_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_4_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_4.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_4.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_5_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_5_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_5.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_5.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_5_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_5_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_5.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_5.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_10_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_10_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_10.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_10.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_10_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_10_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_10.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_10.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_11_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_11_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_11.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_11.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_11_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_11_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_11.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_11.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_12_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_12_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_12.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_12.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_12_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_12_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_12.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_12.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.vector_type.from_i16_array.spec.proof
  (array : Slice Std.I16) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.from_i16_array.spec array out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.from_i16_array.spec.proof
   (array : Slice Std.I16) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.from_i16_array.spec
  array out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.reducing_from_i32_array.spec.proof
   (array : Slice Std.I32) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.reducing_from_i32_array.spec
  array out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.shift_right.spec.proof
   (SHIFT_BY : Std.I32) (vec : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.shift_right.spec
  SHIFT_BY vec
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.compress.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.compress.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.decompress_ciphertext_coefficient.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.decompress_ciphertext_coefficient.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (zeta0 : Std.I16) (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply.spec
  lhs rhs out zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_fill_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_fill_cache.spec
  lhs rhs out cache zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_use_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_use_cache.spec
  lhs rhs out cache
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_1.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_1.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_1.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_1.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_4.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_4.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_4.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_4.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_5.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_5.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_5.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_5.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_10.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_10.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_10.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_10.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_11.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_11.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_11.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_11.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_12.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_12.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_12.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_12.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.rej_sample.spec.proof
   (a : Slice Std.U8) (out : Slice Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.rej_sample.spec
  a out
  := by sorry

end libcrux_iot_ml_kem
