-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: proof obligations
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.Types
import LibcruxIotMlKem.Extraction.Funs
import LibcruxIotMlKem.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_kem

@[spec]
theorem polynomial.zeta.spec.proof (i : Std.Usize) : polynomial.zeta.spec i
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_1.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_1.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_2.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_2.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_3.spec.proof {Vector : Type} (vectortraitsOperationsInst :
                               vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_3.spec vectortraitsOperationsInst zeta_i re
  _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  ntt.ntt_layer_int_vec_step.spec.proof {Vector : Type}
                                       (vectortraitsOperationsInst :
                                       vector.traits.Operations Vector)
  (coefficients : Array Vector 16#usize) (a : Std.Usize) (b : Std.Usize)
  (scratch : Vector) (zeta_r : Std.I16) :
  ntt.ntt_layer_int_vec_step.spec vectortraitsOperationsInst coefficients a b
  scratch zeta_r
  := by sorry

@[spec]
theorem
  ntt.ntt_at_layer_4_plus.spec.proof {Vector : Type}
                                    (vectortraitsOperationsInst :
                                    vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (layer : Std.Usize) (scratch : Vector)
  (_initial_coefficient_bound : Std.Usize) :
  ntt.ntt_at_layer_4_plus.spec vectortraitsOperationsInst zeta_i re layer
  scratch _initial_coefficient_bound
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_1.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_1.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_2.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_2.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_3.spec.proof {Vector : Type}
                                             (vectortraitsOperationsInst :
                                             vector.traits.Operations Vector)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector) :
  invert_ntt.invert_ntt_at_layer_3.spec vectortraitsOperationsInst zeta_i re
  := by sorry

@[spec]
theorem
  invert_ntt.inv_ntt_layer_int_vec_step_reduce.spec.proof {Vector : Type}
                                                         (vectortraitsOperationsInst
                                                         :
                                                         vector.traits.Operations
                                                         Vector)
  (coefficients : Array Vector 16#usize) (a : Std.Usize) (b : Std.Usize)
  (scratch : Vector) (zeta_r : Std.I16) :
  invert_ntt.inv_ntt_layer_int_vec_step_reduce.spec vectortraitsOperationsInst
  coefficients a b scratch zeta_r
  := by sorry

@[spec]
theorem
  invert_ntt.invert_ntt_at_layer_4_plus.spec.proof {Vector : Type}
                                                  (vectortraitsOperationsInst :
                                                  vector.traits.Operations
                                                  Vector) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (layer : Std.Usize)
  (scratch : Vector) :
  invert_ntt.invert_ntt_at_layer_4_plus.spec vectortraitsOperationsInst zeta_i
  re layer scratch
  := by sorry

@[spec]
theorem
  matrix.entry.spec.proof {Vector : Type} (K : Std.Usize)
                         (vectortraitsOperationsInst : vector.traits.Operations
                         Vector)
  (matrix1 : Slice (polynomial.PolynomialRingElement Vector)) (i : Std.Usize)
  (j : Std.Usize) : matrix.entry.spec K vectortraitsOperationsInst matrix1 i j
  := by sorry

@[spec]
theorem
  matrix.sample_matrix_entry.spec.proof {Vector : Type} {Hasher : Type}
                                       (vectortraitsOperationsInst :
                                       vector.traits.Operations Vector)
                                       (hash_functionsHashInst :
                                       hash_functions.Hash Hasher) :
  matrix.sample_matrix_entry.spec vectortraitsOperationsInst
  hash_functionsHashInst
  := by sorry

@[spec]
theorem
  matrix.sample_matrix_A.spec.proof {Vector : Type} {Hasher : Type} (K :
                                   Std.Usize) (vectortraitsOperationsInst :
                                   vector.traits.Operations Vector)
                                   (hash_functionsHashInst :
                                   hash_functions.Hash Hasher) :
  matrix.sample_matrix_A.spec K vectortraitsOperationsInst
  hash_functionsHashInst
  := by sorry

@[spec]
theorem
  matrix.compute_message.spec.proof {Vector : Type} {K : Std.Usize}
                                   (vectortraitsOperationsInst :
                                   vector.traits.Operations Vector)
  (v : polynomial.PolynomialRingElement Vector)
  (secret_as_ntt : Array (polynomial.PolynomialRingElement Vector) K)
  (u_as_ntt : Array (polynomial.PolynomialRingElement Vector) K)
  (result : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (accumulator : Array Std.I32 256#usize) :
  matrix.compute_message.spec vectortraitsOperationsInst v secret_as_ntt
  u_as_ntt result scratch accumulator
  := by sorry

@[spec]
theorem
  matrix.compute_ring_element_v.spec.proof {Vector : Type} (K : Std.Usize)
                                          (vectortraitsOperationsInst :
                                          vector.traits.Operations Vector)
  (public_key : Slice Std.U8)
  (t_as_ntt_entry : polynomial.PolynomialRingElement Vector)
  (r_as_ntt : Slice (polynomial.PolynomialRingElement Vector))
  (error_2 : polynomial.PolynomialRingElement Vector)
  (message : polynomial.PolynomialRingElement Vector)
  (result : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (cache : Slice (polynomial.PolynomialRingElement Vector))
  (accumulator : Array Std.I32 256#usize) :
  matrix.compute_ring_element_v.spec K vectortraitsOperationsInst public_key
  t_as_ntt_entry r_as_ntt error_2 message result scratch cache accumulator
  := by sorry

@[spec]
theorem
  matrix.compute_vector_u.spec.proof {Vector : Type} {Hasher : Type} (K :
                                    Std.Usize) (vectortraitsOperationsInst :
                                    vector.traits.Operations Vector)
                                    (hash_functionsHashInst :
                                    hash_functions.Hash Hasher)
  (matrix_entry : polynomial.PolynomialRingElement Vector)
  (seed : Slice Std.U8)
  (r_as_ntt : Slice (polynomial.PolynomialRingElement Vector))
  (error_1 : Slice (polynomial.PolynomialRingElement Vector))
  (result : Slice (polynomial.PolynomialRingElement Vector)) (scratch : Vector)
  (cache : Slice (polynomial.PolynomialRingElement Vector))
  (accumulator : Array Std.I32 256#usize) :
  matrix.compute_vector_u.spec K vectortraitsOperationsInst
  hash_functionsHashInst matrix_entry seed r_as_ntt error_1 result scratch
  cache accumulator
  := by sorry

@[spec]
theorem
  matrix.compute_As_plus_e.spec.proof {Vector : Type} {K : Std.Usize}
                                     (vectortraitsOperationsInst :
                                     vector.traits.Operations Vector)
  (t_as_ntt : Array (polynomial.PolynomialRingElement Vector) K)
  (matrix_A : Slice (polynomial.PolynomialRingElement Vector))
  (s_as_ntt : Array (polynomial.PolynomialRingElement Vector) K)
  (error_as_ntt : Array (polynomial.PolynomialRingElement Vector) K)
  (s_cache : Array (polynomial.PolynomialRingElement Vector) K)
  (accumulator : Array Std.I32 256#usize) :
  matrix.compute_As_plus_e.spec vectortraitsOperationsInst t_as_ntt matrix_A
  s_as_ntt error_as_ntt s_cache accumulator
  := by sorry

@[spec]
theorem
  matrix.compute_u_and_v.spec.proof {Vector : Type} {Hasher : Type} (K :
                                   Std.Usize) (vectortraitsOperationsInst :
                                   vector.traits.Operations Vector)
                                   (hash_functionsHashInst :
                                   hash_functions.Hash Hasher)
  (seed : Slice Std.U8) (public_key : Slice Std.U8)
  (r_as_ntt : Slice (polynomial.PolynomialRingElement Vector))
  (error_1 : Slice (polynomial.PolynomialRingElement Vector))
  (error_2 : polynomial.PolynomialRingElement Vector)
  (message : polynomial.PolynomialRingElement Vector)
  (matrix_entry : polynomial.PolynomialRingElement Vector)
  (t_as_ntt_entry : polynomial.PolynomialRingElement Vector)
  (result_u : Slice (polynomial.PolynomialRingElement Vector))
  (result_v : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (cache : Slice (polynomial.PolynomialRingElement Vector))
  (accumulator : Array Std.I32 256#usize) :
  matrix.compute_u_and_v.spec K vectortraitsOperationsInst
  hash_functionsHashInst seed public_key r_as_ntt error_1 error_2 message
  matrix_entry t_as_ntt_entry result_u result_v scratch cache accumulator
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_message.spec.proof {Vector : Type}
                                                      (vectortraitsOperationsInst
                                                      :
                                                      vector.traits.Operations
                                                      Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_message.spec vectortraitsOperationsInst re
  serialized scratch
  := by sorry

@[spec]
theorem
  serialize.serialize_uncompressed_ring_element.spec.proof {Vector : Type}
                                                          (vectortraitsOperationsInst
                                                          :
                                                          vector.traits.Operations
                                                          Vector)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (serialized : Slice Std.U8) :
  serialize.serialize_uncompressed_ring_element.spec vectortraitsOperationsInst
  re scratch serialized
  := by sorry

@[spec]
theorem
  serialize.deserialize_to_uncompressed_ring_element.spec.proof {Vector : Type}
                                                               (vectortraitsOperationsInst
                                                               :
                                                               vector.traits.Operations
                                                               Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_to_uncompressed_ring_element.spec
  vectortraitsOperationsInst serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_to_reduced_ring_element.spec.proof {Vector : Type}
                                                          (vectortraitsOperationsInst
                                                          :
                                                          vector.traits.Operations
                                                          Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_to_reduced_ring_element.spec vectortraitsOperationsInst
  serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_ring_elements_reduced.spec.proof {Vector : Type} (K :
                                                        Std.Usize)
                                                        (vectortraitsOperationsInst
                                                        :
                                                        vector.traits.Operations
                                                        Vector)
  (public_key : Slice Std.U8)
  (deserialized_pk : Slice (polynomial.PolynomialRingElement Vector)) :
  serialize.deserialize_ring_elements_reduced.spec K vectortraitsOperationsInst
  public_key deserialized_pk
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_10.spec.proof {Vector : Type} (BLOCK_LEN :
                                                 Std.Usize)
                                                 (vectortraitsOperationsInst :
                                                 vector.traits.Operations
                                                 Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_10.spec BLOCK_LEN
  vectortraitsOperationsInst re serialized scratch
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_11.spec.proof {Vector : Type} (BLOCK_LEN :
                                                 Std.Usize)
                                                 (vectortraitsOperationsInst :
                                                 vector.traits.Operations
                                                 Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_11.spec BLOCK_LEN
  vectortraitsOperationsInst re serialized scratch
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_ring_element_u.spec.proof {Vector : Type}
                                                             (U_COMPRESSION_FACTOR
                                                             : Std.Usize)
                                                             (BLOCK_LEN :
                                                             Std.Usize)
                                                             (vectortraitsOperationsInst
                                                             :
                                                             vector.traits.Operations
                                                             Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_ring_element_u.spec U_COMPRESSION_FACTOR
  BLOCK_LEN vectortraitsOperationsInst re serialized scratch
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_4.spec.proof {Vector : Type}
                                                (vectortraitsOperationsInst :
                                                vector.traits.Operations
                                                Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_4.spec vectortraitsOperationsInst re
  serialized scratch
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_5.spec.proof {Vector : Type}
                                                (vectortraitsOperationsInst :
                                                vector.traits.Operations
                                                Vector)
  (re : polynomial.PolynomialRingElement Vector) (serialized : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_5.spec vectortraitsOperationsInst re
  serialized scratch
  := by sorry

@[spec]
theorem
  serialize.compress_then_serialize_ring_element_v.spec.proof {Vector : Type}
                                                             (K : Std.Usize)
                                                             (V_COMPRESSION_FACTOR
                                                             : Std.Usize)
                                                             (C2_LEN :
                                                             Std.Usize)
                                                             (vectortraitsOperationsInst
                                                             :
                                                             vector.traits.Operations
                                                             Vector)
  (re : polynomial.PolynomialRingElement Vector) (out : Slice Std.U8)
  (scratch : Vector) :
  serialize.compress_then_serialize_ring_element_v.spec K V_COMPRESSION_FACTOR
  C2_LEN vectortraitsOperationsInst re out scratch
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_10.spec.proof {Vector : Type}
                                                     (vectortraitsOperationsInst
                                                     : vector.traits.Operations
                                                     Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_10.spec vectortraitsOperationsInst
  serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_11.spec.proof {Vector : Type}
                                                     (vectortraitsOperationsInst
                                                     : vector.traits.Operations
                                                     Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_11.spec vectortraitsOperationsInst
  serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_ring_element_u.spec.proof {Vector :
                                                                 Type}
                                                                 (U_COMPRESSION_FACTOR
                                                                 : Std.Usize)
                                                                 (vectortraitsOperationsInst
                                                                 :
                                                                 vector.traits.Operations
                                                                 Vector)
  (serialized : Slice Std.U8)
  (output : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_ring_element_u.spec
  U_COMPRESSION_FACTOR vectortraitsOperationsInst serialized output
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_4.spec.proof {Vector : Type}
                                                    (vectortraitsOperationsInst
                                                    : vector.traits.Operations
                                                    Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_4.spec vectortraitsOperationsInst
  serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_5.spec.proof {Vector : Type}
                                                    (vectortraitsOperationsInst
                                                    : vector.traits.Operations
                                                    Vector)
  (serialized : Slice Std.U8) (re : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_5.spec vectortraitsOperationsInst
  serialized re
  := by sorry

@[spec]
theorem
  serialize.deserialize_then_decompress_ring_element_v.spec.proof {Vector :
                                                                 Type} (K :
                                                                 Std.Usize)
                                                                 (V_COMPRESSION_FACTOR
                                                                 : Std.Usize)
                                                                 (vectortraitsOperationsInst
                                                                 :
                                                                 vector.traits.Operations
                                                                 Vector)
  (serialized : Slice Std.U8)
  (output : polynomial.PolynomialRingElement Vector) :
  serialize.deserialize_then_decompress_ring_element_v.spec K
  V_COMPRESSION_FACTOR vectortraitsOperationsInst serialized output
  := by sorry

@[spec]
theorem
  polynomial.PolynomialRingElement.reducing_from_i32_array.spec.proof
   {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (a : Slice Std.I32) (out : polynomial.PolynomialRingElement Vector) :
  polynomial.PolynomialRingElement.reducing_from_i32_array.spec
  vectortraitsOperationsInst a out
  := by sorry

@[spec]
theorem
  polynomial.PolynomialRingElement.accumulating_ntt_multiply.spec.proof
   {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (self : polynomial.PolynomialRingElement Vector)
  (rhs : polynomial.PolynomialRingElement Vector)
  (accumulator : Array Std.I32 256#usize) :
  polynomial.PolynomialRingElement.accumulating_ntt_multiply.spec
  vectortraitsOperationsInst self rhs accumulator
  := by sorry

@[spec]
theorem vector.portable.arithmetic.get_n_least_significant_bits.spec.proof
   (n : Std.U8) (value : Std.U32) :
  vector.portable.arithmetic.get_n_least_significant_bits.spec n value
  := by sorry

@[spec]
theorem vector.portable.arithmetic.reducing_from_i32_array.spec.proof
   (array : Slice Std.I32) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.arithmetic.reducing_from_i32_array.spec array out
  := by sorry

@[spec]
theorem vector.portable.arithmetic.shift_right.spec.proof (SHIFT_BY : Std.I32)
  (vec : vector.portable.vector_type.PortableVector) :
  vector.portable.arithmetic.shift_right.spec SHIFT_BY vec
  := by sorry

@[spec]
theorem vector.portable.compress.compress_ciphertext_coefficient.spec.proof
   (coefficient_bits : Std.U8) (fe : Std.U16) :
  vector.portable.compress.compress_ciphertext_coefficient.spec
  coefficient_bits fe
  := by sorry

@[spec]
theorem
  vector.portable.compress.compress.spec.proof (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.compress.compress.spec COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.compress.decompress_ciphertext_coefficient.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.compress.decompress_ciphertext_coefficient.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem vector.portable.ntt.ntt_step.spec.proof
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  vector.portable.ntt.ntt_step.spec vec zeta i j
  := by sorry

@[spec]
theorem vector.portable.ntt.inv_ntt_step.spec.proof
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  vector.portable.ntt.inv_ntt_step.spec vec zeta i j
  := by sorry

@[spec]
theorem
  vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache.spec a b
  zeta i out cache
  := by sorry

@[spec]
theorem
  vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (i : Std.Usize)
  (out : Slice Std.I32) (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache.spec a b i
  out cache
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_binomials.spec.proof
   (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32) :
  vector.portable.ntt.accumulating_ntt_multiply_binomials.spec a b zeta i out
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply.spec.proof
  (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (zeta0 : Std.I16) (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.ntt.accumulating_ntt_multiply.spec lhs rhs out zeta0 zeta1
  zeta2 zeta3
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_fill_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.ntt.accumulating_ntt_multiply_fill_cache.spec lhs rhs out
  cache zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem vector.portable.ntt.accumulating_ntt_multiply_use_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.ntt.accumulating_ntt_multiply_use_cache.spec lhs rhs out
  cache
  := by sorry

@[spec]
theorem vector.portable.sampling.rej_sample.spec.proof (a : Slice Std.U8)
  (out : Slice Std.I16) : vector.portable.sampling.rej_sample.spec a out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_1.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_1.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_1.spec.proof (v : Slice Std.U8)
  (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_1.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_4_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_4_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_4.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_4.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_4_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_4_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_4.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_4.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_5_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_5_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_5.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_5.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_5_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_5_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_5.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_5.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_10_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_10_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_10.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_10.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_10_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_10_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_10.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_10.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_11_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_11_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_11.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_11.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_11_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_11_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_11.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_11.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_12_int.spec.proof
  (v : Slice Std.I16) : vector.portable.serialize.serialize_12_int.spec v
  := by sorry

@[spec]
theorem vector.portable.serialize.serialize_12.spec.proof
  (v : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.serialize.serialize_12.spec v out
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_12_int.spec.proof
  (bytes : Slice Std.U8) :
  vector.portable.serialize.deserialize_12_int.spec bytes
  := by sorry

@[spec]
theorem vector.portable.serialize.deserialize_12.spec.proof
  (bytes : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.serialize.deserialize_12.spec bytes out
  := by sorry

@[spec]
theorem vector.portable.vector_type.from_i16_array.spec.proof
  (array : Slice Std.I16) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.from_i16_array.spec array out
  := by sorry

@[spec]
theorem vector.portable.vector_type.to_i16_array.spec.proof
  (x : vector.portable.vector_type.PortableVector) (out : Slice Std.I16) :
  vector.portable.vector_type.to_i16_array.spec x out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.from_i16_array.spec.proof
   (array : Slice Std.I16) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.from_i16_array.spec
  array out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.to_i16_array.spec.proof
   (x : vector.portable.vector_type.PortableVector) (out : Slice Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.to_i16_array.spec
  x out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.reducing_from_i32_array.spec.proof
   (array : Slice Std.I32) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.reducing_from_i32_array.spec
  array out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.shift_right.spec.proof
   (SHIFT_BY : Std.I32) (vec : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.shift_right.spec
  SHIFT_BY vec
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.compress.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.compress.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.decompress_ciphertext_coefficient.spec.proof
   (COEFFICIENT_BITS : Std.I32)
  (a : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.decompress_ciphertext_coefficient.spec
  COEFFICIENT_BITS a
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (zeta0 : Std.I16) (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply.spec
  lhs rhs out zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_fill_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_fill_cache.spec
  lhs rhs out cache zeta0 zeta1 zeta2 zeta3
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_use_cache.spec.proof
   (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.accumulating_ntt_multiply_use_cache.spec
  lhs rhs out cache
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_1.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_1.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_1.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_1.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_4.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_4.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_4.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_4.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_5.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_5.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_5.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_5.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_10.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_10.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_10.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_10.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_11.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_11.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_11.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_11.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_12.spec.proof
   (a : vector.portable.vector_type.PortableVector) (out : Slice Std.U8) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.serialize_12.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_12.spec.proof
   (a : Slice Std.U8) (out : vector.portable.vector_type.PortableVector) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.deserialize_12.spec
  a out
  := by sorry

@[spec]
theorem
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.rej_sample.spec.proof
   (a : Slice Std.U8) (out : Slice Std.I16) :
  vector.portable.vector_type.PortableVector.Insts.Libcrux_iot_ml_kemVectorTraitsOperations.rej_sample.spec
  a out
  := by sorry

end libcrux_iot_ml_kem
