-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: type definitions
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libcrux_iot_ml_kem

/-- Trait declaration: [libcrux_iot_ml_kem::hash_functions::Hash]
    Source: 'ml-kem/src/hash_functions.rs', lines 26:0-69:1 -/
structure hash_functions.Hash (Self : Type) where
  G : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8)
  H : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8)
  PRF : forall (LEN : Std.Usize), Slice Std.U8 → Slice Std.U8 → Result
    (Slice Std.U8)
  PRFxN : Slice (Array Std.U8 33#usize) → Slice Std.U8 → Std.Usize →
    Result (Slice Std.U8)
  shake128_init_absorb_final : Slice (Array Std.U8 34#usize) → Result Self
  shake128_squeeze_first_three_blocks : Self → Slice (Array Std.U8 504#usize)
    → Result (Self × (Slice (Array Std.U8 504#usize)))
  shake128_squeeze_next_block : Self → Slice (Array Std.U8 168#usize) →
    Result (Self × (Slice (Array Std.U8 168#usize)))

/-- [libcrux_iot_ml_kem::polynomial::PolynomialRingElement]
    Source: 'ml-kem/src/polynomial.rs', lines 32:0-34:1 -/
structure polynomial.PolynomialRingElement (Vector : Type) where
  coefficients : Array Vector 16#usize

/-- [libcrux_iot_ml_kem::ind_cpa::unpacked::IndCpaPrivateKeyUnpacked]
    Source: 'ml-kem/src/ind_cpa.rs', lines 31:4-33:5 -/
structure ind_cpa.unpacked.IndCpaPrivateKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  secret_as_ntt : Array (polynomial.PolynomialRingElement Vector) K

/-- [libcrux_iot_ml_kem::ind_cpa::unpacked::IndCpaPublicKeyUnpacked]
    Source: 'ml-kem/src/ind_cpa.rs', lines 46:4-54:5 -/
structure ind_cpa.unpacked.IndCpaPublicKeyUnpacked (Vector : Type) (K :
  Std.Usize) (K_SQUARED : Std.Usize) where
  t_as_ntt : Array (polynomial.PolynomialRingElement Vector) K
  seed_for_A : Array Std.U8 32#usize
  A : Array (polynomial.PolynomialRingElement Vector) K_SQUARED

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Repr]
    Source: 'ml-kem/src/vector/traits.rs', lines 22:0-22:17
    Visibility: public -/
structure vector.traits.Repr (Self : Type) where

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Operations]
    Source: 'ml-kem/src/vector/traits.rs', lines 25:0-164:1
    Visibility: public -/
structure vector.traits.Operations (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  corecloneCloneInst : core.clone.Clone Self
  ReprInst : vector.traits.Repr Self
  ZERO : Result Self
  from_i16_array : Slice Std.I16 → Self → Result Self
  reducing_from_i32_array : Slice Std.I32 → Self → Result Self
  add : Self → Self → Result Self
  sub : Self → Self → Result Self
  negate : Self → Result Self
  multiply_by_constant : Self → Std.I16 → Result Self
  bitwise_and_with_constant : Self → Std.I16 → Result Self
  shift_right : forall (SHIFT_BY : Std.I32), Self → Result Self
  cond_subtract_3329 : Self → Result Self
  barrett_reduce : Self → Result Self
  montgomery_multiply_by_constant : Self → Std.I16 → Result Self
  compress_1 : Self → Result Self
  compress : forall (COEFFICIENT_BITS : Std.I32), Self → Result Self
  decompress_ciphertext_coefficient : forall (COEFFICIENT_BITS : Std.I32), Self
    → Result Self
  ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 →
    Result Self
  ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  ntt_layer_3_step : Self → Std.I16 → Result Self
  inv_ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16
    → Result Self
  inv_ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  inv_ntt_layer_3_step : Self → Std.I16 → Result Self
  accumulating_ntt_multiply : Self → Self → Slice Std.I32 → Std.I16 →
    Std.I16 → Std.I16 → Std.I16 → Result (Slice Std.I32)
  accumulating_ntt_multiply_fill_cache : Self → Self → Slice Std.I32 →
    Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 → Result ((Slice
    Std.I32) × Self)
  accumulating_ntt_multiply_use_cache : Self → Self → Slice Std.I32 →
    Self → Result (Slice Std.I32)
  serialize_1 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_1 : Slice Std.U8 → Self → Result Self
  serialize_4 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_4 : Slice Std.U8 → Self → Result Self
  serialize_5 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_5 : Slice Std.U8 → Self → Result Self
  serialize_10 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_10 : Slice Std.U8 → Self → Result Self
  serialize_11 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_11 : Slice Std.U8 → Self → Result Self
  serialize_12 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_12 : Slice Std.U8 → Self → Result Self
  rej_sample : Slice Std.U8 → Slice Std.I16 → Result (Std.Usize × (Slice
    Std.I16))

/-- [libcrux_iot_ml_kem::ind_cpa::decrypt_unpacked::closure]
    Source: 'ml-kem/src/ind_cpa.rs', lines 887:31-887:74 -/
@[reducible]
def ind_cpa.decrypt_unpacked.closure (Vector : Type) (K : Std.Usize)
  (CIPHERTEXT_SIZE : Std.Usize) (VECTOR_U_ENCODED_SIZE : Std.Usize)
  (U_COMPRESSION_FACTOR : Std.Usize) (V_COMPRESSION_FACTOR : Std.Usize) :=
Unit

/-- [libcrux_iot_ml_kem::ind_cpa::decrypt::closure]
    Source: 'ml-kem/src/ind_cpa.rs', lines 941:36-941:79 -/
@[reducible]
def ind_cpa.decrypt.closure (Vector : Type) (K : Std.Usize) (CIPHERTEXT_SIZE :
  Std.Usize) (VECTOR_U_ENCODED_SIZE : Std.Usize) (U_COMPRESSION_FACTOR :
  Std.Usize) (V_COMPRESSION_FACTOR : Std.Usize) :=
Unit

/-- [libcrux_iot_ml_kem::vector::portable::vector_type::PortableVector]
    Source: 'ml-kem/src/vector/portable/vector_type.rs', lines 9:0-11:1
    Visibility: public -/
structure vector.portable.vector_type.PortableVector where
  elements : Array Std.I16 16#usize

end libcrux_iot_ml_kem
