name = "LibcruxIotSha3"
version = "0.1.0"
defaultTargets = ["LibcruxIotSha3"]

[[lean_lib]]
name = "LibcruxIotSha3"
globs = ["LibcruxIotSha3", "LibcruxIotSha3.+"]

[[require]]
name = "Hax"
git = "https://github.com/cryspen/hax-lean"
rev = "v0.2.0"

[[require]]
name = "HacspecSha3"
git = { url = "https://github.com/cryspen/libcrux", subDir = "specs/sha3/proofs/aeneas-lean" }
rev = "a4cfb1ebf26431b2ee81f0dc19383158aaf397b7"
