-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import LibcruxIotSha3.Extraction.Types
import LibcruxIotSha3.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_sha3


/-- [libcrux_iot_sha3::hash::pre]:
    Source: 'sha3/src/lib.rs', lines 151:0-151:89 -/
@[reducible]
def hash.pre
  (LEN : Std.Usize) (algorithm : Algorithm) (payload : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if i <= i1
  then let i2 ← digest_size algorithm
       ok (LEN = i2)
  else ok false

def hash.spec (LEN : Std.Usize) (algorithm : Algorithm)
  (payload : Slice Std.U8) : Prop :=
  (hash.pre LEN algorithm payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  hash LEN algorithm payload
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::sha224::pre]:
    Source: 'sha3/src/lib.rs', lines 173:0-173:56 -/
@[reducible]
def sha224.pre (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def sha224.spec (payload : Slice Std.U8) : Prop :=
  (sha224.pre payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha224 payload
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::sha224_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 186:0-186:96 -/
@[reducible]
def sha224_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if i <= i1
  then let i2 ← core.slice.Slice.len digest
       ok (i2 = SHA3_224_DIGEST_SIZE)
  else ok false

/-- [libcrux_iot_sha3::sha224_ema::post]:
    Source: 'sha3/src/lib.rs', lines 187:0-189:66 -/
@[reducible]
def sha224_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len digest_future
  if i = SHA3_224_DIGEST_SIZE
  then
    let s ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
    let s1 ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
    let a ← hacspec_sha3.sha3.sha3_224 s1
    let s2 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8)) a ()
    core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8
      s s2
  else ok false

def sha224_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha224_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha224_ema digest payload
  ⦃ ⇓ res => ⌜ (sha224_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha256::pre]:
    Source: 'sha3/src/lib.rs', lines 203:0-203:56 -/
@[reducible]
def sha256.pre (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def sha256.spec (payload : Slice Std.U8) : Prop :=
  (sha256.pre payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha256 payload
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::sha256_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 216:0-216:96 -/
@[reducible]
def sha256_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if i <= i1
  then let i2 ← core.slice.Slice.len digest
       ok (i2 = SHA3_256_DIGEST_SIZE)
  else ok false

/-- [libcrux_iot_sha3::sha256_ema::post]:
    Source: 'sha3/src/lib.rs', lines 217:0-219:66 -/
@[reducible]
def sha256_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len digest_future
  if i = SHA3_256_DIGEST_SIZE
  then
    let s ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
    let s1 ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
    let a ← hacspec_sha3.sha3.sha3_256 s1
    let s2 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8)) a ()
    core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8
      s s2
  else ok false

def sha256_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha256_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha256_ema digest payload
  ⦃ ⇓ res => ⌜ (sha256_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha384::pre]:
    Source: 'sha3/src/lib.rs', lines 233:0-233:56 -/
@[reducible]
def sha384.pre (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def sha384.spec (payload : Slice Std.U8) : Prop :=
  (sha384.pre payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha384 payload
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::sha384_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 246:0-246:96 -/
@[reducible]
def sha384_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if i <= i1
  then let i2 ← core.slice.Slice.len digest
       ok (i2 = SHA3_384_DIGEST_SIZE)
  else ok false

/-- [libcrux_iot_sha3::sha384_ema::post]:
    Source: 'sha3/src/lib.rs', lines 247:0-249:66 -/
@[reducible]
def sha384_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len digest_future
  if i = SHA3_384_DIGEST_SIZE
  then
    let s ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
    let s1 ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
    let a ← hacspec_sha3.sha3.sha3_384 s1
    let s2 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8)) a ()
    core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8
      s s2
  else ok false

def sha384_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha384_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha384_ema digest payload
  ⦃ ⇓ res => ⌜ (sha384_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::sha512::pre]:
    Source: 'sha3/src/lib.rs', lines 263:0-263:56 -/
@[reducible]
def sha512.pre (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def sha512.spec (payload : Slice Std.U8) : Prop :=
  (sha512.pre payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha512 payload
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::sha512_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 276:0-276:96 -/
@[reducible]
def sha512_ema.pre
  (digest : Slice Std.U8) (payload : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len payload
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  if i <= i1
  then let i2 ← core.slice.Slice.len digest
       ok (i2 = SHA3_512_DIGEST_SIZE)
  else ok false

/-- [libcrux_iot_sha3::sha512_ema::post]:
    Source: 'sha3/src/lib.rs', lines 277:0-279:66 -/
@[reducible]
def sha512_ema.post
  (digest : Slice Std.U8) (payload : Slice Std.U8)
  (digest_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len digest_future
  if i = SHA3_512_DIGEST_SIZE
  then
    let s ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar digest_future
    let s1 ←
      libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
        libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar payload
    let a ← hacspec_sha3.sha3.sha3_512 s1
    let s2 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8)) a ()
    core.Slice.Insts.CoreCmpPartialEqSlice.eq core.U8.Insts.CoreCmpPartialEqU8
      s s2
  else ok false

def sha512_ema.spec (digest : Slice Std.U8) (payload : Slice Std.U8) : Prop :=
  (sha512_ema.pre digest payload).holds →
  ⦃ ⌜ True ⌝ ⦄
  sha512_ema digest payload
  ⦃ ⇓ res => ⌜ (sha512_ema.post digest payload res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake128::pre]:
    Source: 'sha3/src/lib.rs', lines 293:0-293:48 -/
@[reducible]
def shake128.pre (BYTES : Std.Usize) (data : Slice Std.U8) : RustM Bool := do
  let i ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (BYTES <= i)

/-- [libcrux_iot_sha3::shake128::post]:
    Source: 'sha3/src/lib.rs', lines 294:0-295:63 -/
@[reducible]
def shake128.post
  {BYTES : Std.Usize} (data : Slice Std.U8) (out : Array Std.U8 BYTES) :
  RustM Bool
  := do
  let a ← libcrux_secrets.traits.Declassify.Blanket.declassify out
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let a1 ← hacspec_sha3.sha3.shake128 BYTES s
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U8.Insts.CoreCmpPartialEqU8 a
    a1

def shake128.spec (BYTES : Std.Usize) (data : Slice Std.U8) : Prop :=
  (shake128.pre BYTES data).holds →
  ⦃ ⌜ True ⌝ ⦄
  shake128 BYTES data
  ⦃ ⇓ res => ⌜ (shake128.post data res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake128_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 309:0-309:52 -/
@[reducible]
def shake128_ema.pre
  (out : Slice Std.U8) (data : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len out
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def shake128_ema.spec (out : Slice Std.U8) (data : Slice Std.U8) : Prop :=
  (shake128_ema.pre out data).holds →
  ⦃ ⌜ True ⌝ ⦄
  shake128_ema out data
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::shake256::pre]:
    Source: 'sha3/src/lib.rs', lines 318:0-318:48 -/
@[reducible]
def shake256.pre (BYTES : Std.Usize) (data : Slice Std.U8) : RustM Bool := do
  let i ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (BYTES <= i)

/-- [libcrux_iot_sha3::shake256::post]:
    Source: 'sha3/src/lib.rs', lines 319:0-320:63 -/
@[reducible]
def shake256.post
  {BYTES : Std.Usize} (data : Slice Std.U8) (out : Array Std.U8 BYTES) :
  RustM Bool
  := do
  let a ← libcrux_secrets.traits.Declassify.Blanket.declassify out
  let s ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let a1 ← hacspec_sha3.sha3.shake256 BYTES s
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U8.Insts.CoreCmpPartialEqU8 a
    a1

def shake256.spec (BYTES : Std.Usize) (data : Slice Std.U8) : Prop :=
  (shake256.pre BYTES data).holds →
  ⦃ ⌜ True ⌝ ⦄
  shake256 BYTES data
  ⦃ ⇓ res => ⌜ (shake256.post data res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::shake256_ema::pre]:
    Source: 'sha3/src/lib.rs', lines 334:0-334:52 -/
@[reducible]
def shake256_ema.pre
  (out : Slice Std.U8) (data : Slice Std.U8) : RustM Bool := do
  let i ← core.slice.Slice.len out
  let i1 ← lift (UScalar.cast .Usize core.num.U32.MAX)
  ok (i <= i1)

def shake256_ema.spec (out : Slice Std.U8) (data : Slice Std.U8) : Prop :=
  (shake256_ema.pre out data).holds →
  ⦃ ⌜ True ⌝ ⦄
  shake256_ema out data
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccakx1::pre]:
    Source: 'sha3/src/lib.rs', lines 546:0-548:2 -/
@[reducible]
def keccakx1.pre
  (RATE : Std.Usize) (DELIM : Std.U8) (data : Slice Std.U8)
  (out : Slice Std.U8) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then ok (RATE <= 168#usize)
    else ok false
  else ok false

def keccakx1.spec (RATE : Std.Usize) (DELIM : Std.U8) (data : Slice Std.U8)
  (out : Slice Std.U8) : Prop :=
  (keccakx1.pre RATE DELIM data out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccakx1 RATE DELIM data out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::_squeeze::pre]:
    Source: 'sha3/src/keccak.rs', lines 211:0-211:92 -/
@[reducible]
def keccak._squeeze.pre
  {RATE : Std.Usize} (keccak_state : keccak.KeccakXofState RATE)
  (out : Slice Std.U8) :
  RustM Bool
  := do
  if RATE = 168#usize
  then ok true
  else
    if RATE = 144#usize
    then ok true
    else
      if RATE = 136#usize
      then ok true
      else if RATE = 104#usize
           then ok true
           else ok (RATE = 72#usize)

def keccak._squeeze.spec {RATE : Std.Usize}
  (keccak_state : keccak.KeccakXofState RATE) (out : Slice Std.U8) : Prop :=
  (keccak._squeeze.pre keccak_state out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak._squeeze keccak_state out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::absorb_block::pre]:
    Source: 'sha3/src/keccak.rs', lines 2594:0-2598:2 -/
@[reducible]
def keccak.absorb_block.pre
  (RATE : Std.Usize) (s : state.KeccakState) (blocks : Slice Std.U8)
  (start : Std.Usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then
      let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int start
      let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int RATE
      let i3 ←
        hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
      let i4 ← core.slice.Slice.len blocks
      let i5 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i4
      core.cmp.PartialOrd.le.default
        hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i5
    else ok false
  else ok false

def keccak.absorb_block.spec (RATE : Std.Usize) (s : state.KeccakState)
  (blocks : Slice Std.U8) (start : Std.Usize) : Prop :=
  (keccak.absorb_block.pre RATE s blocks start).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.absorb_block RATE s blocks start
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::absorb_final::pre]:
    Source: 'sha3/src/keccak.rs', lines 2605:0-2610:61 -/
@[reducible]
def keccak.absorb_final.pre
  (RATE : Std.Usize) (DELIM : Std.U8) (s : state.KeccakState)
  (last : Slice Std.U8) (start : Std.Usize) (len : Std.Usize) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then
      if RATE <= 168#usize
      then
        if len < RATE
        then
          let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int start
          let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int len
          let i3 ←
            hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
          let i4 ← core.slice.Slice.len last
          let i5 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i4
          core.cmp.PartialOrd.le.default
            hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i5
        else ok false
      else ok false
    else ok false
  else ok false

def keccak.absorb_final.spec (RATE : Std.Usize) (DELIM : Std.U8)
  (s : state.KeccakState) (last : Slice Std.U8) (start : Std.Usize)
  (len : Std.Usize) : Prop :=
  (keccak.absorb_final.pre RATE DELIM s last start len).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.absorb_final RATE DELIM s last start len
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::squeeze_first_block::pre]:
    Source: 'sha3/src/keccak.rs', lines 2631:0-2631:71 -/
@[reducible]
def keccak.squeeze_first_block.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (RATE <= i1)
    else ok false
  else ok false

/-- [libcrux_iot_sha3::keccak::squeeze_first_block::post]:
    Source: 'sha3/src/keccak.rs', lines 2632:0-2632:55 -/
@[reducible]
def keccak.squeeze_first_block.post
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8)
  (out_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len out_future
  let i1 ← core.slice.Slice.len out
  ok (i = i1)

def keccak.squeeze_first_block.spec (RATE : Std.Usize) (s : state.KeccakState)
  (out : Slice Std.U8) : Prop :=
  (keccak.squeeze_first_block.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.squeeze_first_block RATE s out
  ⦃ ⇓ res => ⌜ (keccak.squeeze_first_block.post RATE s out res).holds ⌝
  ⦄


/-- [libcrux_iot_sha3::keccak::squeeze_next_block::pre]:
    Source: 'sha3/src/keccak.rs', lines 2638:0-2638:71 -/
@[reducible]
def keccak.squeeze_next_block.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (RATE <= i1)
    else ok false
  else ok false

/-- [libcrux_iot_sha3::keccak::squeeze_next_block::post]:
    Source: 'sha3/src/keccak.rs', lines 2639:0-2639:55 -/
@[reducible]
def keccak.squeeze_next_block.post
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8)
  (p : (state.KeccakState × (Slice Std.U8))) :
  RustM Bool
  := do
  let (_, out_future) := p
  let i ← core.slice.Slice.len out_future
  let i1 ← core.slice.Slice.len out
  ok (i = i1)

def keccak.squeeze_next_block.spec (RATE : Std.Usize) (s : state.KeccakState)
  (out : Slice Std.U8) : Prop :=
  (keccak.squeeze_next_block.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.squeeze_next_block RATE s out
  ⦃ ⇓ res => ⌜ (keccak.squeeze_next_block.post RATE s out res).holds ⌝
  ⦄


/-- [libcrux_iot_sha3::keccak::squeeze_last::pre]:
    Source: 'sha3/src/keccak.rs', lines 2666:0-2666:70 -/
@[reducible]
def keccak.squeeze_last.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (i1 <= 200#usize)
    else ok false
  else ok false

def keccak.squeeze_last.spec (RATE : Std.Usize) (s : state.KeccakState)
  (out : Slice Std.U8) : Prop :=
  (keccak.squeeze_last.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.squeeze_last RATE s out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::squeeze_first_and_last::pre]:
    Source: 'sha3/src/keccak.rs', lines 2675:0-2675:70 -/
@[reducible]
def keccak.squeeze_first_and_last.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (i1 <= 200#usize)
    else ok false
  else ok false

def keccak.squeeze_first_and_last.spec (RATE : Std.Usize)
  (s : state.KeccakState) (out : Slice Std.U8) : Prop :=
  (keccak.squeeze_first_and_last.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.squeeze_first_and_last RATE s out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::keccak_fc::pre]:
    Source: 'sha3/src/keccak.rs', lines 2696:0-2696:62 -/
@[reducible]
def keccak.keccak_fc.pre
  (RATE : Std.Usize) (DELIM : Std.U8) {OUT_LEN : Std.Usize}
  (data : Slice Std.U8) (out : Array Std.U8 OUT_LEN) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then ok (RATE <= 168#usize)
    else ok false
  else ok false

/-- [libcrux_iot_sha3::keccak::keccak_fc::post]:
    Source: 'sha3/src/keccak.rs', lines 2697:0-2701:3 -/
@[reducible]
def keccak.keccak_fc.post
  (RATE : Std.Usize) (DELIM : Std.U8) {OUT_LEN : Std.Usize}
  (data : Slice Std.U8) (out : Array Std.U8 OUT_LEN) (_ : Unit) :
  RustM Bool
  := do
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ← keccak.keccak RATE DELIM data s
  let out1 := to_slice_mut_back s1
  let a ← libcrux_secrets.traits.Declassify.Blanket.declassify out1
  let s2 ←
    libcrux_secrets.SharedASlice.Insts.Libcrux_secretsTraitsDeclassifyRefSharedASlice.declassify_ref
      libcrux_secrets.U8.Insts.Libcrux_secretsTraitsScalar data
  let a1 ← hacspec_sha3.sponge.keccak OUT_LEN RATE DELIM s2
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U8.Insts.CoreCmpPartialEqU8 a
    a1

def
  keccak.keccak_fc.spec (RATE : Std.Usize) (DELIM : Std.U8) {OUT_LEN :
                       Std.Usize} (data : Slice Std.U8)
  (out : Array Std.U8 OUT_LEN) : Prop :=
  (keccak.keccak_fc.pre RATE DELIM data out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.keccak_fc RATE DELIM data out
  ⦃ ⇓ res => ⌜ (keccak.keccak_fc.post RATE DELIM data out res).holds ⌝
  ⦄


/-- [libcrux_iot_sha3::state::load_block_2u32::pre]:
    Source: 'sha3/src/state.rs', lines 131:0-131:109 -/
@[reducible]
def state.load_block_2u32.pre
  (RATE : Std.Usize) (keccak_state : state.KeccakState) (blocks : Slice Std.U8)
  (start : Std.Usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then
      let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int start
      let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int RATE
      let i3 ←
        hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
      let i4 ← core.slice.Slice.len blocks
      let i5 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i4
      core.cmp.PartialOrd.le.default
        hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i5
    else ok false
  else ok false

def state.load_block_2u32.spec (RATE : Std.Usize)
  (keccak_state : state.KeccakState) (blocks : Slice Std.U8)
  (start : Std.Usize) : Prop :=
  (state.load_block_2u32.pre RATE keccak_state blocks start).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.load_block_2u32 RATE keccak_state blocks start
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::load_block_full_2u32::pre]:
    Source: 'sha3/src/state.rs', lines 151:0-151:100 -/
@[reducible]
def state.load_block_full_2u32.pre
  (RATE : Std.Usize) (keccak_state : state.KeccakState)
  (blocks : Array Std.U8 200#usize) (start : Std.Usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then
      let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int start
      let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int RATE
      let i3 ←
        hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
      let i4 ← hax_lib.I32.Insts.Hax_lib_2IntToInt.to_int 200#i32
      core.cmp.PartialOrd.le.default
        hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
    else ok false
  else ok false

def state.load_block_full_2u32.spec (RATE : Std.Usize)
  (keccak_state : state.KeccakState) (blocks : Array Std.U8 200#usize)
  (start : Std.Usize) : Prop :=
  (state.load_block_full_2u32.pre RATE keccak_state blocks start).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.load_block_full_2u32 RATE keccak_state blocks start
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::store_block_2u32::pre]:
    Source: 'sha3/src/state.rs', lines 161:0-161:71 -/
@[reducible]
def state.store_block_2u32.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (RATE <= i1)
    else ok false
  else ok false

def state.store_block_2u32.spec (RATE : Std.Usize) (s : state.KeccakState)
  (out : Slice Std.U8) : Prop :=
  (state.store_block_2u32.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.store_block_2u32 RATE s out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::store_block_full_2u32::pre]:
    Source: 'sha3/src/state.rs', lines 176:0-176:50 -/
@[reducible]
def state.store_block_full_2u32.pre
  (RATE : Std.Usize) (s : state.KeccakState) (out : Array Std.U8 200#usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then ok (RATE <= 168#usize)
  else ok false

def state.store_block_full_2u32.spec (RATE : Std.Usize) (s : state.KeccakState)
  (out : Array Std.U8 200#usize) : Prop :=
  (state.store_block_full_2u32.pre RATE s out).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.store_block_full_2u32 RATE s out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::absorb::pre]:
    Source: 'sha3/src/keccak.rs', lines 56:4-62:6 -/
@[reducible]
def keccak.KeccakXofState.absorb.pre
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then
      if RATE <= 168#usize
      then
        if self_.buf_len < RATE
        then
          let i1 ← core.slice.Slice.len inputs
          let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i1
          let i3 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.buf_len
          let i4 ←
            hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i2 i3
          let i5 ←
            hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
          core.cmp.PartialOrd.le.default
            hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i4 i5
        else ok false
      else ok false
    else ok false
  else ok false

def keccak.KeccakXofState.absorb.spec {RATE : Std.Usize}
  (self : keccak.KeccakXofState RATE) (inputs : Slice Std.U8) : Prop :=
  (keccak.KeccakXofState.absorb.pre self inputs).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.KeccakXofState.absorb self inputs
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::absorb_full::pre]:
    Source: 'sha3/src/keccak.rs', lines 81:4-87:6 -/
@[reducible]
def keccak.KeccakXofState.absorb_full.pre
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then
      if RATE <= 168#usize
      then
        if self_.buf_len < RATE
        then
          let i1 ← core.slice.Slice.len inputs
          let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i1
          let i3 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.buf_len
          let i4 ←
            hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i2 i3
          let i5 ←
            hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
          core.cmp.PartialOrd.le.default
            hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i4 i5
        else ok false
      else ok false
    else ok false
  else ok false

/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::absorb_full::post]:
    Source: 'sha3/src/keccak.rs', lines 88:4-93:6 -/
@[reducible]
def keccak.KeccakXofState.absorb_full.post
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) (p : (Std.Usize × (keccak.KeccakXofState RATE))) :
  RustM Bool
  := do
  let (remainder, self__future) := p
  if remainder < RATE
  then
    let i ← core.slice.Slice.len inputs
    if remainder <= i
    then
      if self__future.buf_len <= RATE
      then
        let i1 ←
          hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self__future.buf_len
        let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int remainder
        let i3 ←
          hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
        let i4 ←
          hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
        core.cmp.PartialOrd.lt.default
          hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
      else ok false
    else ok false
  else ok false

def keccak.KeccakXofState.absorb_full.spec {RATE : Std.Usize}
  (self : keccak.KeccakXofState RATE) (inputs : Slice Std.U8) : Prop :=
  (keccak.KeccakXofState.absorb_full.pre self inputs).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.KeccakXofState.absorb_full self inputs
  ⦃ ⇓ res =>
  ⌜ (keccak.KeccakXofState.absorb_full.post self inputs res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::fill_buffer::pre]:
    Source: 'sha3/src/keccak.rs', lines 139:4-142:6 -/
@[reducible]
def keccak.KeccakXofState.fill_buffer.pre
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) :
  RustM Bool
  := do
  if self_.buf_len <= RATE
  then
    let i ← core.slice.Slice.len inputs
    let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i
    let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.buf_len
    let i3 ← hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
    let i4 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
    core.cmp.PartialOrd.le.default
      hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
  else ok false

/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::fill_buffer::post]:
    Source: 'sha3/src/keccak.rs', lines 143:4-147:6 -/
@[reducible]
def keccak.KeccakXofState.fill_buffer.post
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) (p : (Std.Usize × (keccak.KeccakXofState RATE))) :
  RustM hax_lib_2.prop.Prop
  := do
  let (res, self__future) := p
  let p1 ← hax_lib.Bool.Insts.Hax_lib_2PropToProp.to_prop (res <= RATE)
  let p2 ←
    hax_lib.Bool.Insts.Hax_lib_2PropToProp.to_prop (self__future.buf_len <=
      RATE)
  let p3 ←
    hax_lib.hax_lib_2.prop.Prop.Insts.CoreOpsBitBitAndTProp.bitand
      (core.convert.Into.Blanket (core.convert.From.Blanket
      hax_lib_2.prop.Prop)) p1 p2
  let p4 ←
    hax_lib_2.prop.implies (core.convert.Into.Blanket
      hax_lib.hax_lib_2.prop.Prop.Insts.CoreConvertFromBool)
      (core.convert.Into.Blanket
      hax_lib.hax_lib_2.prop.Prop.Insts.CoreConvertFromBool) (res > 0#usize)
      (self__future.buf_len = RATE)
  hax_lib.hax_lib_2.prop.Prop.Insts.CoreOpsBitBitAndTProp.bitand
    (core.convert.Into.Blanket (core.convert.From.Blanket hax_lib_2.prop.Prop))
    p3 p4

def keccak.KeccakXofState.fill_buffer.spec {RATE : Std.Usize}
  (self : keccak.KeccakXofState RATE) (inputs : Slice Std.U8) : Prop :=
  (keccak.KeccakXofState.fill_buffer.pre self inputs).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.KeccakXofState.fill_buffer self inputs
  ⦃ ⇓ res =>
  ⌜ (keccak.KeccakXofState.fill_buffer.post self inputs res).holds ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::absorb_final::pre]:
    Source: 'sha3/src/keccak.rs', lines 169:4-175:6 -/
@[reducible]
def keccak.KeccakXofState.absorb_final.pre
  {RATE : Std.Usize} (DELIMITER : Std.U8) (self_ : keccak.KeccakXofState RATE)
  (inputs : Slice Std.U8) :
  RustM Bool
  := do
  if RATE > 0#usize
  then
    let i ← RATE % 8#usize
    if i = 0#usize
    then
      if RATE <= 168#usize
      then
        if self_.buf_len < RATE
        then
          let i1 ← core.slice.Slice.len inputs
          let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i1
          let i3 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.buf_len
          let i4 ←
            hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i2 i3
          let i5 ←
            hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
          core.cmp.PartialOrd.le.default
            hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i4 i5
        else ok false
      else ok false
    else ok false
  else ok false

def
  keccak.KeccakXofState.absorb_final.spec {RATE : Std.Usize} (DELIMITER :
                                         Std.U8)
  (self : keccak.KeccakXofState RATE) (inputs : Slice Std.U8) : Prop :=
  (keccak.KeccakXofState.absorb_final.pre DELIMITER self inputs).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.KeccakXofState.absorb_final DELIMITER self inputs
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::squeeze::pre]:
    Source: 'sha3/src/keccak.rs', lines 199:4-199:96 -/
@[reducible]
def keccak.KeccakXofState.squeeze.pre
  {RATE : Std.Usize} (self_ : keccak.KeccakXofState RATE) (out : Slice Std.U8)
  :
  RustM Bool
  := do
  if RATE = 168#usize
  then ok true
  else
    if RATE = 144#usize
    then ok true
    else
      if RATE = 136#usize
      then ok true
      else if RATE = 104#usize
           then ok true
           else ok (RATE = 72#usize)

def keccak.KeccakXofState.squeeze.spec {RATE : Std.Usize}
  (self : keccak.KeccakXofState RATE) (out : Slice Std.U8) : Prop :=
  (keccak.KeccakXofState.squeeze.pre self out).holds →
  ⦃ ⌜ True ⌝ ⦄
  keccak.KeccakXofState.squeeze self out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::store::pre]:
    Source: 'sha3/src/state.rs', lines 89:4-89:75 -/
@[reducible]
def state.KeccakState.store.pre
  (RATE : Std.Usize) (self_ : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (i1 <= RATE)
    else ok false
  else ok false

/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::store::post]:
    Source: 'sha3/src/state.rs', lines 90:4-90:59 -/
@[reducible]
def state.KeccakState.store.post
  (RATE : Std.Usize) (self_ : state.KeccakState) (out : Slice Std.U8)
  (out_future : Slice Std.U8) :
  RustM Bool
  := do
  let i ← core.slice.Slice.len out_future
  let i1 ← core.slice.Slice.len out
  ok (i = i1)

def state.KeccakState.store.spec (RATE : Std.Usize) (self : state.KeccakState)
  (out : Slice Std.U8) : Prop :=
  (state.KeccakState.store.pre RATE self out).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.store RATE self out
  ⦃ ⇓ res => ⌜ (state.KeccakState.store.post RATE self out res).holds ⌝
  ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::get_with_zeta::pre]:
    Source: 'sha3/src/state.rs', lines 29:4-29:52 -/
@[reducible]
def state.KeccakState.get_with_zeta.pre
  (self_ : state.KeccakState) (i : Std.Usize) (j : Std.Usize)
  (zeta : Std.Usize) :
  RustM Bool
  := do
  if i < 5#usize
  then if j < 5#usize
       then ok (zeta < 2#usize)
       else ok false
  else ok false

def state.KeccakState.get_with_zeta.spec (self : state.KeccakState)
  (i : Std.Usize) (j : Std.Usize) (zeta : Std.Usize) : Prop :=
  (state.KeccakState.get_with_zeta.pre self i j zeta).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.get_with_zeta self i j zeta
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::set_lane_value::pre]:
    Source: 'sha3/src/state.rs', lines 53:4-53:40 -/
@[reducible]
def state.KeccakState.set_lane_value.pre
  (self_ : state.KeccakState) (i : Std.Usize) (j : Std.Usize) (value : Std.U32)
  :
  RustM Bool
  := do
  if i < 5#usize
  then ok (j < 2#usize)
  else ok false

def state.KeccakState.set_lane_value.spec (self : state.KeccakState)
  (i : Std.Usize) (j : Std.Usize) (value : Std.U32) : Prop :=
  (state.KeccakState.set_lane_value.pre self i j value).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.set_lane_value self i j value
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::lane::{impl core::ops::index::Index<usize, u32> for libcrux_iot_sha3::lane::Lane2U32}::index::pre]:
    Source: 'sha3/src/lane.rs', lines 86:4-86:35 -/
@[reducible]
def lane.IndexLane2U32UsizeU32.index.pre
  (self_ : lane.Lane2U32) (index : Std.Usize) : RustM Bool := do
  ok (index < 2#usize)

def lane.Lane2U32.Insts.CoreOpsIndexIndexUsizeU32.index.spec
  (self : lane.Lane2U32) (index : Std.Usize) : Prop :=
  (lane.IndexLane2U32UsizeU32.index.pre self index).holds →
  ⦃ ⌜ True ⌝ ⦄
  lane.Lane2U32.Insts.CoreOpsIndexIndexUsizeU32.index self index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::set_with_zeta::pre]:
    Source: 'sha3/src/state.rs', lines 35:4-35:52 -/
@[reducible]
def state.KeccakState.set_with_zeta.pre
  (self_ : state.KeccakState) (i : Std.Usize) (j : Std.Usize)
  (zeta : Std.Usize) (v : Std.U32) :
  RustM Bool
  := do
  if i < 5#usize
  then if j < 5#usize
       then ok (zeta < 2#usize)
       else ok false
  else ok false

def state.KeccakState.set_with_zeta.spec (self : state.KeccakState)
  (i : Std.Usize) (j : Std.Usize) (zeta : Std.Usize) (v : Std.U32) : Prop :=
  (state.KeccakState.set_with_zeta.pre self i j zeta v).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.set_with_zeta self i j zeta v
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::load_block::pre]:
    Source: 'sha3/src/state.rs', lines 63:4-63:113 -/
@[reducible]
def state.KeccakState.load_block.pre
  (RATE : Std.Usize) (self_ : state.KeccakState) (blocks : Slice Std.U8)
  (start : Std.Usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then
      let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int start
      let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int RATE
      let i3 ←
        hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
      let i4 ← core.slice.Slice.len blocks
      let i5 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i4
      core.cmp.PartialOrd.le.default
        hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i5
    else ok false
  else ok false

def state.KeccakState.load_block.spec (RATE : Std.Usize)
  (self : state.KeccakState) (blocks : Slice Std.U8) (start : Std.Usize)
  : Prop :=
  (state.KeccakState.load_block.pre RATE self blocks start).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.load_block RATE self blocks start
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::load_block_full::pre]:
    Source: 'sha3/src/state.rs', lines 75:4-75:93 -/
@[reducible]
def state.KeccakState.load_block_full.pre
  (RATE : Std.Usize) (self_ : state.KeccakState)
  (blocks : Array Std.U8 200#usize) (start : Std.Usize) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then
      if start <= 200#usize
      then let i1 ← start + RATE
           ok (i1 <= 168#usize)
      else ok false
    else ok false
  else ok false

def state.KeccakState.load_block_full.spec (RATE : Std.Usize)
  (self : state.KeccakState) (blocks : Array Std.U8 200#usize)
  (start : Std.Usize) : Prop :=
  (state.KeccakState.load_block_full.pre RATE self blocks start).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.load_block_full RATE self blocks start
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::store_block::pre]:
    Source: 'sha3/src/state.rs', lines 69:4-69:75 -/
@[reducible]
def state.KeccakState.store_block.pre
  (RATE : Std.Usize) (self_ : state.KeccakState) (out : Slice Std.U8) :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then
    if RATE <= 168#usize
    then let i1 ← core.slice.Slice.len out
         ok (RATE <= i1)
    else ok false
  else ok false

def state.KeccakState.store_block.spec (RATE : Std.Usize)
  (self : state.KeccakState) (out : Slice Std.U8) : Prop :=
  (state.KeccakState.store_block.pre RATE self out).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.store_block RATE self out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::store_block_full::pre]:
    Source: 'sha3/src/state.rs', lines 81:4-81:54 -/
@[reducible]
def state.KeccakState.store_block_full.pre
  (RATE : Std.Usize) (self_ : state.KeccakState) (out : Array Std.U8 200#usize)
  :
  RustM Bool
  := do
  let i ← RATE % 8#usize
  if i = 0#usize
  then ok (RATE <= 168#usize)
  else ok false

def state.KeccakState.store_block_full.spec (RATE : Std.Usize)
  (self : state.KeccakState) (out : Array Std.U8 200#usize) : Prop :=
  (state.KeccakState.store_block_full.pre RATE self out).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.store_block_full RATE self out
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::get_lane::pre]:
    Source: 'sha3/src/state.rs', lines 41:4-41:40 -/
@[reducible]
def state.KeccakState.get_lane.pre
  (self_ : state.KeccakState) (i : Std.Usize) (j : Std.Usize) :
  RustM Bool
  := do
  if i < 5#usize
  then ok (j < 5#usize)
  else ok false

def state.KeccakState.get_lane.spec (self : state.KeccakState) (i : Std.Usize)
  (j : Std.Usize) : Prop :=
  (state.KeccakState.get_lane.pre self i j).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.get_lane self i j
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::set_lane::pre]:
    Source: 'sha3/src/state.rs', lines 47:4-47:40 -/
@[reducible]
def state.KeccakState.set_lane.pre
  (self_ : state.KeccakState) (i : Std.Usize) (j : Std.Usize)
  (lane1 : lane.Lane2U32) :
  RustM Bool
  := do
  if i < 5#usize
  then ok (j < 5#usize)
  else ok false

def state.KeccakState.set_lane.spec (self : state.KeccakState) (i : Std.Usize)
  (j : Std.Usize) (lane1 : lane.Lane2U32) : Prop :=
  (state.KeccakState.set_lane.pre self i j lane1).holds →
  ⦃ ⌜ True ⌝ ⦄
  state.KeccakState.set_lane self i j lane1
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::incremental::{impl libcrux_iot_sha3::incremental::Xof<168usize> for libcrux_iot_sha3::incremental::Shake128Xof}::absorb::pre]:
    Source: 'sha3/src/lib.rs', lines 427:8-430:10 -/
@[reducible]
def incremental.XofShake128Xof168.absorb.pre
  (self_ : incremental.Shake128Xof) (input : Slice Std.U8) : RustM Bool := do
  if self_.state.buf_len < 168#usize
  then
    let i ← core.slice.Slice.len input
    let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i
    let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.state.buf_len
    let i3 ← hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
    let i4 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
    core.cmp.PartialOrd.le.default
      hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
  else ok false

def incremental.Shake128Xof.Insts.Libcrux_iot_sha3IncrementalXof168.absorb.spec
   (self : incremental.Shake128Xof) (input : Slice Std.U8) : Prop :=
  (incremental.XofShake128Xof168.absorb.pre self input).holds →
  ⦃ ⌜ True ⌝ ⦄
  incremental.Shake128Xof.Insts.Libcrux_iot_sha3IncrementalXof168.absorb self
  input
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::incremental::{impl libcrux_iot_sha3::incremental::Xof<168usize> for libcrux_iot_sha3::incremental::Shake128Xof}::absorb_final::pre]:
    Source: 'sha3/src/lib.rs', lines 435:8-438:10 -/
@[reducible]
def incremental.XofShake128Xof168.absorb_final.pre
  (self_ : incremental.Shake128Xof) (input : Slice Std.U8) : RustM Bool := do
  if self_.state.buf_len < 168#usize
  then
    let i ← core.slice.Slice.len input
    let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i
    let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.state.buf_len
    let i3 ← hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
    let i4 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
    core.cmp.PartialOrd.le.default
      hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
  else ok false

def
  incremental.Shake128Xof.Insts.Libcrux_iot_sha3IncrementalXof168.absorb_final.spec
   (self : incremental.Shake128Xof) (input : Slice Std.U8) : Prop :=
  (incremental.XofShake128Xof168.absorb_final.pre self input).holds →
  ⦃ ⌜ True ⌝ ⦄
  incremental.Shake128Xof.Insts.Libcrux_iot_sha3IncrementalXof168.absorb_final
  self input
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::incremental::{impl libcrux_iot_sha3::incremental::Xof<136usize> for libcrux_iot_sha3::incremental::Shake256Xof}::absorb::pre]:
    Source: 'sha3/src/lib.rs', lines 456:8-459:10 -/
@[reducible]
def incremental.XofShake256Xof136.absorb.pre
  (self_ : incremental.Shake256Xof) (input : Slice Std.U8) : RustM Bool := do
  if self_.state.buf_len < 136#usize
  then
    let i ← core.slice.Slice.len input
    let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i
    let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.state.buf_len
    let i3 ← hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
    let i4 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
    core.cmp.PartialOrd.le.default
      hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
  else ok false

def incremental.Shake256Xof.Insts.Libcrux_iot_sha3IncrementalXof136.absorb.spec
   (self : incremental.Shake256Xof) (input : Slice Std.U8) : Prop :=
  (incremental.XofShake256Xof136.absorb.pre self input).holds →
  ⦃ ⌜ True ⌝ ⦄
  incremental.Shake256Xof.Insts.Libcrux_iot_sha3IncrementalXof136.absorb self
  input
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [libcrux_iot_sha3::incremental::{impl libcrux_iot_sha3::incremental::Xof<136usize> for libcrux_iot_sha3::incremental::Shake256Xof}::absorb_final::pre]:
    Source: 'sha3/src/lib.rs', lines 464:8-467:10 -/
@[reducible]
def incremental.XofShake256Xof136.absorb_final.pre
  (self_ : incremental.Shake256Xof) (input : Slice Std.U8) : RustM Bool := do
  if self_.state.buf_len < 136#usize
  then
    let i ← core.slice.Slice.len input
    let i1 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int i
    let i2 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int self_.state.buf_len
    let i3 ← hax_lib.hax_lib_2.int.Int.Insts.CoreOpsArithAddIntInt.add i1 i2
    let i4 ← hax_lib.Usize.Insts.Hax_lib_2IntToInt.to_int core.num.Usize.MAX
    core.cmp.PartialOrd.le.default
      hax_lib.hax_lib_2.int.Int.Insts.CoreCmpPartialOrdInt i3 i4
  else ok false

def
  incremental.Shake256Xof.Insts.Libcrux_iot_sha3IncrementalXof136.absorb_final.spec
   (self : incremental.Shake256Xof) (input : Slice Std.U8) : Prop :=
  (incremental.XofShake256Xof136.absorb_final.pre self input).holds →
  ⦃ ⌜ True ⌝ ⦄
  incremental.Shake256Xof.Insts.Libcrux_iot_sha3IncrementalXof136.absorb_final
  self input
  ⦃ ⇓ res => ⌜ True ⌝ ⦄

end libcrux_iot_sha3
