/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotMlDsa.Extraction`. -/

/-
  # Discharging the hax-generated specs -- and what it exposes

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust: for each annotated function a
  `<fn>.pre` (the `requires`, as a `RustM Bool`), optionally a `<fn>.post`, and

    `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  ML-DSA's annotations sit on the eight `simd.portable.arithmetic` helpers, not on
  the polynomial API, so those eight are what got generated. Six of them have a
  hand-written correctness theorem in `Vector/Portable/Rounding.lean`.

  ## The finding: NONE of the eight is dischargeable as generated

  Not one of the six can be proved from its existing theorem, and the reason is
  worth stating precisely, because it is a real mismatch between the Rust
  annotations and the Lean development rather than a proof-engineering nuisance.

  (1) THE ANNOTATION IS WEAKER THAN THE PROOF'S DOMAIN.
      `compute_one_hint` and `compute_hint` are annotated
      `requires(gamma2 != i32::MIN)` -- just enough for `-gamma2` not to overflow.
      Their Lean theorems assume `gamma2 ∈ {95232, 261888}`, the two FIPS-204
      values, because the functional postcondition is stated against
      `Spec.Rounding.computeHint`, which is only meaningful there. So the
      generated obligation claims MORE than we proved: panic-freedom for every
      `gamma2` except `i32::MIN`.

  (2) THE ANNOTATION OMITS INPUT-RANGE PRECONDITIONS THE PROOF NEEDS.
      `decompose_element`, `decompose`, `use_one_hint` and `use_hint` are
      annotated only with `gamma2 ∈ {GAMMA2_V95_232, GAMMA2_V261_888}`. Their Lean
      theorems additionally assume the coefficients lie in `[-q, q)` and, for the
      hint functions, that each hint is `0` or `1`. The Rust says nothing about
      either, so again the generated obligation is the stronger statement.

  In both cases the generated spec is STRICTLY STRONGER than the theorem, so no
  amount of post-weakening closes the gap -- it would take either a genuinely more
  general panic-freedom argument, or a strengthening of the Rust annotations to
  match the domain that was actually verified. That is a decision about the Rust,
  not about the proofs, so it is surfaced here rather than papered over with a
  `sorry`.

  ## What this file does prove

  For each of the six, the generated spec is discharged UNDER THE HYPOTHESES THE
  ANNOTATION IS MISSING, stated explicitly as extra arguments. Each theorem below
  is therefore a real result that reuses the existing correctness proof, and its
  hypothesis list is exactly the gap: whatever appears there beyond
  `(… .pre …).holds` is what the corresponding `#[requires]` would have to gain
  for the generated obligation to hold outright.

  `compute_one_hint` is the most informative case: it is the one ML-DSA function
  with an `#[ensures]`, so its generated `post` is a real property
  (`0 <= out <= 1`) rather than `⌜True⌝` -- and that post IS delivered by the
  existing theorem, which proves `r.val ∈ {0, 1}`.

  The remaining two generated specs, `get_n_least_significant_bits` and
  `shift_left_then_reduce`, have no correctness theorem in the tree at all and are
  left untouched.
-/
import LibcruxIotMlDsa.Extraction
import LibcruxIotMlDsa.Vector.Portable.Rounding

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_ml_dsa.Verification

/-! ## Bridges -/

/-- A Triple with a `⌜True⌝` post says exactly "this computation does not fail
    and does not diverge", so any stronger post implies it. -/
private theorem triple_true_of_triple {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ True ⌝ ⦄ := by
  match hx : x with
  | .ok v => simp [Std.Do.Triple, WP.wp, PredTrans.apply]
  | .fail e =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-- `<fn>.pre` is a `RustM Bool` while `RustM.holds` wants a `RustM Prop`, so the
    generated `.spec` inserts a `(· = true) <$> ·`; on an `ok` that collapses. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Converse of `bool_of_holds_map_ok`: build a generated `post`'s `.holds` from
    the plain boolean fact. -/
private theorem holds_map_ok_of_bool {b : Bool} (h : b = true) :
    RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool)) := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap]
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Triple from an `ok` equation plus the post fact. -/
private theorem triple_of_ok {α : Type} {x : RustM α} {v : α}
    {P : α → Prop} (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

/-- Triple to existential (stated with `x` a variable so the `match` substitutes). -/
private theorem triple_exists_ok {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'; exact h'
  | .fail e =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-! ## The `gamma2 ∈ {95232, 261888}` group

    Here the generated `pre` delivers exactly the theorems' `hg`; what has to be
    supplied on the side is the input-range information the Rust omits. -/

theorem decompose_element_spec_proof (gamma2 r : Std.I32)
    -- supplied because `#[requires]` does not state it:
    (hlo : -(8380417 : Int) ≤ r.val) (hhi : r.val < (8380417 : Int)) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.spec gamma2 r := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.decompose_element_spec gamma2 r hg hlo hhi)

theorem use_one_hint_spec_proof (gamma2 r hint : Std.I32)
    -- supplied because `#[requires]` does not state them:
    (hlo : -(8380417 : Int) ≤ r.val) (hhi : r.val < (8380417 : Int))
    (hh : hint.val = 0 ∨ hint.val = 1) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.spec gamma2 r hint := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.use_one_hint_spec gamma2 r hint hg hlo hhi hh)

theorem decompose_spec_proof (gamma2 : Std.I32)
    (simd_unit low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    -- supplied because `#[requires]` does not state it:
    (hbound : ∀ j : Nat, j < 8 →
        -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
          ∧ (simd_unit.values.val[j]!).val < (8380417 : Int)) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.spec
      gamma2 simd_unit low high := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.decompose_spec gamma2 simd_unit low high hg hbound)

theorem use_hint_spec_proof (gamma2 : Std.I32)
    (simd_unit hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    -- supplied because `#[requires]` does not state them:
    (hbound : ∀ j : Nat, j < 8 →
        -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
          ∧ (simd_unit.values.val[j]!).val < (8380417 : Int))
    (hhint : ∀ j : Nat, j < 8 →
        (hint.values.val[j]!).val = 0 ∨ (hint.values.val[j]!).val = 1) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.spec
      gamma2 simd_unit hint := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.use_hint_spec gamma2 simd_unit hint hg hbound hhint)

/-! ## The `gamma2 != i32::MIN` group

    Here the generated `pre` is too weak to yield the theorems' `hg` at all, so
    `hg` itself is what has to be supplied. -/

theorem compute_hint_spec_proof
    (low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (gamma2 : Std.I32)
    (hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    -- supplied because `#[requires]` only says `gamma2 != i32::MIN`:
    (hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_hint.spec
      low high gamma2 hint := by
  intro _
  exact triple_true_of_triple
    (Vector.Portable.Rounding.compute_hint_spec low high gamma2 hint hg)

/-- The one ML-DSA function with an `#[ensures]`, so the generated `post` is a real
    property (`0 <= out <= 1`) rather than `⌜True⌝` -- and it is delivered by the
    existing theorem, which proves `r.val ∈ {0, 1}`. -/
theorem compute_one_hint_spec_proof (low high gamma2 : Std.I32)
    -- supplied because `#[requires]` only says `gamma2 != i32::MIN`:
    (hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.spec
      low high gamma2 := by
  intro _
  obtain ⟨v, hv_eq, -, hv_01⟩ :=
    triple_exists_ok (Vector.Portable.Rounding.compute_one_hint_spec low high gamma2 hg)
  refine triple_of_ok hv_eq ?_
  -- the generated post is `if out >= 0 then out <= 1 else false`
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.post]
  rw [if_pos (show v ≥ 0#i32 from by scalar_tac)]
  exact holds_map_ok_of_bool (by simp; scalar_tac)

end libcrux_iot_ml_dsa.Verification
