/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotMlDsa.Extraction`. -/

/-
  # Discharging the hax-generated specs -- and what it exposes

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust: for each annotated function a
  `<fn>.pre` (the `requires`, as a `RustM Bool`), optionally a `<fn>.post`, and

    `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  ML-DSA's annotations sit on the eight `simd.portable.arithmetic` helpers, not on
  the polynomial API, so those eight are what got generated. Six of them have a
  hand-written correctness theorem in `Vector/Portable/Rounding.lean`.

  ## The original finding, and what was done about it

  As first generated, NOT ONE of the eight was dischargeable. The annotations
  have since been STRENGTHENED to match the domains the Lean proofs actually
  verify, and ALL SIX that have a correctness theorem now discharge OUTRIGHT:
  every hypothesis of every one of them comes out of its generated `pre`. No
  theorem below takes a hypothesis beyond `(... .pre ...).holds`.

  What that took, beyond pinning `gamma2`:

  - `decompose_element` and `use_one_hint` gained scalar range bounds on their
    coefficient arguments (`r >= -FIELD_MODULUS && r < FIELD_MODULUS`, and
    `hint == 0 || hint == 1`). For `decompose_element` this makes good on the
    `// XXX: ... should be a precondition for hax instead` note that sat next to
    a commented-out `debug_assert!` in `arithmetic.rs`.

  - `decompose` and `use_hint` gained the same bounds PER LANE, via the
    spec-only boolean helpers `coefficients_in_field` / `coefficients_are_hints`.
    Those are written as an explicit eight-way conjunction rather than a
    `hax_lib::forall`, for two reasons documented in full both in
    `arithmetic.rs` and at the decoding lemmas below. In short: a bool `&&`
    inside a quantifier closure makes aeneas fail outright, and even with a
    Prop-level `&` the resulting precondition is unsatisfiable, which would make
    the generated spec vacuous rather than fail loudly.

  Note that the coefficients here are SECRET-typed (`libcrux_secrets::I32`);
  bounding them in a `#[requires]` turned out to be fine, because the annotation
  is erased in non-hax builds.

  ## What the trusted reference actually is

  CORRECTION to an earlier claim of mine, which said ML-DSA's theorems are stated
  against a hand-written Lean spec "not against the extracted hacspec at all".
  That is wrong. `Spec/HacspecBridge.lean` exists precisely to close that gap --
  its own header says "so the extracted spec, not the hand spec, is the trusted
  reference" -- and there are six impl-to-extracted-hacspec results:

      poly_add_hacspec_fc / poly_sub_hacspec_fc / poly_pointwise_mul_hacspec_fc
      ntt_hacspec_fc / intt_hacspec_fc / infinity_norm_exceeds_hacspec_fc

  covering `hacspec_ml_dsa.{polynomial.poly_*, ntt.*, arithmetic.coeff_norm}`.
  Each composes an impl FC (impl = hand spec, through `lift_poly`) with a bridge
  (hand spec = extracted spec).

  What is genuinely NOT bridged is the ROUNDING layer -- and not because the
  hacspec lacks it: `specs/ml-dsa/src/arithmetic.rs` has `mod_q`, `mod_pm`,
  `power2round`, `decompose`, `high_bits`, `low_bits`, `make_hint`, `use_hint`,
  `coeff_norm`, and `Spec/Rounding.lean` describes itself as a "faithful
  translation" of exactly that file. The bridge for it simply had not been built.
  `decompose_element` below now starts it.

  ## Naming the hacspec from Rust: where it works and where it does not

  At the SCALAR layer it just works, and `decompose_element` now does it: both
  sides are plain `i32`, so the `#[ensures]` names
  `hacspec_ml_dsa::arithmetic::decompose` directly and the generated `post` is
  full functional correctness. This needed the hacspec's `arithmetic` module and
  its nine functions to become `pub` (libcrux@24115c32 + follow-up), plus the
  spec crate's hax-lib pinned to libcrux-iot's rev so charon does not emit a
  second `hax_lib_1`.

  At the POLY layer it does not, yet, and the obstacle is not the lifting
  function -- that now exists in Rust too, as
  `simd::portable::arithmetic::lift_poly_res`, the counterpart of
  `Spec.HacspecBridge.lift_poly_res` (it regathers the 32x8 SIMD layout into a
  flat `[i32; 256]` and canonicalises with the hacspec's own `mod_q`). The
  obstacle is GENERICITY: `PolynomialRingElement::{add,subtract}` and the NTT
  entry points are generic over `SIMDUnit: Operations`, the lift needs concrete
  lane access (`values`, `pub(super)`), and the trait's own `to_coefficient_array`
  is an out-param function so it cannot appear in an `ensures` expression.
  Attaching it needs either a monomorphic wrapper on the impl side or a pure lane
  accessor on the trait. Note also that a generic function's generated `.spec` is
  itself generic over the instance, while the FC theorems hold only for
  `portable_ops_inst`, so even then the discharge would have to be stated at the
  instantiated spec.

  ## The original diagnosis (retained, because it is what drove the change)

  Not one of the six can be proved from its existing theorem, and the reason is
  worth stating precisely, because it is a real mismatch between the Rust
  annotations and the Lean development rather than a proof-engineering nuisance.

  (1) THE ANNOTATION IS WEAKER THAN THE PROOF'S DOMAIN.
      `compute_one_hint` and `compute_hint` are annotated
      `requires(gamma2 != i32::MIN)` -- just enough for `-gamma2` not to overflow.
      Their Lean theorems assume `gamma2 ∈ {95232, 261888}`, the two FIPS-204
      values, because the functional postcondition is stated against
      `Spec.Rounding.computeHint`, which is only meaningful there. So the
      generated obligation claims MORE than we proved: panic-freedom for every
      `gamma2` except `i32::MIN`.

  (2) THE ANNOTATION OMITS INPUT-RANGE PRECONDITIONS THE PROOF NEEDS.
      `decompose_element`, `decompose`, `use_one_hint` and `use_hint` are
      annotated only with `gamma2 ∈ {GAMMA2_V95_232, GAMMA2_V261_888}`. Their Lean
      theorems additionally assume the coefficients lie in `[-q, q)` and, for the
      hint functions, that each hint is `0` or `1`. The Rust says nothing about
      either, so again the generated obligation is the stronger statement.

  In both cases the generated spec is STRICTLY STRONGER than the theorem, so no
  amount of post-weakening closes the gap -- it would take either a genuinely more
  general panic-freedom argument, or a strengthening of the Rust annotations to
  match the domain that was actually verified. That is a decision about the Rust,
  not about the proofs, so it is surfaced here rather than papered over with a
  `sorry`.

  ## What this file does prove

  All six generated specs are discharged unconditionally from the existing
  correctness proofs in `Vector/Portable/Rounding.lean`.

  `compute_one_hint` is the most informative case: it is the one ML-DSA function
  with an `#[ensures]`, so its generated `post` is a real property
  (`0 <= out <= 1`) rather than `True` -- and that post IS delivered by the
  existing theorem, which proves `r.val in {0, 1}`.

  The remaining two generated specs, `get_n_least_significant_bits` and
  `shift_left_then_reduce`, have no correctness theorem in the tree at all and are
  left untouched.
-/
import LibcruxIotMlDsa.Extraction
import LibcruxIotMlDsa.Vector.Portable.Rounding
import LibcruxIotMlDsa.Spec.HacspecBridge
import LibcruxIotMlDsa.Spec.RoundingBridge
import LibcruxIotMlDsa.Vector.Portable.Arithmetic

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_ml_dsa.Verification

/-! ## Bridges -/

/-- A Triple with a `⌜True⌝` post says exactly "this computation does not fail
    and does not diverge", so any stronger post implies it. -/
private theorem triple_true_of_triple {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ True ⌝ ⦄ := by
  match hx : x with
  | .ok v => simp [Std.Do.Triple, WP.wp, PredTrans.apply]
  | .fail e =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-- `<fn>.pre` is a `RustM Bool` while `RustM.holds` wants a `RustM Prop`, so the
    generated `.spec` inserts a `(· = true) <$> ·`; on an `ok` that collapses. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Converse of `bool_of_holds_map_ok`: build a generated `post`'s `.holds` from
    the plain boolean fact. -/
private theorem holds_map_ok_of_bool {b : Bool} (h : b = true) :
    RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool)) := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap]
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Triple from an `ok` equation plus the post fact. -/
private theorem triple_of_ok {α : Type} {x : RustM α} {v : α}
    {P : α → Prop} (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

/-- Triple to existential (stated with `x` a variable so the `match` substitutes). -/
private theorem triple_exists_ok {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'; exact h'
  | .fail e =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-! ### Decoding the unrolled lane conjunctions

    `decompose` and `use_hint` are annotated with the spec-only boolean helpers
    `coefficients_in_field` / `coefficients_are_hints`, so the per-lane bounds
    their theorems need now come OUT OF the generated `pre` instead of being
    supplied by hand.

    Those helpers are written in Rust as an explicit eight-way conjunction over
    constant indices rather than as `hax_lib::forall(|i| implies(i < 8, ...))`.
    `arithmetic.rs` carries the full note; the two reasons, both established by
    experiment, are:

    1. a bool `&&` inside a quantifier closure makes aeneas fail outright
       (`interp/Interp.ml, line 609`) -- a Prop-level `&` on `.to_prop()`s does
       not, so short-circuiting `&&` in a `Prop` closure is the trigger;

    2. even with `&`, the resulting precondition is UNSATISFIABLE, which would
       make `<fn>.spec` VACUOUS rather than fail loudly. `hax_lib::prop::forall`
       is modelled (`CoreModels/HaxLib/Prop.lean`) as

         ok (∀ t : T, Result.holds (do let u <- fn.call f t; inst.into u))

       i.e. it ranges over ALL of `Usize`, while the extracted closure body
       evaluates `Array.index_usize simd_unit.values i` BEFORE the `i < 8` guard.
       Out of range that index is `fail .panic`, `Result.holds` of a failing
       computation is `False`, and so the whole `forall` is `False`.

    The unrolled form has neither problem: its `&&`s sit in an ordinary function
    rather than a `Prop` closure, and every index is in range. -/

/-- Like `bool_of_holds_map_ok`, but for a `pre` that is not syntactically an
    `ok` -- here it is a nested-`if` computation. -/
private theorem eq_ok_true_of_holds_map {x : RustM Bool}
    (h : RustM.holds ((fun a => a = true) <$> x)) : x = .ok true := by
  cases x with
  | ok b => rw [bool_of_holds_map_ok h]
  | fail e =>
      exfalso
      have hm : ((fun a => a = true) <$> (RustM.fail e : RustM Bool))
          = (RustM.fail e : RustM Prop) := rfl
      rw [hm] at h
      simp [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] at h
  | div =>
      exfalso
      have hm : ((fun a => a = true) <$> (RustM.div : RustM Bool))
          = (RustM.div : RustM Prop) := rfl
      rw [hm] at h
      simp [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] at h

/-- An in-range `Array.index_usize` as a plain equation, so the unrolled
    conjunction can be rewritten index by index. -/
private theorem array_index_ok {alpha : Type} [Inhabited alpha] {n : Std.Usize}
    (v : Aeneas.Std.Array alpha n) (i : Std.Usize) (h : i.val < v.val.length) :
    v.index_usize i = .ok (v.val[i.val]!) := by
  unfold Aeneas.Std.Array.index_usize
  rw [Aeneas.Std.Array.getElem?_Usize_eq, List.getElem?_eq_getElem h,
    List.getElem!_eq_getElem?_getD, List.getElem?_eq_getElem h]
  rfl

/-- One link of the unrolled conjunction: `&&` extracts to
    `if b then rest else false`, so a `true` result forces both sides. -/
private theorem bind_if_ok_true {x rest : RustM Bool}
    (h : (do let b ← x; if b then rest else RustM.ok false) = RustM.ok true) :
    x = .ok true ∧ rest = .ok true := by
  cases x with
  | ok b =>
      cases b with
      | true => exact ⟨rfl, by simpa using h⟩
      | false => exfalso; simp at h
  | fail e => exfalso; simp at h
  | div => exfalso; simp at h

/-- `lane_in_field x = ok true` decoded. The `-FIELD_MODULUS` bound arrives as a
    CHECKED negation (`-. FIELD_MODULUS`, a `RustM I32`) and is resolved first. -/
private theorem lane_in_field_true {x : Std.I32}
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field x = .ok true) :
    -(8380417 : Int) ≤ x.val ∧ x.val < (8380417 : Int) := by
  have hneg : (-. libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS : RustM Std.I32)
      = .ok (-8380417)#i32 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
    first | rfl | decide
  have hFM : (libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS).val = 8380417 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field, hneg,
    Aeneas.Std.bind_tc_ok] at h
  by_cases h1 : x ≥ (-8380417)#i32
  · by_cases h2 : x < libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS
    · exact ⟨by scalar_tac, by scalar_tac⟩
    · exfalso; rw [if_pos h1] at h; simp [h2] at h
  · exfalso; rw [if_neg h1] at h; simp at h

/-- `lane_is_hint x = ok true` decoded. -/
private theorem lane_is_hint_true {x : Std.I32}
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint x = .ok true) :
    x.val = 0 ∨ x.val = 1 := by
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint] at h
  by_cases h1 : x = 0#i32
  · exact Or.inl (by scalar_tac)
  · rw [if_neg h1] at h
    have hx : x = 1#i32 := by simpa using h
    exact Or.inr (by scalar_tac)

/-- All eight lanes of `coefficients_in_field` pass. -/
private theorem coefficients_in_field_lanes
    (c : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field c = .ok true) :
    ∀ j : Nat, j < 8 → libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field (c.values.val[j]!) = .ok true := by
  have hlen : c.values.val.length = 8 := c.values.property
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field,
    array_index_ok c.values 0#usize (by simp [hlen]),
    array_index_ok c.values 1#usize (by simp [hlen]),
    array_index_ok c.values 2#usize (by simp [hlen]),
    array_index_ok c.values 3#usize (by simp [hlen]),
    array_index_ok c.values 4#usize (by simp [hlen]),
    array_index_ok c.values 5#usize (by simp [hlen]),
    array_index_ok c.values 6#usize (by simp [hlen]),
    array_index_ok c.values 7#usize (by simp [hlen]),
    Aeneas.Std.bind_tc_ok] at h
  obtain ⟨h0, h⟩ := bind_if_ok_true h
  obtain ⟨h1, h⟩ := bind_if_ok_true h
  obtain ⟨h2, h⟩ := bind_if_ok_true h
  obtain ⟨h3, h⟩ := bind_if_ok_true h
  obtain ⟨h4, h⟩ := bind_if_ok_true h
  obtain ⟨h5, h⟩ := bind_if_ok_true h
  obtain ⟨h6, h7⟩ := bind_if_ok_true h
  intro j hj
  -- `interval_cases` is a Mathlib tactic and is not imported here; peel the
  -- eight literals off by hand. Each `exact` closes up to `(k#usize).val = k`.
  rcases j with _ | _ | _ | _ | _ | _ | _ | _ | j
  · exact h0
  · exact h1
  · exact h2
  · exact h3
  · exact h4
  · exact h5
  · exact h6
  · exact h7
  · exact absurd hj (by omega)

/-- All eight lanes of `coefficients_are_hints` pass. -/
private theorem coefficients_are_hints_lanes
    (c : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints c = .ok true) :
    ∀ j : Nat, j < 8 → libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint (c.values.val[j]!) = .ok true := by
  have hlen : c.values.val.length = 8 := c.values.property
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints,
    array_index_ok c.values 0#usize (by simp [hlen]),
    array_index_ok c.values 1#usize (by simp [hlen]),
    array_index_ok c.values 2#usize (by simp [hlen]),
    array_index_ok c.values 3#usize (by simp [hlen]),
    array_index_ok c.values 4#usize (by simp [hlen]),
    array_index_ok c.values 5#usize (by simp [hlen]),
    array_index_ok c.values 6#usize (by simp [hlen]),
    array_index_ok c.values 7#usize (by simp [hlen]),
    Aeneas.Std.bind_tc_ok] at h
  obtain ⟨h0, h⟩ := bind_if_ok_true h
  obtain ⟨h1, h⟩ := bind_if_ok_true h
  obtain ⟨h2, h⟩ := bind_if_ok_true h
  obtain ⟨h3, h⟩ := bind_if_ok_true h
  obtain ⟨h4, h⟩ := bind_if_ok_true h
  obtain ⟨h5, h⟩ := bind_if_ok_true h
  obtain ⟨h6, h7⟩ := bind_if_ok_true h
  intro j hj
  -- `interval_cases` is a Mathlib tactic and is not imported here; peel the
  -- eight literals off by hand. Each `exact` closes up to `(k#usize).val = k`.
  rcases j with _ | _ | _ | _ | _ | _ | _ | _ | j
  · exact h0
  · exact h1
  · exact h2
  · exact h3
  · exact h4
  · exact h5
  · exact h6
  · exact h7
  · exact absurd hj (by omega)

/-! ### Lifting the scalar hacspec post to a whole SIMD unit

    `decompose_element`'s `#[ensures]` is per-lane. `decompose`'s is the same
    statement over all eight lanes, via the spec-only `decompose_unit_ok`. These
    two lemmas BUILD that conjunction (the earlier `coefficients_in_field_lanes`
    decodes one, in the other direction). -/

/-- `declassify` is the identity (Assumptions/FunsExternal). -/
private theorem decl_eq {T : Type} (a : T) : libcrux_secrets.traits.Declassify.Blanket.declassify a = .ok a := rfl

/-- One lane of `decompose_unit_ok`, from the FC theorem's per-lane post. -/
private theorem decompose_lane_ok_of (gamma2 sv lo hi : Std.I32)
    (hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
    (hb_lo : -(8380417 : Int) ≤ sv.val) (hb_hi : sv.val < (8380417 : Int))
    (hlo_eq : lo.val = (libcrux_iot_ml_dsa.Spec.Rounding.decompose sv.val gamma2.val).2)
    (hhi_eq : hi.val = (libcrux_iot_ml_dsa.Spec.Rounding.decompose sv.val gamma2.val).1) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_lane_ok gamma2 sv lo hi = .ok true := by
  -- the `sv as i64` cast, then `mod_q` for the canonical residue
  have hcb : Aeneas.Std.IScalar.min .I64 ≤ sv.val ∧ sv.val ≤ Aeneas.Std.IScalar.max .I64 := by
    simp only [Aeneas.Std.IScalar.min_IScalarTy_I64_eq,
      Aeneas.Std.IScalar.max_IScalarTy_I64_eq, Aeneas.Std.I64.min, Aeneas.Std.I64.max,
      Aeneas.Std.I64.numBits, Aeneas.Std.IScalarTy.I64_numBits_eq]
    omega
  obtain ⟨c, hc_eq, hc_val⟩ :=
    Aeneas.Std.WP.spec_imp_exists (Aeneas.Std.IScalar.cast_inBounds_spec .I64 sv hcb)
  obtain ⟨rc, hrc_eq, hrc_zq, hrc_lo, hrc_hi⟩ :=
    libcrux_iot_ml_dsa.Spec.HacspecBridge.mod_q_eq c
  have hrc_hi' : rc.val < 8380417 := by
    have : (libcrux_iot_ml_dsa.Spec.Parameters.Q : Int) = 8380417 := by
      norm_num [libcrux_iot_ml_dsa.Spec.Parameters.Q]
    omega
  obtain ⟨r1, r0, hd_eq, hr1_val, hr0_val⟩ := libcrux_iot_ml_dsa.Spec.RoundingBridge.decompose_eq rc gamma2 hrc_lo hrc_hi' hg
  have hsame : libcrux_iot_ml_dsa.Spec.Rounding.decompose rc.val gamma2.val = libcrux_iot_ml_dsa.Spec.Rounding.decompose sv.val gamma2.val := by
    refine libcrux_iot_ml_dsa.Spec.RoundingBridge.decompose_canonical sv rc gamma2 ?_ hrc_lo hrc_hi'
    rw [hrc_zq, hc_val]
  rw [hsame] at hr1_val hr0_val
  have hlo' : lo = r0 := Aeneas.Std.IScalar.eq_of_val_eq (by rw [hlo_eq, hr0_val])
  have hhi' : hi = r1 := Aeneas.Std.IScalar.eq_of_val_eq (by rw [hhi_eq, hr1_val])
  -- one `simp`, because the `let (i4, i5) := s` rebinds and blocks `rw`
  simp [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_lane_ok, decl_eq, hc_eq, hrc_eq, hd_eq, hlo', hhi']

/-- All eight lanes, assembled into `decompose_unit_ok`. -/
private theorem decompose_unit_ok_of (gamma2 : Std.I32) (u low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
    (hbound : ∀ j : Nat, j < 8 →
        -(8380417 : Int) ≤ (u.values.val[j]!).val
          ∧ (u.values.val[j]!).val < (8380417 : Int))
    (hlanes : ∀ j : Nat, j < 8 →
        (low.values.val[j]!).val = (libcrux_iot_ml_dsa.Spec.Rounding.decompose (u.values.val[j]!).val gamma2.val).2
        ∧ (high.values.val[j]!).val = (libcrux_iot_ml_dsa.Spec.Rounding.decompose (u.values.val[j]!).val gamma2.val).1) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_unit_ok gamma2 u low high = .ok true := by
  have hlen_u : u.values.val.length = 8 := u.values.property
  have hlen_low : low.values.val.length = 8 := low.values.property
  have hlen_high : high.values.val.length = 8 := high.values.property
  have h0 := decompose_lane_ok_of gamma2 (u.values.val[0]!) (low.values.val[0]!)
    (high.values.val[0]!) hg (hbound 0 (by omega)).1 (hbound 0 (by omega)).2
    (hlanes 0 (by omega)).1 (hlanes 0 (by omega)).2
  have h1 := decompose_lane_ok_of gamma2 (u.values.val[1]!) (low.values.val[1]!)
    (high.values.val[1]!) hg (hbound 1 (by omega)).1 (hbound 1 (by omega)).2
    (hlanes 1 (by omega)).1 (hlanes 1 (by omega)).2
  have h2 := decompose_lane_ok_of gamma2 (u.values.val[2]!) (low.values.val[2]!)
    (high.values.val[2]!) hg (hbound 2 (by omega)).1 (hbound 2 (by omega)).2
    (hlanes 2 (by omega)).1 (hlanes 2 (by omega)).2
  have h3 := decompose_lane_ok_of gamma2 (u.values.val[3]!) (low.values.val[3]!)
    (high.values.val[3]!) hg (hbound 3 (by omega)).1 (hbound 3 (by omega)).2
    (hlanes 3 (by omega)).1 (hlanes 3 (by omega)).2
  have h4 := decompose_lane_ok_of gamma2 (u.values.val[4]!) (low.values.val[4]!)
    (high.values.val[4]!) hg (hbound 4 (by omega)).1 (hbound 4 (by omega)).2
    (hlanes 4 (by omega)).1 (hlanes 4 (by omega)).2
  have h5 := decompose_lane_ok_of gamma2 (u.values.val[5]!) (low.values.val[5]!)
    (high.values.val[5]!) hg (hbound 5 (by omega)).1 (hbound 5 (by omega)).2
    (hlanes 5 (by omega)).1 (hlanes 5 (by omega)).2
  have h6 := decompose_lane_ok_of gamma2 (u.values.val[6]!) (low.values.val[6]!)
    (high.values.val[6]!) hg (hbound 6 (by omega)).1 (hbound 6 (by omega)).2
    (hlanes 6 (by omega)).1 (hlanes 6 (by omega)).2
  have h7 := decompose_lane_ok_of gamma2 (u.values.val[7]!) (low.values.val[7]!)
    (high.values.val[7]!) hg (hbound 7 (by omega)).1 (hbound 7 (by omega)).2
    (hlanes 7 (by omega)).1 (hlanes 7 (by omega)).2
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_unit_ok,
    array_index_ok u.values 0#usize (by simp [hlen_u]),
    array_index_ok low.values 0#usize (by simp [hlen_low]),
    array_index_ok high.values 0#usize (by simp [hlen_high]),
    array_index_ok u.values 1#usize (by simp [hlen_u]),
    array_index_ok low.values 1#usize (by simp [hlen_low]),
    array_index_ok high.values 1#usize (by simp [hlen_high]),
    array_index_ok u.values 2#usize (by simp [hlen_u]),
    array_index_ok low.values 2#usize (by simp [hlen_low]),
    array_index_ok high.values 2#usize (by simp [hlen_high]),
    array_index_ok u.values 3#usize (by simp [hlen_u]),
    array_index_ok low.values 3#usize (by simp [hlen_low]),
    array_index_ok high.values 3#usize (by simp [hlen_high]),
    array_index_ok u.values 4#usize (by simp [hlen_u]),
    array_index_ok low.values 4#usize (by simp [hlen_low]),
    array_index_ok high.values 4#usize (by simp [hlen_high]),
    array_index_ok u.values 5#usize (by simp [hlen_u]),
    array_index_ok low.values 5#usize (by simp [hlen_low]),
    array_index_ok high.values 5#usize (by simp [hlen_high]),
    array_index_ok u.values 6#usize (by simp [hlen_u]),
    array_index_ok low.values 6#usize (by simp [hlen_low]),
    array_index_ok high.values 6#usize (by simp [hlen_high]),
    array_index_ok u.values 7#usize (by simp [hlen_u]),
    array_index_ok low.values 7#usize (by simp [hlen_low]),
    array_index_ok high.values 7#usize (by simp [hlen_high]),
    h0,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    h7, Aeneas.Std.bind_tc_ok, reduceIte,
    show ((0#usize : Std.Usize)).val = 0 from rfl,
    show ((1#usize : Std.Usize)).val = 1 from rfl,
    show ((2#usize : Std.Usize)).val = 2 from rfl,
    show ((3#usize : Std.Usize)).val = 3 from rfl,
    show ((4#usize : Std.Usize)).val = 4 from rfl,
    show ((5#usize : Std.Usize)).val = 5 from rfl,
    show ((6#usize : Std.Usize)).val = 6 from rfl,
    show ((7#usize : Std.Usize)).val = 7 from rfl]

/-! ## The `gamma2 ∈ {95232, 261888}` group

    Here the generated `pre` delivers exactly the theorems' `hg`; what has to be
    supplied on the side is the input-range information the Rust omits. -/

/-- **`power2round_element`: full functional correctness against the extracted
    hacspec.** Same shape as `decompose_element` below, and simpler -- the
    hacspec's `power2round` has no `gamma2` and no `Q - 1` boundary branch.

    The `#[requires]` also makes good on the `// XXX: ... should be a
    precondition for hax instead` note that sat next to a commented-out
    `debug_assert!` in `arithmetic.rs` (hax issue 1082). -/
theorem power2round_element_spec_proof (t : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.power2round_element.spec t := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.power2round_element.pre] at hok
  have hr : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field t = .ok true := hok
  obtain ⟨hlo, hhi⟩ := lane_in_field_true hr
  -- the impl result, and its agreement with the HAND spec
  obtain ⟨p, hp_eq, hp_lo, hp_hi⟩ :=
    triple_exists_ok
      (Vector.Portable.Arithmetic.power2round_element_spec t
        (by simp only [libcrux_iot_ml_dsa.Spec.Rounding.Qi]; norm_num [Spec.Parameters.Q]; omega)
        (by simp only [libcrux_iot_ml_dsa.Spec.Rounding.Qi]; norm_num [Spec.Parameters.Q]; omega))
  obtain ⟨plo, phi⟩ := p
  dsimp only at hp_lo hp_hi
  refine triple_of_ok hp_eq ?_
  -- the `t as i64` cast, then `mod_q` for the canonical residue
  have hcb : Aeneas.Std.IScalar.min .I64 ≤ t.val ∧ t.val ≤ Aeneas.Std.IScalar.max .I64 := by
    simp only [Aeneas.Std.IScalar.min_IScalarTy_I64_eq,
      Aeneas.Std.IScalar.max_IScalarTy_I64_eq, Aeneas.Std.I64.min, Aeneas.Std.I64.max,
      Aeneas.Std.I64.numBits, Aeneas.Std.IScalarTy.I64_numBits_eq]
    omega
  obtain ⟨c, hc_eq, hc_val⟩ :=
    Aeneas.Std.WP.spec_imp_exists (Aeneas.Std.IScalar.cast_inBounds_spec .I64 t hcb)
  obtain ⟨rc, hrc_eq, hrc_zq, hrc_lo, hrc_hi⟩ :=
    libcrux_iot_ml_dsa.Spec.HacspecBridge.mod_q_eq c
  have hrc_hi' : rc.val < 8380417 := by
    have : (libcrux_iot_ml_dsa.Spec.Parameters.Q : Int) = 8380417 := by
      norm_num [libcrux_iot_ml_dsa.Spec.Parameters.Q]
    omega
  -- the extracted hacspec agrees with the hand spec on it
  obtain ⟨r1, r0, hd_eq, hr1_val, hr0_val⟩ := libcrux_iot_ml_dsa.Spec.RoundingBridge.power2round_eq rc hrc_lo hrc_hi'
  have hsame : libcrux_iot_ml_dsa.Spec.Rounding.power2round rc.val
      = libcrux_iot_ml_dsa.Spec.Rounding.power2round t.val := by
    refine libcrux_iot_ml_dsa.Spec.RoundingBridge.power2round_canonical t rc ?_ hrc_lo hrc_hi'
    rw [hrc_zq, hc_val]
  rw [hsame] at hr1_val hr0_val
  have hlo' : plo = r0 := by
    apply Aeneas.Std.IScalar.eq_of_val_eq; rw [hp_lo, hr0_val]
  have hhi' : phi = r1 := by
    apply Aeneas.Std.IScalar.eq_of_val_eq; rw [hp_hi, hr1_val]
  have hpost : libcrux_iot_ml_dsa.simd.portable.arithmetic.power2round_element.post t (plo, phi) = .ok true := by
    simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.power2round_element.post, hc_eq, Aeneas.Std.bind_tc_ok, hrc_eq, hd_eq]
    simp [hlo', hhi']
  rw [hpost]
  exact holds_map_ok_of_bool rfl

/-- **Full functional correctness against the extracted hacspec.**

    `decompose_element`'s `#[ensures]` now names the machine-extracted FIPS-204
    spec directly:

      out.0 == hacspec_ml_dsa::arithmetic::decompose(mod_q(r as i64), gamma2).1
      && out.1 == hacspec_ml_dsa::arithmetic::decompose(mod_q(r as i64), gamma2).0

    so the generated `post` is no longer `True` -- it says the impl computes
    FIPS-204 Decompose. No lifting function is needed at this layer: both sides
    are plain `i32`, exactly as sha3's two sides were both `[u8; N]`. (The
    conjuncts are crossed because the impl returns `(low, high)` while the spec
    returns `(r1, r0)`, and `r` is canonicalised with the hacspec's own `mod_q`
    because `decompose` is specified for `r` in `[0, Q)`.)

    Both halves of the spec-side reasoning are now PROVED, in the new
    `Spec/RoundingBridge.lean`:

      RoundingBridge.decompose_eq         -- extracted hacspec `decompose`
                                          -- = hand spec `Spec.Rounding.decompose`
      RoundingBridge.decompose_canonical  -- the hand spec only reads `r` through
                                          -- its canonical residue

    together with the already-proved `Spec.HacspecBridge.mod_q_eq` for the
    canonicalisation step. So this discharges with no side hypotheses at all. -/
theorem decompose_element_spec_proof (gamma2 r : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.spec gamma2 r := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ -(8380417 : Int) ≤ r.val ∧ r.val < (8380417 : Int) := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      have hr : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field r = .ok true := hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1),
        (lane_in_field_true hr).1, (lane_in_field_true hr).2⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        have hr : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field r = .ok true := hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5),
          (lane_in_field_true hr).1, (lane_in_field_true hr).2⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  -- the impl result, and its agreement with the HAND spec
  obtain ⟨p, hp_eq, hp_lo, hp_hi⟩ :=
    triple_exists_ok
      (Vector.Portable.Rounding.decompose_element_spec gamma2 r key.1 key.2.1 key.2.2)
  obtain ⟨plo, phi⟩ := p
  dsimp only at hp_lo hp_hi
  refine triple_of_ok hp_eq ?_
  -- the `r as i64` cast is in range
  have hcb : Aeneas.Std.IScalar.min .I64 ≤ r.val ∧ r.val ≤ Aeneas.Std.IScalar.max .I64 := by
    simp only [Aeneas.Std.IScalar.min_IScalarTy_I64_eq,
      Aeneas.Std.IScalar.max_IScalarTy_I64_eq, Aeneas.Std.I64.min, Aeneas.Std.I64.max,
      Aeneas.Std.I64.numBits, Aeneas.Std.IScalarTy.I64_numBits_eq]
    omega
  obtain ⟨c, hc_eq, hc_val⟩ :=
    Aeneas.Std.WP.spec_imp_exists (Aeneas.Std.IScalar.cast_inBounds_spec .I64 r hcb)
  -- `mod_q` gives the canonical residue (already proved upstream)
  obtain ⟨rc, hrc_eq, hrc_zq, hrc_lo, hrc_hi⟩ :=
    libcrux_iot_ml_dsa.Spec.HacspecBridge.mod_q_eq c
  have hrc_hi' : rc.val < 8380417 := by
    have : (libcrux_iot_ml_dsa.Spec.Parameters.Q : Int) = 8380417 := by
      norm_num [libcrux_iot_ml_dsa.Spec.Parameters.Q]
    omega
  -- ... so the hacspec `decompose` agrees with the hand spec on it
  obtain ⟨r1, r0, hd_eq, hr1_val, hr0_val⟩ :=
    libcrux_iot_ml_dsa.Spec.RoundingBridge.decompose_eq rc gamma2 hrc_lo hrc_hi' key.1
  have hsame : libcrux_iot_ml_dsa.Spec.Rounding.decompose rc.val gamma2.val
      = libcrux_iot_ml_dsa.Spec.Rounding.decompose r.val gamma2.val := by
    refine libcrux_iot_ml_dsa.Spec.RoundingBridge.decompose_canonical r rc gamma2 ?_ hrc_lo hrc_hi'
    rw [hrc_zq, hc_val]
  rw [hsame] at hr1_val hr0_val
  -- assemble the generated post
  have hlo : plo = r0 := by
    apply Aeneas.Std.IScalar.eq_of_val_eq; rw [hp_lo, hr0_val]
  have hhi : phi = r1 := by
    apply Aeneas.Std.IScalar.eq_of_val_eq; rw [hp_hi, hr1_val]
  have hpost : libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.post
      gamma2 r (plo, phi) = .ok true := by
    simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.post, hc_eq,
      Aeneas.Std.bind_tc_ok, hrc_eq, hd_eq]
    simp [hlo, hhi]
  rw [hpost]
  exact holds_map_ok_of_bool rfl

/-- Discharged OUTRIGHT: the `#[requires]` now states the `[-q, q)` range for `r`
    and `hint in {0, 1}` as well as pinning `gamma2`, so every hypothesis of
    `use_one_hint_spec` comes out of the generated `pre`.

    The decode is longhand because hax compiles `(a || b) && c && d && (e || f)`
    into nested `if`s with the `c && d` block DUPLICATED under each disjunct, and
    the `-FIELD_MODULUS` bound arrives as a CHECKED negation
    (`-. FIELD_MODULUS`, a `RustM I32`) that has to be resolved first. -/
theorem use_one_hint_spec_proof (gamma2 r hint : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.spec gamma2 r hint := by
  intro hpre
  have hFM : (libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS).val = 8380417 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
  have hneg : (-. libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS : RustM Std.I32)
      = .ok (-8380417)#i32 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
    first | rfl | decide
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.pre, hneg,
    Aeneas.Std.bind_tc_ok] at hpre
  have key : (-(8380417 : Int) ≤ r.val ∧ r.val < 8380417)
      ∧ (hint.val = 0 ∨ hint.val = 1) := by
    by_cases h2 : r ≥ (-8380417)#i32
    · by_cases h3 : r < libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS
      · refine ⟨⟨by scalar_tac, by scalar_tac⟩, ?_⟩
        by_cases h4 : hint = 0#i32
        · exact Or.inl (by scalar_tac)
        · exact Or.inr (by
            by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
            · rw [if_pos h1, if_pos h2, if_pos h3, if_neg h4] at hpre
              have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac
            · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
              · rw [if_neg h1, if_pos h5, if_pos h2, if_pos h3, if_neg h4] at hpre
                have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac
              · rw [if_neg h1, if_neg h5] at hpre
                exact absurd (bool_of_holds_map_ok hpre) (by simp))
      · exfalso
        by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
        · rw [if_pos h1, if_pos h2, if_neg h3] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
        · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
          · rw [if_neg h1, if_pos h5, if_pos h2, if_neg h3] at hpre
            exact absurd (bool_of_holds_map_ok hpre) (by simp)
          · rw [if_neg h1, if_neg h5] at hpre
            exact absurd (bool_of_holds_map_ok hpre) (by simp)
    · exfalso
      by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
      · rw [if_pos h1, if_neg h2] at hpre
        exact absurd (bool_of_holds_map_ok hpre) (by simp)
      · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
        · rw [if_neg h1, if_pos h5, if_neg h2] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
        · rw [if_neg h1, if_neg h5] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · exact Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5)
      · rw [if_neg h1, if_neg h5] at hpre
        exact absurd (bool_of_holds_map_ok hpre) (by simp)
  -- the impl result, and its agreement with the HAND spec
  obtain ⟨z, hz_eq, hz_val⟩ :=
    triple_exists_ok
      (Vector.Portable.Rounding.use_one_hint_spec gamma2 r hint hg key.1.1 key.1.2 key.2)
  refine triple_of_ok hz_eq ?_
  -- the `r as i64` cast, then `mod_q` for the canonical residue
  have hcb : Aeneas.Std.IScalar.min .I64 ≤ r.val ∧ r.val ≤ Aeneas.Std.IScalar.max .I64 := by
    simp only [Aeneas.Std.IScalar.min_IScalarTy_I64_eq,
      Aeneas.Std.IScalar.max_IScalarTy_I64_eq, Aeneas.Std.I64.min, Aeneas.Std.I64.max,
      Aeneas.Std.I64.numBits, Aeneas.Std.IScalarTy.I64_numBits_eq]
    have := key.1.1; have := key.1.2; omega
  obtain ⟨c, hc_eq, hc_val⟩ :=
    Aeneas.Std.WP.spec_imp_exists (Aeneas.Std.IScalar.cast_inBounds_spec .I64 r hcb)
  obtain ⟨rc, hrc_eq, hrc_zq, hrc_lo, hrc_hi⟩ :=
    libcrux_iot_ml_dsa.Spec.HacspecBridge.mod_q_eq c
  have hrc_hi' : rc.val < 8380417 := by
    have : (libcrux_iot_ml_dsa.Spec.Parameters.Q : Int) = 8380417 := by
      norm_num [libcrux_iot_ml_dsa.Spec.Parameters.Q]
    omega
  -- the extracted hacspec `use_hint` agrees with the hand spec on it
  obtain ⟨w, hw_eq, hw_val⟩ :=
    libcrux_iot_ml_dsa.Spec.RoundingBridge.use_hint_eq (decide (hint = 1#i32)) rc gamma2 hrc_lo hrc_hi' hg
  have hsame : libcrux_iot_ml_dsa.Spec.Rounding.useHint (decide (hint = 1#i32)) rc.val gamma2.val
      = libcrux_iot_ml_dsa.Spec.Rounding.useHint (decide (hint = 1#i32)) r.val gamma2.val := by
    refine libcrux_iot_ml_dsa.Spec.RoundingBridge.useHint_canonical _ r rc gamma2 ?_ hrc_lo hrc_hi'
    rw [hrc_zq, hc_val]
  rw [hsame] at hw_val
  -- the two Bool spellings of "the hint is set" agree
  have hbool : (decide (hint = 1#i32)) = ((hint.val == 1) : Bool) := by
    by_cases h : hint.val = 1
    · rw [decide_eq_true (Aeneas.Std.IScalar.eq_of_val_eq (by rw [h]; decide))]
      simp [h]
    · rw [decide_eq_false (fun hc => h (by rw [hc]; decide))]
      simp [h]
  rw [hbool] at hw_val
  have hzw : z = w := by
    apply Aeneas.Std.IScalar.eq_of_val_eq; rw [hz_val, hw_val]
  have hpost : libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.post gamma2 r hint z = .ok true := by
    simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.post, hc_eq, Aeneas.Std.bind_tc_ok, hrc_eq, hw_eq]
    simp [hzw]
  rw [hpost]
  exact holds_map_ok_of_bool rfl

/-- Discharged OUTRIGHT. The `#[requires]` now carries the per-lane
    `[-q, q)` bound via `coefficients_in_field`, so `decompose_spec`'s `hbound`
    comes out of the generated `pre`. -/
theorem decompose_spec_proof (gamma2 : Std.I32)
    (simd_unit low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.spec gamma2 simd_unit low high := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field simd_unit = .ok true := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1), hok⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5), hok⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  have hbound : ∀ j : Nat, j < 8 →
      -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
        ∧ (simd_unit.values.val[j]!).val < (8380417 : Int) :=
    fun j hj => lane_in_field_true
      (coefficients_in_field_lanes simd_unit key.2 j hj)
  -- the impl result, and its per-lane agreement with the HAND spec
  obtain ⟨p, hp_eq, hp⟩ :=
    triple_exists_ok
      (Vector.Portable.Rounding.decompose_spec gamma2 simd_unit low high key.1 hbound)
  obtain ⟨plow, phigh⟩ := p
  dsimp only at hp
  refine triple_of_ok hp_eq ?_
  have hpost : libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.post gamma2 simd_unit low high (plow, phigh) = .ok true := by
    simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.post]
    exact decompose_unit_ok_of gamma2 simd_unit plow phigh key.1 hbound hp
  rw [hpost]
  exact holds_map_ok_of_bool rfl

/-- Discharged OUTRIGHT. `use_hint`'s `#[requires]` carries both missing pieces
    -- the per-lane `[-q, q)` bound and `hint[j] ∈ {0, 1}` -- via
    `coefficients_in_field` and `coefficients_are_hints`. -/
theorem use_hint_spec_proof (gamma2 : Std.I32)
    (simd_unit hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.spec gamma2 simd_unit hint := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field simd_unit = .ok true
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints hint = .ok true := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      obtain ⟨hf, hh⟩ := bind_if_ok_true hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1), hf, hh⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        obtain ⟨hf, hh⟩ := bind_if_ok_true hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5), hf, hh⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  have hbound : ∀ j : Nat, j < 8 →
      -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
        ∧ (simd_unit.values.val[j]!).val < (8380417 : Int) :=
    fun j hj => lane_in_field_true
      (coefficients_in_field_lanes simd_unit key.2.1 j hj)
  have hhint : ∀ j : Nat, j < 8 →
      (hint.values.val[j]!).val = 0 ∨ (hint.values.val[j]!).val = 1 :=
    fun j hj => lane_is_hint_true
      (coefficients_are_hints_lanes hint key.2.2 j hj)
  exact triple_true_of_triple
    (Vector.Portable.Rounding.use_hint_spec gamma2 simd_unit hint key.1 hbound hhint)

/-! ## The `gamma2 != i32::MIN` group

    Here the generated `pre` is too weak to yield the theorems' `hg` at all, so
    `hg` itself is what has to be supplied. -/

/-- Discharged OUTRIGHT: the `#[requires]` now pins `gamma2` to the two FIPS-204
    values, which is exactly the theorem's `hg`. -/
theorem compute_hint_spec_proof
    (low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (gamma2 : Std.I32)
    (hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_hint.spec
      low high gamma2 hint := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.compute_hint_spec low high gamma2 hint hg)

/-- Discharged OUTRIGHT, and the most informative case: the one ML-DSA function
    with an `#[ensures]`, so the generated `post` is a real property
    (`0 <= out <= 1`) rather than `True` -- delivered by the existing theorem,
    which proves `r.val in {0, 1}`. The `#[requires]` now pins `gamma2`. -/
theorem compute_one_hint_spec_proof (low high gamma2 : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.spec
      low high gamma2 := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  obtain ⟨v, hv_eq, -, hv_01⟩ :=
    triple_exists_ok (Vector.Portable.Rounding.compute_one_hint_spec low high gamma2 hg)
  refine triple_of_ok hv_eq ?_
  -- the generated post is `if out >= 0 then out <= 1 else false`
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.post]
  rw [if_pos (show v ≥ 0#i32 from by scalar_tac)]
  exact holds_map_ok_of_bool (by simp; scalar_tac)

end libcrux_iot_ml_dsa.Verification
