-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: external functions.
-- Hand-written external models. The opaque `sample_matrix_entry` axiom is
-- from the template; the model defs below are ported from the old
-- aeneas-lean Missing.lean (with now-native symbols removed).
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.Types
import HacspecMlKem.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open libcrux_iot_ml_kem

/-- [libcrux_iot_ml_kem::matrix::sample_matrix_entry]:
    Source: 'ml-kem/src/matrix.rs', lines 26:0-43:1 -/
axiom matrix.sample_matrix_entry
  {Vector : Type} {Hasher : Type} (vectortraitsOperationsInst :
  vector.traits.Operations Vector) (hash_functionsHashInst :
  hash_functions.Hash Hasher) :
  polynomial.PolynomialRingElement Vector → Slice Std.U8 → Std.Usize →
    Std.Usize → RustM (polynomial.PolynomialRingElement Vector)

noncomputable section

namespace CoreModels.core

def cmRangeUsizeToAeneas (r : ops.range.Range Aeneas.Std.Usize) :
    Aeneas.Std.core.ops.range.Range Aeneas.Std.Usize :=
  { start := r.start, «end» := r.«end» }

end CoreModels.core

-- `CoreIterTraitsIteratorIteratorSharedASlice` (the Iterator instance) is now
-- provided natively by CoreModels (hax-lean v0.2.0). `enumerate` is now modeled
-- as a generic `Iterator::enumerate` default method, so provide that instead of
-- the ChunksExact-specific one.
namespace CoreModels.core.iter.traits.iterator

/-- `Iterator::enumerate` default method: wrap `self` in an `Enumerate` at count 0. -/
def Iterator.enumerate.default {Self Item : Type}
    (_inst : Iterator Self Item) (self : Self) :
    Aeneas.Std.RustM (CoreModels.core.iter.adapters.enumerate.Enumerate Self) :=
  Aeneas.Std.RustM.ok { iter := self, count := 0#usize }

end CoreModels.core.iter.traits.iterator

/-! ### `into_iter` for a SHARED FIXED-SIZE ARRAY — a CoreModels gap, delegated here.

    ⚠ THIS BELONGS UPSTREAM, NOT HERE. `cryspen/hax-lean` (pinned at tag `v0.2.0` =
    `ea3e4204`, on `main`) models `into_iter` for a shared SLICE
    (`CoreModels/Core/Funs.lean`, `SharedASlice.Insts.…into_iter`) and has **no
    `SharedAArray` at all**. Iterating `&[T; N]` — which `ind_cpa::serialize_vector` does,
    and which is ordinary Rust — therefore hits an unmodelled external and the extraction
    fails to compile with `Unknown identifier core.SharedAArray.Insts.…into_iter`.

    CHECKED UPSTREAM 2026-08-19, so this is not a guess: `SharedAArray` appears NOWHERE in
    `hax-lib/proof-libs/lean/CoreModels/` on EITHER `cryspen/hax` `main` OR the
    `core-models-regressions-fixes` branch (`6bc393f7`, 7 commits ahead, which rewrites 774
    lines of `CoreModels/Core/Funs.lean` and still only carries `SharedASlice`). So the gap
    is open upstream and a newer core-models does not close it.

    ACTION REQUIRED (KB): raise it against hax so the definition lands in CoreModels and this
    delegate can be deleted. Until then every project extracting a shared-array iteration
    must re-derive it, which is the definition of a gap rather than a project decision.

    Soundness of the delegate: `Array.to_slice` is TOTAL (`Aeneas/Std/Array/ArraySlice.lean:20`,
    no `RustM`), and `&[T; N] → &[T]` is exactly the unsizing coercion Rust performs at
    this call site, so this is the array case expressed through the slice case rather than
    a new model. It is a `def`, NOT an axiom: it adds nothing to `#print axioms`. -/
namespace CoreModels.core

def SharedAArray.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
    {T : Type} {N : Aeneas.Std.Usize} (self : Aeneas.Std.Array T N) :
    RustM (slice.iter.Iter T) :=
  SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
    (Aeneas.Std.Array.to_slice self)

end CoreModels.core

/-! ## `libcrux_secrets.*` integer-cast + classify/declassify stubs.
    `libcrux_secrets`-functions are not part of the extraction; we map
    them to identity functions on the underlying scalar types. -/

namespace libcrux_secrets.traits.Classify.Blanket
def classify {T : Type} (a : T) : Aeneas.Std.RustM T := ok a
end libcrux_secrets.traits.Classify.Blanket

namespace libcrux_secrets.traits.Declassify.Blanket
def declassify {T : Type} (a : T) : Aeneas.Std.RustM T := ok a
end libcrux_secrets.traits.Declassify.Blanket

/-! ### `mem_requests` — valgrind constant-time markers.

    `ct_classify` / `ct_declassify` are `fn <T: ?Sized>(val: &T)` returning `()`.
    Their whole body sits behind `#[cfg(valgrind_ct_test)]`; the module's own
    docs say "When the `cfg` is not enabled, these operations are no-ops".
    Extraction runs WITHOUT that cfg (`RUSTFLAGS=--cfg hax_backend_lean` only),
    so a no-op returning `Unit` is the faithful model.

    `Unit` is a deliberate choice, NOT something the call sites force: aeneas
    emits these as bare statements in a `RustM` do-block, which discards the
    value, so `RustM α` elaborates for any `α` (measured: `RustM Nat` is
    accepted too; only `RustM T` is rejected). Fixing `α := Unit` matches the
    Rust `()` return and stops a future call site from pinning something else.
    The parameter stays generic because Rust's bound is `T: ?Sized`; aeneas
    erases the shared reference, so it is the value type (e.g. `Slice U8`),
    never a reference type. -/

namespace libcrux_secrets.mem_requests
def ct_classify   {T : Type} (_ : T) : Aeneas.Std.RustM Unit := ok ()
def ct_declassify {T : Type} (_ : T) : Aeneas.Std.RustM Unit := ok ()
end libcrux_secrets.mem_requests

namespace libcrux_secrets

/-! Cast stubs written in the upstream `declassify → cast → classify`
    shape so that downstream proofs can unfold the chain. -/

def I16.Insts.Libcrux_secretsIntCastOps.as_i16 (x : Std.I16) : RustM Std.I16 := do
  let i ← traits.Declassify.Blanket.declassify x
  traits.Classify.Blanket.classify i

def I16.Insts.Libcrux_secretsIntCastOps.as_i32 (x : Std.I16) : RustM Std.I32 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.IScalar.cast .I32 i)
  traits.Classify.Blanket.classify i1

def I16.Insts.Libcrux_secretsIntCastOps.as_u16 (x : Std.I16) : RustM Std.U16 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.IScalar.hcast .U16 i)
  traits.Classify.Blanket.classify i1

def I16.Insts.Libcrux_secretsIntCastOps.as_u8 (x : Std.I16) : RustM Std.U8 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.IScalar.hcast .U8 i)
  traits.Classify.Blanket.classify i1

def I32.Insts.Libcrux_secretsIntCastOps.as_i16 (x : Std.I32) : RustM Std.I16 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.IScalar.cast .I16 i)
  traits.Classify.Blanket.classify i1

def U8.Insts.Libcrux_secretsIntCastOps.as_i16 (x : Std.U8) : RustM Std.I16 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.UScalar.hcast .I16 i)
  traits.Classify.Blanket.classify i1

def U16.Insts.Libcrux_secretsIntCastOps.as_i16 (x : Std.U16) : RustM Std.I16 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.UScalar.hcast .I16 i)
  traits.Classify.Blanket.classify i1

def U16.Insts.Libcrux_secretsIntCastOps.as_u64 (x : Std.U16) : RustM Std.U64 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 := Std.UScalar.cast .U64 i
  traits.Classify.Blanket.classify i1

def U32.Insts.Libcrux_secretsIntCastOps.as_i16 (x : Std.U32) : RustM Std.I16 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.UScalar.hcast .I16 i)
  traits.Classify.Blanket.classify i1

def U32.Insts.Libcrux_secretsIntCastOps.as_i32 (x : Std.U32) : RustM Std.I32 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 ← lift (Std.UScalar.hcast .I32 i)
  traits.Classify.Blanket.classify i1

def U64.Insts.Libcrux_secretsIntCastOps.as_u32 (x : Std.U64) : RustM Std.U32 := do
  let i ← traits.Declassify.Blanket.declassify x
  let i1 := Std.UScalar.cast .U32 i
  traits.Classify.Blanket.classify i1

/-- `Scalar` marker trait (carries no methods we use); `PUnit` for shape. -/
@[reducible] def traits.Scalar (_Self : Type) : Type := PUnit
@[reducible] def U8.Insts.Libcrux_secretsTraitsScalar : traits.Scalar Std.U8 := PUnit.unit

/-- `classify_ref` on a shared slice — no-op (takes the marker + slice). -/
def SharedASlice.Insts.Libcrux_secretsTraitsClassifyRefSharedASlice.classify_ref
    {T : Type} (_inst : traits.Scalar T) (s : Aeneas.Std.Slice T) :
    Aeneas.Std.RustM (Aeneas.Std.Slice T) := ok s

end libcrux_secrets

end
