/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotMlKem.Extraction`. -/

/-
  # Discharging the hax-generated specs -- and what it exposes

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust: for each annotated function a
  `<fn>.pre` (the `requires`, as a `RustM Bool`), optionally a `<fn>.post`, and

    `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  ## Where the annotations are -- and where the verification is

  All 38 generated specs sit in `vector.portable.*`: the SIMD vector primitives
  (`ntt_step`, `serialize_*`/`deserialize_*`, `compress*`, `rej_sample`,
  `accumulating_ntt_multiply*`, …). NONE of them is one of this development's
  top-level results: the four L7 matrix apexes (`compute_As_plus_e_fc`,
  `compute_vector_u_fc`, `compute_ring_element_v_fc`, `compute_message_fc`) and the
  `ind_cpa` lane theorems are proved about `matrix.*` / `ind_cpa.*` / `serialize.*`
  Rust functions, and those carry no `requires`/`ensures` at all, so hax generates
  nothing for them.

  That is the first thing this exercise established, and it is worth stating
  plainly: the feature produces specs exactly where annotations exist, and in
  libcrux-iot the annotations are on the inner helpers rather than on the verified
  top-level API. (SHA-3 is the exception -- its six public entry points ARE
  annotated, and `LibcruxIotSha3`'s corresponding file discharges all six
  outright.)

  ## The second finding: the annotations are weaker than the proofs' domains

  For the vector primitives that DO have a hand-written theorem, the generated
  `pre` is systematically weaker than the theorem's hypotheses. `ntt_step` is
  representative: it is annotated `requires(i < 16 && j < 16)`, while
  `Vector.Portable.Ntt.ntt_step_spec` additionally assumes `i ≠ j`, a bound on the
  zeta (`|zeta| <= 1664`) and coefficient magnitude bounds (`|vec[i]|, |vec[j]| <=
  3*3328`). The magnitude bounds are the whole substance of the Kyber
  bounds-tracking argument, and the Rust says nothing about them.

  So the generated obligation is STRICTLY STRONGER than what was proved, and no
  post-weakening closes the gap. Discharging it outright would need either a
  genuinely more general panic-freedom argument or a strengthening of the
  `#[requires]` to state the magnitude bounds. That is a decision about the Rust
  annotations, not about the proofs, so it is surfaced rather than hidden behind a
  `sorry`.

  ## What this file proves

  The two `ntt`-layer primitives are discharged UNDER THE HYPOTHESES THE
  ANNOTATION IS MISSING, stated explicitly as extra arguments. Each is a real
  theorem that reuses the existing proof, and its hypothesis list beyond
  `(… .pre …).holds` is exactly the gap -- i.e. exactly what the `#[requires]`
  would have to gain.

  They are done as representatives, not as a complete sweep: the same shape
  applies to the `serialize_*`/`deserialize_*`/`compress*` families, and extending
  it there is mechanical once the annotation question above is settled. Doing all
  38 before that decision would bake in hypothesis lists that the Rust may be
  about to absorb.
-/
import LibcruxIotMlKem.Extraction
import LibcruxIotMlKem.Vector.Portable.Ntt

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_ml_kem.Verification

/-! ## Bridges -/

/-- A Triple with a `⌜True⌝` post says exactly "this computation does not fail
    and does not diverge", so any stronger post implies it. -/
private theorem triple_true_of_triple {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ True ⌝ ⦄ := by
  match hx : x with
  | .ok v => simp [Std.Do.Triple, WP.wp, PredTrans.apply]
  | .fail e =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-- `<fn>.pre` is a `RustM Bool` while `RustM.holds` wants a `RustM Prop`, so the
    generated `.spec` inserts a `(· = true) <$> ·`; on an `ok` that collapses. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-! ## The NTT butterfly steps

    Generated `pre`: `i < 16 && j < 16`. The theorems additionally need `i != j`,
    the zeta bound and the coefficient magnitude bounds -- all supplied here. -/

theorem ntt_step_spec_proof
    (vec : libcrux_iot_ml_kem.vector.portable.vector_type.PortableVector)
    (zeta : Std.I16) (i j : Std.Usize)
    -- supplied because `#[requires]` does not state them:
    (h_ne : i.val ≠ j.val)
    (h_zeta : zeta.val.natAbs ≤ 1664)
    (h_a : (vec.elements.val[i.val]!).val.natAbs ≤ 3 * 3328)
    (h_b : (vec.elements.val[j.val]!).val.natAbs ≤ 3 * 3328) :
    libcrux_iot_ml_kem.vector.portable.ntt.ntt_step.spec vec zeta i j := by
  intro hpre
  obtain ⟨h_i, h_j⟩ : i.val < 16 ∧ j.val < 16 := by
    simp only [libcrux_iot_ml_kem.vector.portable.ntt.ntt_step.pre] at hpre
    by_cases h1 : i < (16#usize : Std.Usize)
    · rw [if_pos h1] at hpre
      exact ⟨by scalar_tac, by
        have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac⟩
    · rw [if_neg h1] at hpre
      exact absurd (bool_of_holds_map_ok hpre) (by simp)
  exact triple_true_of_triple
    (Vector.Portable.Ntt.ntt_step_spec vec zeta i j h_i h_j h_ne h_zeta h_a h_b)

theorem inv_ntt_step_spec_proof
    (vec : libcrux_iot_ml_kem.vector.portable.vector_type.PortableVector)
    (zeta : Std.I16) (i j : Std.Usize)
    -- supplied because `#[requires]` does not state them:
    (h_ne : i.val ≠ j.val)
    (h_zeta : zeta.val.natAbs ≤ 1664)
    (hbnd : ∀ k : Nat, k < 16 → (vec.elements.val[k]!).val.natAbs ≤ 4 * 3328) :
    libcrux_iot_ml_kem.vector.portable.ntt.inv_ntt_step.spec vec zeta i j := by
  intro hpre
  obtain ⟨h_i, h_j⟩ : i.val < 16 ∧ j.val < 16 := by
    simp only [libcrux_iot_ml_kem.vector.portable.ntt.inv_ntt_step.pre] at hpre
    by_cases h1 : i < (16#usize : Std.Usize)
    · rw [if_pos h1] at hpre
      exact ⟨by scalar_tac, by
        have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac⟩
    · rw [if_neg h1] at hpre
      exact absurd (bool_of_holds_map_ok hpre) (by simp)
  exact triple_true_of_triple
    (Vector.Portable.Ntt.inv_ntt_step_spec vec zeta i j h_i h_j h_ne h_zeta hbnd)

end libcrux_iot_ml_kem.Verification
