# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Inria-AIO, Cryspen, and Christian Amsüss

[package]
name = "embedded-cal-nrf54l15-test"
edition = "2024"
license = "(MIT OR Apache-2.0) AND MIT OR Apache-2.0"
repository = "https://github.com/celabshq/libcrux-iot"
version = "0.0.1-alpha"

[lib]
# While the crate is already excluded from the workspace's defaults, setting
# this also means that when `cargo test` is run in here, cargo reaches into the
# local .cargo that sets up target and runner.
test = false

[[test]]
name = "integration"
harness = false

[dependencies]

[dev-dependencies]
embedded-alloc = "0.6.0"
nrf-pac = { version = "0.2.0", features = ["nrf54l15-app", "rt"] }
embedded-cal = { git = "https://github.com/lake-rs/embedded-cal", rev = "14f8f93bbf1bce8e4275c33a88209fbdcd8610a2" }
embedded-cal-nrf54l15 = { git = "https://github.com/lake-rs/embedded-cal", rev = "14f8f93bbf1bce8e4275c33a88209fbdcd8610a2" }
libcrux-iot-p256 = { path = "../libcrux-iot/p256", features = ["embedded-cal"] }
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7", features = ["device"] }
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
defmt-test = "0.4"
hexlit = "0.5.5"
