-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]: type definitions
import Aeneas
import CoreModels
import LibcruxIotMlKem.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libcrux_iot_ml_kem

/-- Trait declaration: [libcrux_iot_ml_kem::hash_functions::Hash]
    Source: 'ml-kem/src/hash_functions.rs', lines 26:0-69:1 -/
structure hash_functions.Hash (Self : Type) where
  G : Slice Std.U8 → Slice Std.U8 → RustM (Slice Std.U8)
  H : Slice Std.U8 → Slice Std.U8 → RustM (Slice Std.U8)
  PRF : forall (LEN : Std.Usize), Slice Std.U8 → Slice Std.U8 → RustM
    (Slice Std.U8)
  PRFxN : Slice (Array Std.U8 33#usize) → Slice Std.U8 → Std.Usize →
    RustM (Slice Std.U8)
  shake128_init_absorb_final : Slice (Array Std.U8 34#usize) → RustM Self
  shake128_squeeze_first_three_blocks : Self → Slice (Array Std.U8 504#usize)
    → RustM (Self × (Slice (Array Std.U8 504#usize)))
  shake128_squeeze_next_block : Self → Slice (Array Std.U8 168#usize) →
    RustM (Self × (Slice (Array Std.U8 168#usize)))

/-- [libcrux_iot_ml_kem::polynomial::PolynomialRingElement]
    Source: 'ml-kem/src/polynomial.rs', lines 32:0-34:1 -/
structure polynomial.PolynomialRingElement (Vector : Type) where
  coefficients : Array Vector 16#usize

/-- [libcrux_iot_ml_kem::ind_cpa::unpacked::IndCpaPrivateKeyUnpacked]
    Source: 'ml-kem/src/ind_cpa.rs', lines 31:4-33:5 -/
structure ind_cpa.unpacked.IndCpaPrivateKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  secret_as_ntt : Array (polynomial.PolynomialRingElement Vector) K

/-- [libcrux_iot_ml_kem::ind_cpa::unpacked::IndCpaPublicKeyUnpacked]
    Source: 'ml-kem/src/ind_cpa.rs', lines 46:4-54:5 -/
structure ind_cpa.unpacked.IndCpaPublicKeyUnpacked (Vector : Type) (K :
  Std.Usize) (K_SQUARED : Std.Usize) where
  t_as_ntt : Array (polynomial.PolynomialRingElement Vector) K
  seed_for_A : Array Std.U8 32#usize
  A : Array (polynomial.PolynomialRingElement Vector) K_SQUARED

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Repr]
    Source: 'ml-kem/src/vector/traits.rs', lines 16:0-19:1
    Visibility: public -/
structure vector.traits.Repr (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  corecloneCloneInst : core.clone.Clone Self
  repr : Self → RustM (Array Std.I16 16#usize)

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Operations]
    Source: 'ml-kem/src/vector/traits.rs', lines 25:0-164:1
    Visibility: public -/
structure vector.traits.Operations (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  corecloneCloneInst : core.clone.Clone Self
  ReprInst : vector.traits.Repr Self
  ZERO : RustM Self
  from_i16_array : Slice Std.I16 → Self → RustM Self
  to_i16_array : Self → Slice Std.I16 → RustM (Slice Std.I16)
  reducing_from_i32_array : Slice Std.I32 → Self → RustM Self
  add : Self → Self → RustM Self
  sub : Self → Self → RustM Self
  negate : Self → RustM Self
  multiply_by_constant : Self → Std.I16 → RustM Self
  bitwise_and_with_constant : Self → Std.I16 → RustM Self
  shift_right : forall (SHIFT_BY : Std.I32), Self → RustM Self
  cond_subtract_3329 : Self → RustM Self
  barrett_reduce : Self → RustM Self
  montgomery_multiply_by_constant : Self → Std.I16 → RustM Self
  compress_1 : Self → RustM Self
  compress : forall (COEFFICIENT_BITS : Std.I32), Self → RustM Self
  decompress_ciphertext_coefficient : forall (COEFFICIENT_BITS : Std.I32), Self
    → RustM Self
  ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 →
    RustM Self
  ntt_layer_2_step : Self → Std.I16 → Std.I16 → RustM Self
  ntt_layer_3_step : Self → Std.I16 → RustM Self
  inv_ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16
    → RustM Self
  inv_ntt_layer_2_step : Self → Std.I16 → Std.I16 → RustM Self
  inv_ntt_layer_3_step : Self → Std.I16 → RustM Self
  accumulating_ntt_multiply : Self → Self → Slice Std.I32 → Std.I16 →
    Std.I16 → Std.I16 → Std.I16 → RustM (Slice Std.I32)
  accumulating_ntt_multiply_fill_cache : Self → Self → Slice Std.I32 →
    Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 → RustM ((Slice
    Std.I32) × Self)
  accumulating_ntt_multiply_use_cache : Self → Self → Slice Std.I32 →
    Self → RustM (Slice Std.I32)
  serialize_1 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_1 : Slice Std.U8 → Self → RustM Self
  serialize_4 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_4 : Slice Std.U8 → Self → RustM Self
  serialize_5 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_5 : Slice Std.U8 → Self → RustM Self
  serialize_10 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_10 : Slice Std.U8 → Self → RustM Self
  serialize_11 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_11 : Slice Std.U8 → Self → RustM Self
  serialize_12 : Self → Slice Std.U8 → RustM (Slice Std.U8)
  deserialize_12 : Slice Std.U8 → Self → RustM Self
  rej_sample : Slice Std.U8 → Slice Std.I16 → RustM (Std.Usize × (Slice
    Std.I16))

/-- [libcrux_iot_ml_kem::ind_cpa::decrypt_unpacked::closure]
    Source: 'ml-kem/src/ind_cpa.rs', lines 893:31-893:74 -/
@[reducible]
def ind_cpa.decrypt_unpacked.closure (Vector : Type) (K : Std.Usize)
  (CIPHERTEXT_SIZE : Std.Usize) (VECTOR_U_ENCODED_SIZE : Std.Usize)
  (U_COMPRESSION_FACTOR : Std.Usize) (V_COMPRESSION_FACTOR : Std.Usize) :=
Unit

/-- [libcrux_iot_ml_kem::ind_cpa::decrypt::closure]
    Source: 'ml-kem/src/ind_cpa.rs', lines 947:36-947:79 -/
@[reducible]
def ind_cpa.decrypt.closure (Vector : Type) (K : Std.Usize) (CIPHERTEXT_SIZE :
  Std.Usize) (VECTOR_U_ENCODED_SIZE : Std.Usize) (U_COMPRESSION_FACTOR :
  Std.Usize) (V_COMPRESSION_FACTOR : Std.Usize) :=
Unit

/-- [libcrux_iot_ml_kem::matrix::lift_poly::closure]
    Source: 'ml-kem/src/matrix.rs', lines 22:25-26:5 -/
@[reducible]
def matrix.lift_poly.closure (Vector : Type) :=
  polynomial.PolynomialRingElement Vector

/-- [libcrux_iot_ml_kem::matrix::lift_vec::closure]
    Source: 'ml-kem/src/matrix.rs', lines 34:25-34:45 -/
@[reducible]
def matrix.lift_vec.closure (Vector : Type) (K : Std.Usize) :=
  Array (polynomial.PolynomialRingElement Vector) K

/-- [libcrux_iot_ml_kem::matrix::lift_matrix_from_slice::closure]
    Source: 'ml-kem/src/matrix.rs', lines 43:25-43:83 -/
@[reducible]
def matrix.lift_matrix_from_slice.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector)

/-- [libcrux_iot_ml_kem::matrix::lift_matrix_from_slice::closure::closure]
    Source: 'ml-kem/src/matrix.rs', lines 43:50-43:82 -/
def matrix.lift_matrix_from_slice.closure.closure (Vector : Type) (K :
  Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector) × Std.Usize

/-- [libcrux_iot_ml_kem::matrix::lift_vec_slice::closure]
    Source: 'ml-kem/src/matrix.rs', lines 51:25-51:45 -/
@[reducible]
def matrix.lift_vec_slice.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector)

/-- [libcrux_iot_ml_kem::matrix::lift_matrix_from_seed::closure]
    Source: 'ml-kem/src/matrix.rs', lines 62:25-68:5 -/
@[reducible]
def matrix.lift_matrix_from_seed.closure (Vector : Type) (Hasher : Type) (K :
  Std.Usize) :=
  Slice Std.U8

/-- [libcrux_iot_ml_kem::matrix::lift_matrix_from_seed::closure::closure]
    Source: 'ml-kem/src/matrix.rs', lines 63:29-67:9 -/
def matrix.lift_matrix_from_seed.closure.closure (Vector : Type) (Hasher :
  Type) (K : Std.Usize) :=
  Slice Std.U8 × Std.Usize

/-- [libcrux_iot_ml_kem::matrix::lift_t_as_ntt_from_public_key::closure]
    Source: 'ml-kem/src/matrix.rs', lines 79:25-86:5 -/
@[reducible]
def matrix.lift_t_as_ntt_from_public_key.closure (Vector : Type) (K :
  Std.Usize) :=
  Slice Std.U8

/-- [libcrux_iot_ml_kem::matrix::compute_cache::closure]
    Source: 'ml-kem/src/matrix.rs', lines 98:25-104:5 -/
@[reducible]
def matrix.compute_cache.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector)

/-- [libcrux_iot_ml_kem::matrix::poly_matches::closure]
    Source: 'ml-kem/src/matrix.rs', lines 138:20-144:5 -/
def matrix.poly_matches.closure (Vector : Type) :=
  polynomial.PolynomialRingElement Vector × Array
  hacspec_ml_kem.parameters.FieldElement 256#usize

/-- [libcrux_iot_ml_kem::matrix::vec_matches::closure]
    Source: 'ml-kem/src/matrix.rs', lines 154:20-163:5 -/
def matrix.vec_matches.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector) × Array (Array
  hacspec_ml_kem.parameters.FieldElement 256#usize) K

/-- [libcrux_iot_ml_kem::matrix::vec_bnd::closure]
    Source: 'ml-kem/src/matrix.rs', lines 228:20-234:5 -/
def matrix.vec_bnd.closure (Vector : Type) (K : Std.Usize) :=
  Array (polynomial.PolynomialRingElement Vector) K × Std.I16

/-- [libcrux_iot_ml_kem::matrix::vec_slice_bnd::closure]
    Source: 'ml-kem/src/matrix.rs', lines 244:20-250:5 -/
def matrix.vec_slice_bnd.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector) × Std.I16

/-- [libcrux_iot_ml_kem::matrix::matrix_slice_bnd::closure]
    Source: 'ml-kem/src/matrix.rs', lines 260:20-266:5 -/
def matrix.matrix_slice_bnd.closure (Vector : Type) (K : Std.Usize) :=
  Slice (polynomial.PolynomialRingElement Vector) × Std.I16

/-- [libcrux_iot_ml_kem::matrix::acc_zero::closure]
    Source: 'ml-kem/src/matrix.rs', lines 273:20-279:5 -/
@[reducible]
def matrix.acc_zero.closure := Array Std.I32 256#usize

/-- [libcrux_iot_ml_kem::vector::portable::vector_type::PortableVector]
    Source: 'ml-kem/src/vector/portable/vector_type.rs', lines 9:0-11:1
    Visibility: public -/
structure vector.portable.vector_type.PortableVector where
  elements : Array Std.I16 16#usize

end libcrux_iot_ml_kem
