/- Handwritten proofs about the extracted definitions.

hax creates this file once and never modifies anything under
`Verification/`. Import the extraction modules to prove properties
about, e.g. `import LibcruxIotMlDsa.Extraction`. -/

/-
  # Discharging the hax-generated specs -- and what it exposes

  `Extraction/Specs.lean` is generated by hax from the `#[hax_lib::requires]` /
  `#[hax_lib::ensures]` annotations on the Rust: for each annotated function a
  `<fn>.pre` (the `requires`, as a `RustM Bool`), optionally a `<fn>.post`, and

    `<fn>.spec : Prop := (<fn>.pre args).holds → ⦃⌜True⌝⦄ <fn> args ⦃⇓ res => ⌜post⌝⦄`

  ML-DSA's annotations sit on the eight `simd.portable.arithmetic` helpers, not on
  the polynomial API, so those eight are what got generated. Six of them have a
  hand-written correctness theorem in `Vector/Portable/Rounding.lean`.

  ## The original finding, and what was done about it

  As first generated, NOT ONE of the eight was dischargeable. The annotations
  have since been STRENGTHENED to match the domains the Lean proofs actually
  verify, and ALL SIX that have a correctness theorem now discharge OUTRIGHT:
  every hypothesis of every one of them comes out of its generated `pre`. No
  theorem below takes a hypothesis beyond `(... .pre ...).holds`.

  What that took, beyond pinning `gamma2`:

  - `decompose_element` and `use_one_hint` gained scalar range bounds on their
    coefficient arguments (`r >= -FIELD_MODULUS && r < FIELD_MODULUS`, and
    `hint == 0 || hint == 1`). For `decompose_element` this makes good on the
    `// XXX: ... should be a precondition for hax instead` note that sat next to
    a commented-out `debug_assert!` in `arithmetic.rs`.

  - `decompose` and `use_hint` gained the same bounds PER LANE, via the
    spec-only boolean helpers `coefficients_in_field` / `coefficients_are_hints`.
    Those are written as an explicit eight-way conjunction rather than a
    `hax_lib::forall`, for two reasons documented in full both in
    `arithmetic.rs` and at the decoding lemmas below. In short: a bool `&&`
    inside a quantifier closure makes aeneas fail outright, and even with a
    Prop-level `&` the resulting precondition is unsatisfiable, which would make
    the generated spec vacuous rather than fail loudly.

  Note that the coefficients here are SECRET-typed (`libcrux_secrets::I32`);
  bounding them in a `#[requires]` turned out to be fine, because the annotation
  is erased in non-hax builds.

  ## The original diagnosis (retained, because it is what drove the change)

  Not one of the six can be proved from its existing theorem, and the reason is
  worth stating precisely, because it is a real mismatch between the Rust
  annotations and the Lean development rather than a proof-engineering nuisance.

  (1) THE ANNOTATION IS WEAKER THAN THE PROOF'S DOMAIN.
      `compute_one_hint` and `compute_hint` are annotated
      `requires(gamma2 != i32::MIN)` -- just enough for `-gamma2` not to overflow.
      Their Lean theorems assume `gamma2 ∈ {95232, 261888}`, the two FIPS-204
      values, because the functional postcondition is stated against
      `Spec.Rounding.computeHint`, which is only meaningful there. So the
      generated obligation claims MORE than we proved: panic-freedom for every
      `gamma2` except `i32::MIN`.

  (2) THE ANNOTATION OMITS INPUT-RANGE PRECONDITIONS THE PROOF NEEDS.
      `decompose_element`, `decompose`, `use_one_hint` and `use_hint` are
      annotated only with `gamma2 ∈ {GAMMA2_V95_232, GAMMA2_V261_888}`. Their Lean
      theorems additionally assume the coefficients lie in `[-q, q)` and, for the
      hint functions, that each hint is `0` or `1`. The Rust says nothing about
      either, so again the generated obligation is the stronger statement.

  In both cases the generated spec is STRICTLY STRONGER than the theorem, so no
  amount of post-weakening closes the gap -- it would take either a genuinely more
  general panic-freedom argument, or a strengthening of the Rust annotations to
  match the domain that was actually verified. That is a decision about the Rust,
  not about the proofs, so it is surfaced here rather than papered over with a
  `sorry`.

  ## What this file does prove

  All six generated specs are discharged unconditionally from the existing
  correctness proofs in `Vector/Portable/Rounding.lean`.

  `compute_one_hint` is the most informative case: it is the one ML-DSA function
  with an `#[ensures]`, so its generated `post` is a real property
  (`0 <= out <= 1`) rather than `True` -- and that post IS delivered by the
  existing theorem, which proves `r.val in {0, 1}`.

  The remaining two generated specs, `get_n_least_significant_bits` and
  `shift_left_then_reduce`, have no correctness theorem in the tree at all and are
  left untouched.
-/
import LibcruxIotMlDsa.Extraction
import LibcruxIotMlDsa.Vector.Portable.Rounding

open CoreModels Aeneas Aeneas.Std Std.Do

namespace libcrux_iot_ml_dsa.Verification

/-! ## Bridges -/

/-- A Triple with a `⌜True⌝` post says exactly "this computation does not fail
    and does not diverge", so any stronger post implies it. -/
private theorem triple_true_of_triple {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ _r => ⌜ True ⌝ ⦄ := by
  match hx : x with
  | .ok v => simp [Std.Do.Triple, WP.wp, PredTrans.apply]
  | .fail e =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h
      simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-- `<fn>.pre` is a `RustM Bool` while `RustM.holds` wants a `RustM Prop`, so the
    generated `.spec` inserts a `(· = true) <$> ·`; on an `ok` that collapses. -/
private theorem bool_of_holds_map_ok {b : Bool}
    (h : RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool))) :
    b = true := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap] at h
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Converse of `bool_of_holds_map_ok`: build a generated `post`'s `.holds` from
    the plain boolean fact. -/
private theorem holds_map_ok_of_bool {b : Bool} (h : b = true) :
    RustM.holds ((fun a => a = true) <$> (RustM.ok b : RustM Bool)) := by
  have hmap : ((fun a => a = true) <$> (RustM.ok b : RustM Bool))
      = RustM.ok (b = true) := rfl
  rw [hmap]
  simpa [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] using h

/-- Triple from an `ok` equation plus the post fact. -/
private theorem triple_of_ok {α : Type} {x : RustM α} {v : α}
    {P : α → Prop} (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

/-- Triple to existential (stated with `x` a variable so the `match` substitutes). -/
private theorem triple_exists_ok {α : Type} {x : RustM α} {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'; exact h'
  | .fail e =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'
  | .div =>
      exfalso; have h' := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at h'

/-! ### Decoding the unrolled lane conjunctions

    `decompose` and `use_hint` are annotated with the spec-only boolean helpers
    `coefficients_in_field` / `coefficients_are_hints`, so the per-lane bounds
    their theorems need now come OUT OF the generated `pre` instead of being
    supplied by hand.

    Those helpers are written in Rust as an explicit eight-way conjunction over
    constant indices rather than as `hax_lib::forall(|i| implies(i < 8, ...))`.
    `arithmetic.rs` carries the full note; the two reasons, both established by
    experiment, are:

    1. a bool `&&` inside a quantifier closure makes aeneas fail outright
       (`interp/Interp.ml, line 609`) -- a Prop-level `&` on `.to_prop()`s does
       not, so short-circuiting `&&` in a `Prop` closure is the trigger;

    2. even with `&`, the resulting precondition is UNSATISFIABLE, which would
       make `<fn>.spec` VACUOUS rather than fail loudly. `hax_lib::prop::forall`
       is modelled (`CoreModels/HaxLib/Prop.lean`) as

         ok (∀ t : T, Result.holds (do let u <- fn.call f t; inst.into u))

       i.e. it ranges over ALL of `Usize`, while the extracted closure body
       evaluates `Array.index_usize simd_unit.values i` BEFORE the `i < 8` guard.
       Out of range that index is `fail .panic`, `Result.holds` of a failing
       computation is `False`, and so the whole `forall` is `False`.

    The unrolled form has neither problem: its `&&`s sit in an ordinary function
    rather than a `Prop` closure, and every index is in range. -/

/-- Like `bool_of_holds_map_ok`, but for a `pre` that is not syntactically an
    `ok` -- here it is a nested-`if` computation. -/
private theorem eq_ok_true_of_holds_map {x : RustM Bool}
    (h : RustM.holds ((fun a => a = true) <$> x)) : x = .ok true := by
  cases x with
  | ok b => rw [bool_of_holds_map_ok h]
  | fail e =>
      exfalso
      have hm : ((fun a => a = true) <$> (RustM.fail e : RustM Bool))
          = (RustM.fail e : RustM Prop) := rfl
      rw [hm] at h
      simp [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] at h
  | div =>
      exfalso
      have hm : ((fun a => a = true) <$> (RustM.div : RustM Bool))
          = (RustM.div : RustM Prop) := rfl
      rw [hm] at h
      simp [RustM.holds, Std.Do.Triple, WP.wp, PredTrans.apply] at h

/-- An in-range `Array.index_usize` as a plain equation, so the unrolled
    conjunction can be rewritten index by index. -/
private theorem array_index_ok {alpha : Type} [Inhabited alpha] {n : Std.Usize}
    (v : Aeneas.Std.Array alpha n) (i : Std.Usize) (h : i.val < v.val.length) :
    v.index_usize i = .ok (v.val[i.val]!) := by
  unfold Aeneas.Std.Array.index_usize
  rw [Aeneas.Std.Array.getElem?_Usize_eq, List.getElem?_eq_getElem h,
    List.getElem!_eq_getElem?_getD, List.getElem?_eq_getElem h]
  rfl

/-- One link of the unrolled conjunction: `&&` extracts to
    `if b then rest else false`, so a `true` result forces both sides. -/
private theorem bind_if_ok_true {x rest : RustM Bool}
    (h : (do let b ← x; if b then rest else RustM.ok false) = RustM.ok true) :
    x = .ok true ∧ rest = .ok true := by
  cases x with
  | ok b =>
      cases b with
      | true => exact ⟨rfl, by simpa using h⟩
      | false => exfalso; simp at h
  | fail e => exfalso; simp at h
  | div => exfalso; simp at h

/-- `lane_in_field x = ok true` decoded. The `-FIELD_MODULUS` bound arrives as a
    CHECKED negation (`-. FIELD_MODULUS`, a `RustM I32`) and is resolved first. -/
private theorem lane_in_field_true {x : Std.I32}
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field x = .ok true) :
    -(8380417 : Int) ≤ x.val ∧ x.val < (8380417 : Int) := by
  have hneg : (-. libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS : RustM Std.I32)
      = .ok (-8380417)#i32 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
    rfl
  have hFM : (libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS).val = 8380417 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field, hneg,
    Aeneas.Std.bind_tc_ok] at h
  by_cases h1 : x ≥ (-8380417)#i32
  · by_cases h2 : x < libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS
    · exact ⟨by scalar_tac, by scalar_tac⟩
    · exfalso; rw [if_pos h1] at h; simp [h2] at h
  · exfalso; rw [if_neg h1] at h; simp at h

/-- `lane_is_hint x = ok true` decoded. -/
private theorem lane_is_hint_true {x : Std.I32}
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint x = .ok true) :
    x.val = 0 ∨ x.val = 1 := by
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint] at h
  by_cases h1 : x = 0#i32
  · exact Or.inl (by scalar_tac)
  · rw [if_neg h1] at h
    have hx : x = 1#i32 := by simpa using h
    exact Or.inr (by scalar_tac)

/-- All eight lanes of `coefficients_in_field` pass. -/
private theorem coefficients_in_field_lanes
    (c : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field c = .ok true) :
    ∀ j : Nat, j < 8 → libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field (c.values.val[j]!) = .ok true := by
  have hlen : c.values.val.length = 8 := c.values.property
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field,
    array_index_ok c.values 0#usize (by simp [hlen]),
    array_index_ok c.values 1#usize (by simp [hlen]),
    array_index_ok c.values 2#usize (by simp [hlen]),
    array_index_ok c.values 3#usize (by simp [hlen]),
    array_index_ok c.values 4#usize (by simp [hlen]),
    array_index_ok c.values 5#usize (by simp [hlen]),
    array_index_ok c.values 6#usize (by simp [hlen]),
    array_index_ok c.values 7#usize (by simp [hlen]),
    Aeneas.Std.bind_tc_ok] at h
  obtain ⟨h0, h⟩ := bind_if_ok_true h
  obtain ⟨h1, h⟩ := bind_if_ok_true h
  obtain ⟨h2, h⟩ := bind_if_ok_true h
  obtain ⟨h3, h⟩ := bind_if_ok_true h
  obtain ⟨h4, h⟩ := bind_if_ok_true h
  obtain ⟨h5, h⟩ := bind_if_ok_true h
  obtain ⟨h6, h7⟩ := bind_if_ok_true h
  intro j hj
  -- `interval_cases` is a Mathlib tactic and is not imported here; peel the
  -- eight literals off by hand. Each `exact` closes up to `(k#usize).val = k`.
  rcases j with _ | _ | _ | _ | _ | _ | _ | _ | j
  · exact h0
  · exact h1
  · exact h2
  · exact h3
  · exact h4
  · exact h5
  · exact h6
  · exact h7
  · exact absurd hj (by omega)

/-- All eight lanes of `coefficients_are_hints` pass. -/
private theorem coefficients_are_hints_lanes
    (c : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (h : libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints c = .ok true) :
    ∀ j : Nat, j < 8 → libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_is_hint (c.values.val[j]!) = .ok true := by
  have hlen : c.values.val.length = 8 := c.values.property
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints,
    array_index_ok c.values 0#usize (by simp [hlen]),
    array_index_ok c.values 1#usize (by simp [hlen]),
    array_index_ok c.values 2#usize (by simp [hlen]),
    array_index_ok c.values 3#usize (by simp [hlen]),
    array_index_ok c.values 4#usize (by simp [hlen]),
    array_index_ok c.values 5#usize (by simp [hlen]),
    array_index_ok c.values 6#usize (by simp [hlen]),
    array_index_ok c.values 7#usize (by simp [hlen]),
    Aeneas.Std.bind_tc_ok] at h
  obtain ⟨h0, h⟩ := bind_if_ok_true h
  obtain ⟨h1, h⟩ := bind_if_ok_true h
  obtain ⟨h2, h⟩ := bind_if_ok_true h
  obtain ⟨h3, h⟩ := bind_if_ok_true h
  obtain ⟨h4, h⟩ := bind_if_ok_true h
  obtain ⟨h5, h⟩ := bind_if_ok_true h
  obtain ⟨h6, h7⟩ := bind_if_ok_true h
  intro j hj
  -- `interval_cases` is a Mathlib tactic and is not imported here; peel the
  -- eight literals off by hand. Each `exact` closes up to `(k#usize).val = k`.
  rcases j with _ | _ | _ | _ | _ | _ | _ | _ | j
  · exact h0
  · exact h1
  · exact h2
  · exact h3
  · exact h4
  · exact h5
  · exact h6
  · exact h7
  · exact absurd hj (by omega)

/-! ## The `gamma2 ∈ {95232, 261888}` group

    Here the generated `pre` delivers exactly the theorems' `hg`; what has to be
    supplied on the side is the input-range information the Rust omits. -/

/-- Discharged OUTRIGHT. The `#[requires]` now states the `[-q, q)` range for
    `r` as well as pinning `gamma2`, so both hypotheses of
    `decompose_element_spec` come out of the generated `pre`.

    hax duplicates the range block under each `gamma2` disjunct, and each copy is
    definitionally `lane_in_field r`, so `lane_in_field_true` decodes it. -/
theorem decompose_element_spec_proof (gamma2 r : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.spec gamma2 r := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose_element.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ -(8380417 : Int) ≤ r.val ∧ r.val < (8380417 : Int) := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      have hr : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field r = .ok true := hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1),
        (lane_in_field_true hr).1, (lane_in_field_true hr).2⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        have hr : libcrux_iot_ml_dsa.simd.portable.arithmetic.lane_in_field r = .ok true := hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5),
          (lane_in_field_true hr).1, (lane_in_field_true hr).2⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  exact triple_true_of_triple
    (Vector.Portable.Rounding.decompose_element_spec gamma2 r key.1 key.2.1 key.2.2)

/-- Discharged OUTRIGHT: the `#[requires]` now states the `[-q, q)` range for `r`
    and `hint in {0, 1}` as well as pinning `gamma2`, so every hypothesis of
    `use_one_hint_spec` comes out of the generated `pre`.

    The decode is longhand because hax compiles `(a || b) && c && d && (e || f)`
    into nested `if`s with the `c && d` block DUPLICATED under each disjunct, and
    the `-FIELD_MODULUS` bound arrives as a CHECKED negation
    (`-. FIELD_MODULUS`, a `RustM I32`) that has to be resolved first. -/
theorem use_one_hint_spec_proof (gamma2 r hint : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.spec gamma2 r hint := by
  intro hpre
  have hFM : (libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS).val = 8380417 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
  have hneg : (-. libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS : RustM Std.I32)
      = .ok (-8380417)#i32 := by
    simp [libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS]
    rfl
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_one_hint.pre, hneg,
    Aeneas.Std.bind_tc_ok] at hpre
  have key : (-(8380417 : Int) ≤ r.val ∧ r.val < 8380417)
      ∧ (hint.val = 0 ∨ hint.val = 1) := by
    by_cases h2 : r ≥ (-8380417)#i32
    · by_cases h3 : r < libcrux_iot_ml_dsa.simd.traits.FIELD_MODULUS
      · refine ⟨⟨by scalar_tac, by scalar_tac⟩, ?_⟩
        by_cases h4 : hint = 0#i32
        · exact Or.inl (by scalar_tac)
        · exact Or.inr (by
            by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
            · rw [if_pos h1, if_pos h2, if_pos h3, if_neg h4] at hpre
              have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac
            · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
              · rw [if_neg h1, if_pos h5, if_pos h2, if_pos h3, if_neg h4] at hpre
                have := of_decide_eq_true (bool_of_holds_map_ok hpre); scalar_tac
              · rw [if_neg h1, if_neg h5] at hpre
                exact absurd (bool_of_holds_map_ok hpre) (by simp))
      · exfalso
        by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
        · rw [if_pos h1, if_pos h2, if_neg h3] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
        · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
          · rw [if_neg h1, if_pos h5, if_pos h2, if_neg h3] at hpre
            exact absurd (bool_of_holds_map_ok hpre) (by simp)
          · rw [if_neg h1, if_neg h5] at hpre
            exact absurd (bool_of_holds_map_ok hpre) (by simp)
    · exfalso
      by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
      · rw [if_pos h1, if_neg h2] at hpre
        exact absurd (bool_of_holds_map_ok hpre) (by simp)
      · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
        · rw [if_neg h1, if_pos h5, if_neg h2] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
        · rw [if_neg h1, if_neg h5] at hpre
          exact absurd (bool_of_holds_map_ok hpre) (by simp)
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · exact Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5)
      · rw [if_neg h1, if_neg h5] at hpre
        exact absurd (bool_of_holds_map_ok hpre) (by simp)
  exact triple_true_of_triple
    (Vector.Portable.Rounding.use_one_hint_spec gamma2 r hint hg key.1.1 key.1.2 key.2)

/-- Discharged OUTRIGHT. The `#[requires]` now carries the per-lane
    `[-q, q)` bound via `coefficients_in_field`, so `decompose_spec`'s `hbound`
    comes out of the generated `pre`. -/
theorem decompose_spec_proof (gamma2 : Std.I32)
    (simd_unit low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.spec gamma2 simd_unit low high := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.decompose.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field simd_unit = .ok true := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1), hok⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5), hok⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  have hbound : ∀ j : Nat, j < 8 →
      -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
        ∧ (simd_unit.values.val[j]!).val < (8380417 : Int) :=
    fun j hj => lane_in_field_true
      (coefficients_in_field_lanes simd_unit key.2 j hj)
  exact triple_true_of_triple
    (Vector.Portable.Rounding.decompose_spec gamma2 simd_unit low high key.1 hbound)

/-- Discharged OUTRIGHT. `use_hint`'s `#[requires]` carries both missing pieces
    -- the per-lane `[-q, q)` bound and `hint[j] ∈ {0, 1}` -- via
    `coefficients_in_field` and `coefficients_are_hints`. -/
theorem use_hint_spec_proof (gamma2 : Std.I32)
    (simd_unit hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.spec gamma2 simd_unit hint := by
  intro hpre
  have hok := eq_ok_true_of_holds_map hpre
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.use_hint.pre] at hok
  have key : (gamma2 = 95232#i32 ∨ gamma2 = 261888#i32)
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_in_field simd_unit = .ok true
      ∧ libcrux_iot_ml_dsa.simd.portable.arithmetic.coefficients_are_hints hint = .ok true := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · rw [if_pos h1] at hok
      obtain ⟨hf, hh⟩ := bind_if_ok_true hok
      exact ⟨Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1), hf, hh⟩
    · rw [if_neg h1] at hok
      by_cases h5 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V261_888
      · rw [if_pos h5] at hok
        obtain ⟨hf, hh⟩ := bind_if_ok_true hok
        exact ⟨Or.inr (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using h5), hf, hh⟩
      · exfalso; rw [if_neg h5] at hok; simp at hok
  have hbound : ∀ j : Nat, j < 8 →
      -(8380417 : Int) ≤ (simd_unit.values.val[j]!).val
        ∧ (simd_unit.values.val[j]!).val < (8380417 : Int) :=
    fun j hj => lane_in_field_true
      (coefficients_in_field_lanes simd_unit key.2.1 j hj)
  have hhint : ∀ j : Nat, j < 8 →
      (hint.values.val[j]!).val = 0 ∨ (hint.values.val[j]!).val = 1 :=
    fun j hj => lane_is_hint_true
      (coefficients_are_hints_lanes hint key.2.2 j hj)
  exact triple_true_of_triple
    (Vector.Portable.Rounding.use_hint_spec gamma2 simd_unit hint key.1 hbound hhint)

/-! ## The `gamma2 != i32::MIN` group

    Here the generated `pre` is too weak to yield the theorems' `hg` at all, so
    `hg` itself is what has to be supplied. -/

/-- Discharged OUTRIGHT: the `#[requires]` now pins `gamma2` to the two FIPS-204
    values, which is exactly the theorem's `hg`. -/
theorem compute_hint_spec_proof
    (low high : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients)
    (gamma2 : Std.I32)
    (hint : libcrux_iot_ml_dsa.simd.portable.vector_type.Coefficients) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_hint.spec
      low high gamma2 hint := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  exact triple_true_of_triple
    (Vector.Portable.Rounding.compute_hint_spec low high gamma2 hint hg)

/-- Discharged OUTRIGHT, and the most informative case: the one ML-DSA function
    with an `#[ensures]`, so the generated `post` is a real property
    (`0 <= out <= 1`) rather than `True` -- delivered by the existing theorem,
    which proves `r.val in {0, 1}`. The `#[requires]` now pins `gamma2`. -/
theorem compute_one_hint_spec_proof (low high gamma2 : Std.I32) :
    libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.spec
      low high gamma2 := by
  intro hpre
  have hg : gamma2 = 95232#i32 ∨ gamma2 = 261888#i32 := by
    by_cases h1 : gamma2 = libcrux_iot_ml_dsa.constants.GAMMA2_V95_232
    · exact Or.inl (by simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V95_232] using h1)
    · simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.pre,
        if_neg h1] at hpre
      exact Or.inr (by
        simpa [libcrux_iot_ml_dsa.constants.GAMMA2_V261_888] using
          of_decide_eq_true (bool_of_holds_map_ok hpre))
  obtain ⟨v, hv_eq, -, hv_01⟩ :=
    triple_exists_ok (Vector.Portable.Rounding.compute_one_hint_spec low high gamma2 hg)
  refine triple_of_ok hv_eq ?_
  -- the generated post is `if out >= 0 then out <= 1 else false`
  simp only [libcrux_iot_ml_dsa.simd.portable.arithmetic.compute_one_hint.post]
  rw [if_pos (show v ≥ 0#i32 from by scalar_tac)]
  exact holds_map_ok_of_bool (by simp; scalar_tac)

end libcrux_iot_ml_dsa.Verification
