-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: type definitions
import Aeneas
import CoreModels
import LibcruxIotSha3.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libcrux_iot_sha3

/-- [libcrux_iot_sha3::lane::Lane2U32]
    Source: 'sha3/src/lane.rs', lines 7:0-7:41
    Visibility: public -/
@[reducible]
def lane.Lane2U32 := Array Std.U32 2#usize

/-- [libcrux_iot_sha3::state::KeccakState]
    Source: 'sha3/src/state.rs', lines 9:0-14:1 -/
structure state.KeccakState where
  st : Array lane.Lane2U32 25#usize
  c : Array lane.Lane2U32 5#usize
  d : Array lane.Lane2U32 5#usize
  i : Std.Usize

/-- [libcrux_iot_sha3::keccak::KeccakXofState]
    Source: 'sha3/src/keccak.rs', lines 14:0-25:1 -/
structure keccak.KeccakXofState (RATE : Std.Usize) where
  inner : state.KeccakState
  buf : Array Std.U8 RATE
  buf_len : Std.Usize
  sponge : Bool

/-- [libcrux_iot_sha3::keccak::{libcrux_iot_sha3::keccak::KeccakXofState<RATE>}::absorb_full::closure]
    Source: 'sha3/src/keccak.rs', lines 118:37-118:73 -/
def keccak.KeccakXofState.absorb_full.closure (RATE : Std.Usize) :=
  Std.Usize × Std.Usize

/-- [libcrux_iot_sha3::state::{libcrux_iot_sha3::state::KeccakState}::store::closure]
    Source: 'sha3/src/state.rs', lines 100:37-100:69 -/
def state.KeccakState.store.closure (RATE : Std.Usize) :=
  Slice Std.U8 × Std.Usize

/-- [libcrux_iot_sha3::keccak::_squeeze::closure]
    Source: 'sha3/src/keccak.rs', lines 233:33-235:9 -/
def keccak._squeeze.closure (RATE : Std.Usize) :=
  Slice Std.U8 × Std.Usize × Std.Usize

/-- [libcrux_iot_sha3::state::store_block_2u32::closure]
    Source: 'sha3/src/state.rs', lines 164:33-164:65 -/
def state.store_block_2u32.closure (RATE : Std.Usize) :=
  Slice Std.U8 × Std.Usize

/-- [libcrux_iot_sha3::keccak::keccak::closure#1]
    Source: 'sha3/src/keccak.rs', lines 2726:37-2728:13 -/
def keccak.keccak.closure_1 (RATE : Std.Usize) (DELIM : Std.U8) :=
  Slice Std.U8 × Std.Usize × Std.Usize

/-- [libcrux_iot_sha3::keccak::keccak::closure]
    Source: 'sha3/src/keccak.rs', lines 2711:33-2711:94 -/
@[reducible]
def keccak.keccak.closure (RATE : Std.Usize) (DELIM : Std.U8) := Std.Usize

/-- [libcrux_iot_sha3::Algorithm]
    Source: 'sha3/src/lib.rs', lines 92:0-104:1
    Visibility: public -/
@[discriminant u32 [1,2,3,4]]
inductive Algorithm where
| Sha224 : Algorithm
| Sha256 : Algorithm
| Sha384 : Algorithm
| Sha512 : Algorithm

/-- Trait declaration: [libcrux_iot_sha3::incremental::private::Sealed]
    Source: 'sha3/src/lib.rs', lines 431:8-431:27
    Visibility: public -/
structure incremental.private.Sealed (Self : Type) where

/-- [libcrux_iot_sha3::incremental::Shake128Xof]
    Source: 'sha3/src/lib.rs', lines 438:4-440:5
    Visibility: public -/
structure incremental.Shake128Xof where
  state : keccak.KeccakXofState 168#usize

/-- [libcrux_iot_sha3::incremental::Shake256Xof]
    Source: 'sha3/src/lib.rs', lines 443:4-445:5
    Visibility: public -/
structure incremental.Shake256Xof where
  state : keccak.KeccakXofState 136#usize

/-- Trait declaration: [libcrux_iot_sha3::incremental::Xof]
    Source: 'sha3/src/lib.rs', lines 450:4-489:5
    Visibility: public -/
structure incremental.Xof (Self : Type) (RATE : Std.Usize) where
  privateSealedInst : incremental.private.Sealed Self
  new : RustM Self
  absorb : Self → Slice Std.U8 → RustM Self
  absorb_final : Self → Slice Std.U8 → RustM Self
  squeeze : Self → Slice Std.U8 → RustM (Self × (Slice Std.U8))

end libcrux_iot_sha3
